### ISSUE TITLE
Update GDAS initialization scripts for GFS v16

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#102]
The GDAS initialization scripts must be updated to support v16 cycled experiments - with and without the Incremental Analysis Update (IAU).

**Comment by GeorgeGayno-NOAA** [comment]
Some new requirements from @KateFriedman-NOAA to help the gdas_init utility work with the global workflow.

- Add option to support GFS free forecast mode: read data from the GFS tarball, don't run chgres for the enkf members, and don't save the 'abias' or 'radstat' files.  Place data under a directory with the name - gfs.YYYYMMDD.
- Some of the chgres run scripts contain variable CINP, which sets the resolution of the input data.  Update the logic so it can be overridden if the user decides.

**Comment by edwardhartnett** [comment]
Is there a test for these changes?

**Comment by GeorgeGayno-NOAA** [comment]
> Is there a test for these changes?

There are no official tests for the gdas initialization scripts.  What I typically do is run them manually on all supported machines to ensure they work and output all required files.  The utility does two things - 1) pulls the required data from HPSS, 2) runs chgres_cube to create coldstart files for the GDAS and 80 ENKF members.  So I don't know if they can be run easily under github actions.   I am open to suggestions.

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA I just updated my branch for the official v16 tarballs.  Due to a quirk in how the switchover was done, I could not find a complete set of v15 or v16 data for cycle 2021032100.  I am not sure what to do.  So I added an error message if someone picks that cycle.  Do you have a better idea?

**Comment by KateFriedman-NOAA** [comment]
So our EMC v16rt2n parallel was archiving NCO parallel output and it includes that cycle:

/5year/NCEPDEV/emc-global/emc.glopara/WCOSS_D/gfsv16/v16rt2n/2021032100

These runhistory tarballs for that cycle look like the v16 ones though (based on their names and contents):

```
> hpsstar dir /NCEPPROD/hpssprod/runhistory/rh2021/202103/20210321 | grep "00.gfs"
[connecting to hpsscore1.fairmont.rdhpcs.noaa.gov/1217]
-rw-r-----    1 nwprod    rstprod  12444320768 Mar 23 06:25 com_gfs_prod_gfs.20210321_00.gfs.tar
-rw-r--r--    1 nwprod    prod         1870624 Mar 23 06:25 com_gfs_prod_gfs.20210321_00.gfs.tar.idx
-rw-r--r--    1 nwprod    prod     62759898624 Mar 23 06:34 com_gfs_prod_gfs.20210321_00.gfs_flux.tar
-rw-r--r--    1 nwprod    prod          214816 Mar 23 06:34 com_gfs_prod_gfs.20210321_00.gfs_flux.tar.idx
-rw-r--r--    1 nwprod    prod     129383747072 Mar 23 07:35 com_gfs_prod_gfs.20210321_00.gfs_nca.tar
-rw-r--r--    1 nwprod    prod           23328 Mar 23 07:35 com_gfs_prod_gfs.20210321_00.gfs_nca.tar.idx
-rw-r--r--    1 nwprod    prod     138694863872 Mar 23 07:59 com_gfs_prod_gfs.20210321_00.gfs_ncb.tar
-rw-r--r--    1 nwprod    prod           26912 Mar 23 07:59 com_gfs_prod_gfs.20210321_00.gfs_ncb.tar.idx
-rw-r--r--    1 nwprod    prod     142071005184 Mar 23 07:02 com_gfs_prod_gfs.20210321_00.gfs_pgrb2.tar
-rw-r--r--    1 nwprod    prod          482080 Mar 23 07:02 com_gfs_prod_gfs.20210321_00.gfs_pgrb2.tar.idx
-rw-r--r--    1 nwprod    prod     61489506304 Mar 23 07:11 com_gfs_prod_gfs.20210321_00.gfs_pgrb2b.tar
-rw-r--r--    1 nwprod    prod          482080 Mar 23 07:11 com_gfs_prod_gfs.20210321_00.gfs_pgrb2b.tar.idx
-rw-r--r--    1 nwprod    prod     19702107136 Mar 23 07:15 com_gfs_prod_gfs.20210321_00.gfs_restart.tar
-rw-r--r--    1 nwprod    prod            8992 Mar 23 07:15 com_gfs_prod_gfs.20210321_00.gfs_restart.tar.idx
-rw-r--r--    1 nwprod    prod     18656000000 Mar 23 08:02 com_gfs_prod_gfs.20210321_00.gfswave_output.tar
-rw-r--r--    1 nwprod    prod         1714976 Mar 23 08:02 com_gfs_prod_gfs.20210321_00.gfswave_output.tar.idx
-rw-r--r--    1 nwprod    prod     30737774592 Mar 23 08:08 com_gfs_prod_gfs.20210321_00.gfswave_raw.tar
-rw-r--r--    1 nwprod    prod          530720 Mar 23 08:08 com_gfs_prod_gfs.20210321_00.gfswave_raw.tar.idx
```

So it looks like the v15 output is missing(?). Unless they will be overwriting those tarballs with v15 output, I know data is still moving around on WCOSS.

Thanks for updating your branch for the official v16 tarballs. I will update my copy and test it for v16 in the next week. I need to also retest the other GFS versions and options to finish ironing out my changes for the workflow. I'll keep you updated on that and when I'm ready for your branch to go in.

**Comment by GeorgeGayno-NOAA** [comment]
> So our EMC v16rt2n parallel was archiving NCO parallel output and it includes that cycle:
> 
> /5year/NCEPDEV/emc-global/emc.glopara/WCOSS_D/gfsv16/v16rt2n/2021032100
> 
> These runhistory tarballs for that cycle look like the v16 ones though (based on their names and contents):
> 
> ```
> > hpsstar dir /NCEPPROD/hpssprod/runhistory/rh2021/202103/20210321 | grep "00.gfs"
> [connecting to hpsscore1.fairmont.rdhpcs.noaa.gov/1217]
> -rw-r-----    1 nwprod    rstprod  12444320768 Mar 23 06:25 com_gfs_prod_gfs.20210321_00.gfs.tar
> -rw-r--r--    1 nwprod    prod         1870624 Mar 23 06:25 com_gfs_prod_gfs.20210321_00.gfs.tar.idx
> -rw-r--r--    1 nwprod    prod     62759898624 Mar 23 06:34 com_gfs_prod_gfs.20210321_00.gfs_flux.tar
> -rw-r--r--    1 nwprod    prod          214816 Mar 23 06:34 com_gfs_prod_gfs.20210321_00.gfs_flux.tar.idx
> -rw-r--r--    1 nwprod    prod     129383747072 Mar 23 07:35 com_gfs_prod_gfs.20210321_00.gfs_nca.tar
> -rw-r--r--    1 nwprod    prod           23328 Mar 23 07:35 com_gfs_prod_gfs.20210321_00.gfs_nca.tar.idx
> -rw-r--r--    1 nwprod    prod     138694863872 Mar 23 07:59 com_gfs_prod_gfs.20210321_00.gfs_ncb.tar
> -rw-r--r--    1 nwprod    prod           26912 Mar 23 07:59 com_gfs_prod_gfs.20210321_00.gfs_ncb.tar.idx
> -rw-r--r--    1 nwprod    prod     142071005184 Mar 23 07:02 com_gfs_prod_gfs.20210321_00.gfs_pgrb2.tar
> -rw-r--r--    1 nwprod    prod          482080 Mar 23 07:02 com_gfs_prod_gfs.20210321_00.gfs_pgrb2.tar.idx
> -rw-r--r--    1 nwprod    prod     61489506304 Mar 23 07:11 com_gfs_prod_gfs.20210321_00.gfs_pgrb2b.tar
> -rw-r--r--    1 nwprod    prod          482080 Mar 23 07:11 com_gfs_prod_gfs.20210321_00.gfs_pgrb2b.tar.idx
> -rw-r--r--    1 nwprod    prod     19702107136 Mar 23 07:15 com_gfs_prod_gfs.20210321_00.gfs_restart.tar
> -rw-r--r--    1 nwprod    prod            8992 Mar 23 07:15 com_gfs_prod_gfs.20210321_00.gfs_restart.tar.idx
> -rw-r--r--    1 nwprod    prod     18656000000 Mar 23 08:02 com_gfs_prod_gfs.20210321_00.gfswave_output.tar
> -rw-r--r--    1 nwprod    prod         1714976 Mar 23 08:02 com_gfs_prod_gfs.20210321_00.gfswave_output.tar.idx
> -rw-r--r--    1 nwprod    prod     30737774592 Mar 23 08:08 com_gfs_prod_gfs.20210321_00.gfswave_raw.tar
> -rw-r--r--    1 nwprod    prod          530720 Mar 23 08:08 com_gfs_prod_gfs.20210321_00.gfswave_raw.tar.idx
> ```
> 
> So it looks like the v15 output is missing(?). Unless they will be overwriting those tarballs with v15 output, I know data is still moving around on WCOSS.
> 
> Thanks for updating your branch for the official v16 tarballs. I will update my copy and test it for v16 in the next week. I need to also retest the other GFS versions and options to finish ironing out my changes for the workflow. I'll keep you updated on that and when I'm ready for your branch to go in.

Yes, v15 was still officially OPS at 2021032100, so where are the v15 tarballs?  Those are the v16 tarballs as you noted.

**Comment by KateFriedman-NOAA** [comment]
Don't know about the v15 tarballs, I'll shoot an email off to SPA Jen to inquire.

FYI, Russ just had all of the v16rt2n tarballs that were under the emc.gloparadev space on HPSS consolidated under the emc.glopara space. So I'm reconfirming that is the pickup location for pre-implementation tarballs from the NCO parallel.

/NCEPDEV/emc-global/5year/emc.glopara/WCOSS_D/gfsv16/v16rt2n

**Comment by GeorgeGayno-NOAA** [comment]
> Don't know about the v15 tarballs, I'll shoot an email off to SPA Jen to inquire.
> 
> FYI, Russ just had all of the v16rt2n tarballs that were under the emc.gloparadev space on HPSS consolidated under the emc.glopara space. So I'm reconfirming that is the pickup location for pre-implementation tarballs from the NCO parallel.
> 
> /NCEPDEV/emc-global/5year/emc.glopara/WCOSS_D/gfsv16/v16rt2n

Ok. So you want me to keep the option to use v16 pre-implementation data?

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA I've retested your feature/gdas_init.v16 branch on Hera for all supported GFS versions (v12, v13, v14, v15, v16 retro, v16 ops). I had no issues running chgres_cube via a global-workflow job. Tests:

v12: 
/scratch1/NCEPDEV/global/Kate.Friedman/expdir/ffv12
/scratch1/NCEPDEV/stmp4/Kate.Friedman/comrot/ffv12

v13: 
/scratch1/NCEPDEV/global/Kate.Friedman/expdir/ffv13
/scratch1/NCEPDEV/stmp4/Kate.Friedman/comrot/ffv13

v14: 
/scratch1/NCEPDEV/global/Kate.Friedman/expdir/ffv14
/scratch1/NCEPDEV/stmp4/Kate.Friedman/comrot/ffv14

v15: 
/scratch1/NCEPDEV/global/Kate.Friedman/expdir/ffv15
/scratch1/NCEPDEV/stmp4/Kate.Friedman/comrot/ffv15

v16 retro: 
/scratch1/NCEPDEV/global/Kate.Friedman/expdir/ffv16r
/scratch1/NCEPDEV/stmp4/Kate.Friedman/comrot/ffv16r

v16 ops: 
/scratch1/NCEPDEV/global/Kate.Friedman/expdir/ffv16o
/scratch1/NCEPDEV/stmp4/Kate.Friedman/comrot/ffv16o

Going to run the same tests on WCOSS-Dell to confirm no issues there. Then will be ready for feature/gdas_init.v16 to go into UFS_UTILS develop. Thanks!

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA I'm ready for this work to move into develop. I'm wrapping up testing my branch for this work on the workflow side and will be ready for a new hash or tag from UFS_UTILS that includes these updates. Thanks!

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA I'm ready for this work to move into develop. I'm wrapping up testing my branch for this work on the workflow side and will be ready for a new hash or tag from UFS_UTILS that includes these updates. Thanks!

Ok, Kate. Glad to finally get this merged. Will create a release for you.

**Comment by KateFriedman-NOAA** [comment]
> Will create a release for you.

Wonderful, thanks @GeorgeGayno-NOAA !
