### ISSUE TITLE
nemsio utilities belong in nemsio library

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/UFS_UTILS#104]
The NEMSIO utilities such as `nemsio_read`, `nemsio_get`, `nemsio_chgdate`, `mkgfsnemsioctl` belong with the [NCEPLIBS-nemsio](https://github.com/NOAA-EMC/NCEPLIBS-nemsio) as a change to the library API most certainly will need an update to these utilities.

Associated `ctests` should be added to ensure these utilities and the library are in agreement.

**Comment by aerorahul** [comment]
See [ctest](https://github.com/aerorahul/NCEPLIBS-nemsio/tree/feature/ctest) implementation of the library.

**Comment by GeorgeGayno-NOAA** [comment]
> The NEMSIO utilities such as nemsio_read, nemsio_get, nemsio_chgdate, mkgfsnemsioctl belong with the NCEPLIBS-nemsio as a change to the library API most certainly will need an update to these utilities.
> Associated ctests should be added to ensure these utilities and the library are in agreement.

@aerorahul, I would have to agree with you.  I am concerned that EMC and the 'community' view the UFS_UTILS repository as a 'junk box' that should hold everyone's favorite utility.  That is not sustainable.

**Comment by Hang-Lei-NOAA** [comment]
This will be moved to nemsio lib as utilities.
Hang

**Comment by GeorgeGayno-NOAA** [comment]
For details, see this pull request: https://github.com/NOAA-EMC/NCEPLIBS-nemsio/pull/11

**Comment by GeorgeGayno-NOAA** [comment]
Kate verified that `nemsioget` is used by the global workflow.  So don't remove until the new nemsio library get installed.

**Comment by aerorahul** [comment]
[NCEPLIBS-nemsio](https://github.com/NOAA-EMC/NCEPLIBS-nemsio/pull/11) now contains the nemsio utilities.
nemsio utilities are used in the global-workflow and will need to be preserved in UFS_UTILS until they are installed with the new nemsio library.
However, future public releases do not need to include these nemsio utilities in UFS-utils.

**Comment by GeorgeGayno-NOAA** [comment]
The updated nemsio library (which includes the nemsio utilities) has been installed on all supported machines.  I will open a branch to remove them from UFS_UTILS.  Thanks to the library team for making my life a bit easier.

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA gave her blessing to remove `nemsioget` from the head of 'develop'.  The global-workflow is currently using the GFS v16 release branch.  I will not remove it from the release branch.  In the coming months, the global-workflow will be moving to the hpc-stack.

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA  I forgot about this issue.  These utilities are part of the hpc-stack version of the nemsio library.  And the stack has been installed on all machines (except the Cray).  I will do a PR.

**Comment by Hang-Lei-NOAA** [comment]
Yes, These have been a part of nemio library for future installations in
all forms (hpc-stack, NCEPLIB umbrella, individual etc.).

**Comment by KateFriedman-NOAA** [comment]
Thanks @GeorgeGayno-NOAA and @Hang-Lei-NOAA for removing from UFS_UTILS after getting them into the stack. I'll be looking at the stack more once I return from holiday leave. Happy holidays and happy new year!
