### ISSUE TITLE
Update chgres_cube to process Thompson ice- and water-friendly aerosols

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#106]
Update to read in the monthly aerosol climatology, time interpolate to the run time, then horizontally and vertically interpolate it to the model grid.

The climo file is  QNWFA_QNIFA_SIGMA_MONTHLY.dat.nc and located on Hera: 
/scratch1/BMC/gsd-fv3-dev/Judy.K.Henderson/test/gw_ccpp_v16b/sorc/aeroconv.fd/INPUT

**Comment by climbfuji** [comment]
Thanks, @GeorgeGayno-NOAA. Let me know if I can be of help, please.

**Comment by GeorgeGayno-NOAA** [comment]
Provided coldstart files (with and without the Thompson tracers) for a C96 global uniform grid and a C768 regional grid to @climbfuji.  He ran 48-hour tests and the results looked good.  Will submit a pull request.

**Comment by GeorgeGayno-NOAA** [comment]
The branch at 35240ea was successfully compiled on Hera, Jet, WCOSS-Cray and WCOSS-Dell.  And the chgres_cube regression tests passed on these machines.  Will submit a pull request.

**Comment by GeorgeGayno-NOAA** [comment]
Note: @KateFriedman-NOAA has placed the Thompson climatology file under the 'fix_am' directory on our officially supported machines.

**Comment by GeorgeGayno-NOAA** [comment]
Merged to 'develop' at 9a036a5.  Deleting branch and closing ticket.
