### ISSUE TITLE
Missing values in the coordinate lon lat variables in the regional orog file

### ISSUE THREAD

**Issue by BinLiu-NOAA** [NOAA-EMC/UFS_UTILS#11]
There are some strange missing values (see the 0.9969E+37 values below) in the two netcdf coordinate variables (lon and lat) in the orography files for the regional FV3SAR and HAFS configurations, e.g., C768_oro_data.tile7.halo0.nc. The geolon and geolat variables, however, look normal.

Not sure whether these missing coordinate lon/lat values matter or not. But it might be better to fill them with reasonable values or just use npx, npy as coordinate variables.

BTW, when checking the lon, lat values in the sfc_data.tile7.nc and gfs_data.tile7.nc files (generated by chgres), they all look normal though.

Variable: f
Type: file
filename:   oro_data
path:   oro_data.nc
   file global attributes:
   dimensions:
      lon = 2560
      lat = 2160
   variables:
      float lon ( lon )
         cartesian_axis :   X

      float lat ( lat )
         cartesian_axis :   Y

      float geolon ( lat, lon )

      float geolat ( lat, lon )

      float slmsk ( lat, lon )

      float land_frac ( lat, lon )

      float orog_raw ( lat, lon )

      float orog_filt ( lat, lon )

      float stddev ( lat, lon )

      float convexity ( lat, lon )

      float oa1 ( lat, lon )

      float oa2 ( lat, lon )

      float oa3 ( lat, lon )

      float oa4 ( lat, lon )

      float ol1 ( lat, lon )

      float ol2 ( lat, lon )

      float ol3 ( lat, lon )

      float ol4 ( lat, lon )

      float theta ( lat, lon )

      float gamma ( lat, lon )

      float sigma ( lat, lon )

      float elvmax ( lat, lon )

Coordinates:

     lon:

   337.1       337.1       337.0       337.0       337.0       336.9
   336.9       336.9       336.9       336.8       336.8       336.8
   336.8       336.7       336.7       336.7       336.7       336.6
   336.6       336.6       336.6       336.5       336.5       336.5
   336.4       336.4       336.4       336.4       336.3       336.3
   336.3       336.3       336.2       336.2       336.2       336.2
   336.1       336.1       336.1       336.0       336.0       336.0
...
   246.3       246.3       246.3       246.2       246.2       246.2
  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37
  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37
  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37
  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37
  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37
  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37
  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37
  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37
  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37
  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37
  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37
...
  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37
  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37
  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37

     lat:

   44.88       44.86       44.84       44.82       44.79       44.77
   44.75       44.73       44.70       44.68       44.66       44.64
   44.61       44.59       44.57       44.54       44.52       44.50
   44.48       44.45       44.43       44.41       44.39       44.36
...
  -6.162      -6.186      -6.209      -6.233      -6.256      -6.280
  -6.303      -6.327      -6.350      -6.374      -6.398      -6.421
  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37
  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37  0.9969E+37

**Comment by GeorgeGayno-NOAA** [comment]
We suspect the 'lat' and 'lon' records in the orography file are not used.  So instead of fixing this bug, maybe we can remove these records.

**Comment by GeorgeGayno-NOAA** [comment]
> We suspect the 'lat' and 'lon' records in the orography file are not used.  So instead of fixing this bug, maybe we can remove these records.

I removed those records, then ran the forecast model (C96 global).  The model ran fine.

**Comment by GeorgeGayno-NOAA** [comment]
Merged to 'develop' at 7448e0a.   Closing ticket.
