### ISSUE TITLE
Add flexibility for number of soil levels

### ISSUE THREAD

**Issue by barlage** [NOAA-EMC/UFS_UTILS#119]
Some locations in sfcsub.F are hard-coded to 2/4 soil levels (e.g., see below). To facilitate the use of general land surface models that have different soil configurations, this hard coding needs to be replaced with a more flexible solution.

```
        if(lsoil.gt.2) then
        call monitr('smcclm3',smcclm(1,3),sliclm,snoclm,len)
        call monitr('smcclm4',smcclm(1,4),sliclm,snoclm,len)
        call monitr('stcclm3',stcclm(1,3),sliclm,snoclm,len)
        call monitr('stcclm4',stcclm(1,4),sliclm,snoclm,len)
        endif

```

**Comment by GeorgeGayno-NOAA** [comment]
@barlage What is the status on this?  Keep it open?

**Comment by edwardhartnett** [comment]
Is this issue still active?

**Comment by GeorgeGayno-NOAA** [comment]
@barlage Arun has asked us to close any issues that have not been updated in a while. Should we keep this open?

**Comment by barlage** [comment]
@GeorgeGayno-NOAA We can close it. I expect that this will come up again soon, but I've been expecting that for a while so we can address it then. When we start actively testing the regional model, there will be a desire for this soil level flexibility.
