### ISSUE TITLE
Issues with C48 orography

### ISSUE THREAD

**Issue by HenryWinterbottom-NOAA** [NOAA-EMC/UFS_UTILS#126]
The C48 orography values, specifically those for the cubed sphere tiles that cover the poles, have missing values for some of the points. 

Please see, on RDHPCS Hera: /scratch1/NCEPDEV/rstprod/Henry.Winterbottom/work/UFSRNR_DEMO/20161003000000/grids/atmos/ensemble/C48_oro_data.tile[36].nc.

The input files for the respective orog.x applications are, also on RDHPCS Hera: /scratch1/NCEPDEV/rstprod/Henry.Winterbottom/work/UFSRNR_DEMO/20161003000000/grids/atmos/ensemble/orog.input.tile0[36].

Finally, the standard out from the orog.x application for the respective tiles are, on RDHPCS Hera: /scratch1/NCEPDEV/rstprod/Henry.Winterbottom/work/UFSRNR_DEMO/20161003000000/grids/atmos/ensemble/ensemble.orog.tile0[36].out.

**Comment by GeorgeGayno-NOAA** [comment]
@HenryWinterbottom-NOAA I looked at your files with 'ncview' and 'grads'.  I don't see any missing values.  Can you be more specific?  What fields?  Are the bad points confined to the poles?

**Comment by HenryWinterbottom-NOAA** [comment]
@GeorgeGayno-NOAA Please see C48_oro_data.tile[36].nc beneath /scratch1/NCEPDEV/rstprod/Henry.Winterbottom/work/UFSRNR_DEMO/20161003000000/grids/atmos/ensemble. With ncview, I see values around land/ocean boundaries ~9e36 (e.g., missing values).

I am using ncview version 2.1.7.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA Please see C48_oro_data.tile[36].nc beneath /scratch1/NCEPDEV/rstprod/Henry.Winterbottom/work/UFSRNR_DEMO/20161003000000/grids/atmos/ensemble. With ncview, I see values around land/ocean boundaries ~9e36 (e.g., missing values).
> 
> I am using ncview version 2.1.7.

I am using the same version of ncview.  I think the bad values are the map background.  If you go under 'opts' and turn off the overlay, these bad values go away.

**Comment by HenryWinterbottom-NOAA** [comment]
@GeorgeGayno-NOAA I also just looked at the raw values via ncdump and confirm that the values are simply just zeros.

I am curious why, using the same version of ncview, that I didn't see the missing value artifacts when looking at the files beneath /scratch1/NCEPDEV/global/glopara/fix/fix_fv3/C48.

**Comment by HenryWinterbottom-NOAA** [comment]
@GeorgeGayno-NOAA Please disregard my comment above. For some reason the ncview configuration was changing. No idea why, but please go ahead and close this ticket.

Thank you for the help!

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA I also just looked at the raw values via ncdump and confirm that the values are simply just zeros.
> 
> I am curious why, using the same version of ncview, that I didn't see the missing value artifacts when looking at the files beneath /scratch1/NCEPDEV/global/glopara/fix/fix_fv3/C48.

Recently, a 'coordinate' attribute was added to each orography record so 'ncview' could plot a map background.  The files in the official 'fix_fv3' directory were created without this attribute many months ago.

As an aside, I would use the orography files in 'fix_fv3_gmted2010'  They use new and better USGS terrain data.

**Comment by HenryWinterbottom-NOAA** [comment]
@GeorgeGayno-NOAA Noted and thank you again!
