### ISSUE TITLE
Snow update bug in global_cycle program

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#129]
@ClaraDraper-NOAA uncovered a bug in the snow update logic in sfcsub.F.  To summarize:

- The snow depth observations were being converted to snow water equivalent using an assumed density of 0.1 (rather than just using them as snow depth).
- The model snow depth was being re-set from the model snow water equivalent assuming a snow density of 0.1.

For more details, see: https://drive.google.com/drive/folders/1bi2E_eL3ihNgt3T2us3ARSnh6_6Yvv4r?usp=sharing

**Comment by GeorgeGayno-NOAA** [comment]
She is working this under her fork: https://github.com/ClaraDraper-NOAA/UFS_UTILS/tree/snowDAupd

**Comment by GeorgeGayno-NOAA** [comment]
@ClaraDraper-NOAA I opened this issue for your snow updates to global_cycle. There has not been much activity lately. Should I close this?

**Comment by ClaraDraper-NOAA** [comment]
Yes, let's close it. in the tests I ran on this we found that fixing the bug had very little impact on the atmosphere. The decision was made back then to leave it unchanged, since we're working on replacing the snow DA entirely.
