### ISSUE TITLE
Updating FNMSKH to high-res land-sea mask for GFS.v16

### ISSUE THREAD

**Issue by yangfanglin** [NOAA-EMC/UFS_UTILS#14]
set FNMSKH=${FNMSKH:-${FIXam}/global_slmask.t1534.3072.1536.grb}
instead of
    FNMSKH=${FNMSKH:-${FIXam}/seaice_newland.grb}
to use high-res land-sea mask in global_chgres.sh and  global_cycle.sh  for interpolation of climatological SST etc.

This is needed to reduce lake temperature biases for GFS.v16 development.

**Comment by yangfanglin** [comment]
Changes have been made in fork https://github.com/yangfanglin/UFS_UTILS.  Ready to ask for pull

**Comment by GeorgeGayno-NOAA** [comment]
Work complete. Close issue.
