### ISSUE TITLE
Add regression test for GNU compiler

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#151]
@DusanJovic-NOAA recommends that UFS_UTILS should have regression tests for GNU compilers.   Or at a minimum, the repo should be compiled successfully with GNU before merges.

**Comment by GeorgeGayno-NOAA** [comment]
GNU-based NCEPLIBS are available on Hera, by using this module:
https://github.com/ufs-community/ufs-weather-model/blob/develop/modulefiles/hera.gnu/fv3

**Comment by GeorgeGayno-NOAA** [comment]
The branch at 6301855 was successfully compiled on Hera using Gnu.  

The chgres_cube and grid_gen regression tests ran to completion.  Results did not match the baseline, but that was expected.   

The global_cycle and snow2mdl tests failed - the executables broke with segmentation faults.  The ice2_blend test failed because the copygb2 step, which runs before the executable, failed because it could not find the libiopm5.so library.  I will likely need a Gnu version of copygb2.

chgres_cube and the grid generation programs are part of the public release.  So it is important they work with Gnu.  

The global_cycle, ice_blend and snow2mdl programs are not supported as part of the public release.  So, it is not as critical they work with Gnu.  I will think about whether to fix them under this issue or a future issue.

**Comment by GeorgeGayno-NOAA** [comment]
@DusanJovic-NOAA have I satisfied your request?

**Comment by GeorgeGayno-NOAA** [comment]
@JeffBeck-NOAA Under this issue I am renaming the build files - and some of the files are for your machines.  Who is the best person in your group to review these changes?

**Comment by DusanJovic-NOAA** [comment]
> @DusanJovic-NOAA have I satisfied your request?

Yes. Thanks.

**Comment by JeffBeck-NOAA** [comment]
> @JeffBeck-NOAA Under this issue I am renaming the build files - and some of the files are for your machines. Who is the best person in your group to review these changes?

@GeorgeGayno-NOAA, I don't see a related PR attached to this issue, so I'm assuming you're still working on this locally?  If you're referring to Odin/Stampede2, the contact people for those machines would be @LarissaReames-NOAA and @ywangwof.  For Cheyenne, it would be @JulieSchramm or @mkavulich.

**Comment by GeorgeGayno-NOAA** [comment]
Brach at 6840076 was successfully tested on Orion, Hera, Jet, WCOSS-Cray and WCOSS-Dell.  Will merge.

**Comment by GeorgeGayno-NOAA** [comment]
Merged to 'develop' at 1be59bd.  Closing issue.
