### ISSUE TITLE
CHGRES bug when using GRIB2 data

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#157]
When using GRIB2 data, the wgrib2 library writes an inventory file in model_grid.F90.  This file is written from all mpi tasks, then read later whenever a file record is degribbed.  When using large task counts, there is the possibility that one task may still be writing the inventory file while another task is trying to read it.  This was fixed in the medium release branch under PR #155.  Add this fix to develop.  Also, add @DusanJovic-NOAA suggestion to replace instances of 'mpif.h' with 'use mpi'.

**Comment by DusanJovic-NOAA** [comment]
It would be nice to replace all instances of `include 'netcdf.inc'` and `#include <netcdf.inc>` with `use netcdf`

**Comment by GeorgeGayno-NOAA** [comment]
The branch at 5a746ab was compiled on Hera, Orion, Jet, WCOSS-Cray and WCOSS-Dell.  The chgres, grid generation, and global_cycle regression tests all passed on these machines.  Will merge.

**Comment by GeorgeGayno-NOAA** [comment]
Merged to 'develop' at 745fdbd.  Closing issue.
