### ISSUE TITLE
Remove or replace "> /dev/null 2>&1" in the build_all.sh script

### ISSUE THREAD

**Issue by JeffBeck-NOAA** [NOAA-EMC/UFS_UTILS#161]
Piping the "source" and "module load build.$target" commands in build_all.sh to /dev/null results in any errors not being printed to the screen or to a file.  It would be best to either remove this part of the line, or pipe the output to a log file that can be viewed afterward.

@kgerheiser @LarissaReames-NOAA @JulieSchramm

**Comment by edwardhartnett** [comment]
Do we all agree this should be done? I can submit a PR with this change...

**Comment by edwardhartnett** [comment]
On further reflection this seems like an artifact of an old build system. In which case, it should be removed. If it is needed for regression testing, lets move it into the reg_tests directory.

**Comment by edwardhartnett** [comment]
Can we remove this file, now that the testing formerly known as regression has been automated?

**Comment by kgerheiser** [comment]
I don't see any harm in removing it

**Comment by JulieSchramm** [comment]
I think it can be removed, since the cmake build is used.

**Comment by kgerheiser** [comment]
Remove the whole file? My comment referred to piping the output `/dev/null`. `build_all.sh` is useful because it loads the requisite modules for you on each platform.

**Comment by GeorgeGayno-NOAA** [comment]
> Remove the whole file? My comment referred to piping the output `/dev/null`. `build_all.sh` is useful because it loads the requisite modules for you on each platform.

I agree. Please don't remove 'build_all.sh'.

**Comment by kgerheiser** [comment]
Could just get rid of the `2>&1` if you want to suppress non-error output.

**Comment by edwardhartnett** [comment]
I just removed the 2>&1. PR is up now.
