### ISSUE TITLE
Remove nemsiogfs library from global_chgres and all other places

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#167]
The NCEPLIBS-nemsiogfs library is scheduled for deprecation with the next release of NCEPLIBS. We believe this will not be a problem for any users, but it needs to be removed wherever it is offered as an option in UFS_UTILS.

See https://github.com/NOAA-EMC/NCEPLIBS/issues/126 for detailed discussion.

Please speak up now if you think this will be a problem for anyone. ;-)

@Hang-Lei-NOAA you will be interested in this issue.

**Comment by Hang-Lei-NOAA** [comment]
Thanks, George. So we can deprecate it without any problem.

**Comment by edwardhartnett** [comment]
Whenis global_chgres going to stop being used?

**Comment by GeorgeGayno-NOAA** [comment]
I am not aware that anyone is using it.  And the best way to prevent future users is to get rid of it now.

**Comment by edwardhartnett** [comment]
OK, shall I submit a PR removing it's directory and all contents?

**Comment by GeorgeGayno-NOAA** [comment]
> OK, shall I submit a PR removing it's directory and all contents?

If you want.  There are several associated scripts that should be removed as well.

**Comment by edwardhartnett** [comment]
Which scripts?

**Comment by GeorgeGayno-NOAA** [comment]
> Which scripts?

./ush/global_chgres.sh
./ush/global_chgres_driver.sh
