### ISSUE TITLE
Update documentation to match the MWR App v1.1.0 release

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#175]
The docs directory was updated for the MWR App v1.1.0 release (77d0099 and 7509be5).  Add these changes to 'develop'.

These changes also must be added to the SRW App release branch (release/public-v2)

**Comment by jwolff-ncar** [comment]
@GeorgeGayno-NOAA Also migrate any necessary updates to the release/public-v2 branch.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA Also migrate any necessary updates to the release/public-v2 branch.

Doing that now.

**Comment by GeorgeGayno-NOAA** [comment]
Update was made to develop (0d2bc7b) and release/public-v2 (64507a7).  Closing issue.
