### ISSUE TITLE
chgres_cube: Thompson aerosols are never created and written to file

### ISSUE THREAD

**Issue by LarissaReames-NOAA** [NOAA-EMC/UFS_UTILS#178]
The return statement in read_setup_namelist is a few lines too early, and before the if statement that sets use_thomp_mp_climo to true if thomp_mp_climo_file is set in the namelist. This prevents the aerosols from ever being created or written to file, regardless of input data type.

**Comment by GeorgeGayno-NOAA** [comment]
Merged to authoritative repo (develop) at 21543e0.  

Will leave open in case the same change needs to be made to the SRW App public release branch.

**Comment by GeorgeGayno-NOAA** [comment]
@LarissaReames-NOAA  Can this issue be closed?

**Comment by LarissaReames-NOAA** [comment]
> @LarissaReames-NOAA Can this issue be closed?

Yes, we fixed the issue in release/public-v2 as well. (https://github.com/NOAA-EMC/UFS_UTILS/pull/184)

Closed.
