### ISSUE TITLE
A few sea ice related issues in the NSST analysis

### ISSUE THREAD

**Issue by XuLi-NOAA** [NOAA-EMC/UFS_UTILS#18]
In the current NSST foundation temperature (Tf) analysis, a few sea ice related issues need to be resolved:
1. Tf analysis for the water-ice mixed grids (ice concentration > 15%)

2. The Tf evolution in prediction mode due to two SST climatology updates: (1) Seasonal tendency; (2) Relaxation to climatology

In this ticket, 
1. The Tf analysis for the grids with sea ice will be done in the stand-a-lone global_cycle step through a salinity dependent formula. 
2. The assigned value (currently, the frozen point, 271.2 K) will be re-visited, including the use of the SST climatology to help. 
3. Apply the two SST climatology updates to Tf for the grids with sea ice fraction

**Comment by XuLi-NOAA** [comment]
The item 3, Apply the two SST climatology updates to Tf for the grids with sea ice fraction, is not included in this review (will be done in the future).

1. The code change:

global_cycle.fd/cycle.f90
flobal_cycle.fd/read_write_data.f90

2. The scripts change:

ush/global_cycle.sh

3. Addition of a fix file (global_salclm.t1534.3072.1536.nc) to FIXam directory in global workflow

**Comment by SMoorthi-emc** [comment]
Xu,  I hope you are not hardwiring the minimum sea ice concentration.  In the GFS now we have namelist variables "min_seaice" and "min_lakeice".  While standalone GFS currently uses a value of 0.15 for both, in the coupled model I am using 1.0e-6 for min_seaice and 0.15 for min_lakeice.
Moorthi

**Comment by XuLi-NOAA** [comment]
Hi, Moorthi,

I am not using a hardwired  minimum sea ice concentration, I use the mask
(slifcs) to judge if the water temperature (for the grids when sea ice
exists) is calculated or not.

Xu

**Comment by GeorgeGayno-NOAA** [comment]
Work complete.  Closing issue.
