### ISSUE TITLE
branch protection rules for develop branch

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#183]
See https://github.com/NOAA-EMC/NCEPLIBS/issues/154

I have included admins in the rules. When CI is added (#182) it must be enforced in settings. Then this issue can close.

**Comment by GeorgeGayno-NOAA** [comment]
@edwardhartnett During the week of Nov 4th, there will be a training session for community users of the Medium Range Weather application (which includes UFS_UTILS).  We need to double check our repo security settings.  For example, I don't want members of the 'community' to open branches under the authoritative repo.  What else do we need to worry about?

**Comment by edwardhartnett** [comment]
No one will be able to open branches on our repo, except those people listed here:

![image](https://user-images.githubusercontent.com/38856240/97195923-7a910600-1771-11eb-8992-8e061db56bf0.png)

Since the repo is public, anyone may take a fork, and then create branches on that. That's how they may contribute pull requests against the code.

However, nothing will get merged to the repo except through the pull request process, including CI and review.

**Comment by edwardhartnett** [comment]
OK, I turned on branch protections. We will no longer be able to merge PRs if the CI fails.
