### ISSUE TITLE
Add doxygen documentation

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#191]
See https://github.com/NOAA-EMC/NCEPLIBS/issues/121

**Comment by edwardhartnett** [comment]
Are we all done with this issue? I think there is still more to do...

**Comment by GeorgeGayno-NOAA** [comment]
> Are we all done with this issue? I think there is still more to do...

I just opened another branch to add doxygen to the remaining dozen or so files.   So keep it open.

**Comment by edwardhartnett** [comment]
We need to add an overview of UFS_UTILS in the user_guide.md. This will include a (hyper-lined) list of all utilities, with a brief description.

I will submit a PR shortly. @GeorgeGayno-NOAA I'm going to need your help coming up with the descriptions...

**Comment by GeorgeGayno-NOAA** [comment]
> We need to add an overview of UFS_UTILS in the user_guide.md. This will include a (hyper-lined) list of all utilities, with a brief description.
> 
> I will submit a PR shortly. @GeorgeGayno-NOAA I'm going to need your help coming up with the descriptions...

No problem.

**Comment by edwardhartnett** [comment]
@lgannoaa, we need doxygen for UFS_UTILS on
* Every function/subroutine 
* Every public variable
* Every code file 

(Except for testing code, which is documented but not with doxygen. We do not include a description of our test code in the user documentation.)

More details about Doxygen can be found here:
https://github.com/NOAA-EMC/NCEPLIBS/issues/121

@jbathegit has a tip sheet which is posted in that thread. Jeff is very far along in applying doxygen to NCEPLIBS-bufr, and that's a great place to look for examples.

**Comment by GeorgeVandenberghe-NOAA** [comment]
Per suggestion I have (had already) been ignoring module CONTAINED docblock rendering  issues (while addressing other issues in those docblocks) since wednesday afternoon.  So this did not stop me.

**Comment by edwardhartnett** [comment]
Not sure hot this issue got closed. We will keep it open until we turn on WARN_AS_ERROR everywhere (perhaps with some exceptions), and fill in all "???" in the current documentation.

**Comment by edwardhartnett** [comment]
It's been a heck of an issue!

Documentation work will continue but I believe this issue can be called complete.
