### ISSUE TITLE
Point to new NCEPLIBS location on Jet

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#196]
UFS_UTILS currently points to Dom's NCEPLIBS here: /lfs4/HFIP/hfv3gfs/software/NCEPLIBS-ufs-v2.0.0beta01/intel-18.0.5.274/impi-2018.4.274

But that directory was recently removed.  Dom said to point to here: /lfs4/HFIP/hfv3gfs/software/NCEPLIBS-ufs-v2.0.0/intel-18.0.5.274/impi-2018.4.274

He also mentioned there is an umbrella module now which can be loaded instead of loading each library separately: /lfs4/HFIP/hfv3gfs/software/NCEPLIBS-ufs-v2.0.0/intel-18.0.5.274/impi-2018.4.274/modules/NCEPLIBS/2.0.0

**Comment by climbfuji** [comment]
I assume this issue is for the `release/public-v2` branch of UFS_UTILS? For develop, we should try to install the hpc-stack and point to those modules. I can do that, if necessary, but we need to dig up the old discussion of lifting jet to a tier-1 platform for ufs-weather-model regression testing with a formal agreement who is responsible for maintaining and testing.

**Comment by GeorgeGayno-NOAA** [comment]
> I assume this issue is for the `release/public-v2` branch of UFS_UTILS? For develop, we should try to install the hpc-stack and point to those modules. I can do that, if necessary, but we need to dig up the old discussion of lifting jet to a tier-1 platform for ufs-weather-model regression testing with a formal agreement who is responsible for maintaining and testing.

This is for 'develop'.  I did not know the hpc-stack was installed on Jet.  I am testing the hpc-stack under #152.  I did not think about the release branch.   Thanks for the reminder.

**Comment by climbfuji** [comment]
Let me try to install hpc-stack on jet today, it's not yet there but easy to get there.

Dom

**Comment by GeorgeGayno-NOAA** [comment]
My branch at 1809b6f was compiled on Jet.  And all regression tests passed.  Will merge.  Updates for the hpc stack on Jet will be done under #152.

**Comment by GeorgeGayno-NOAA** [comment]
Merged to 'develop' at 2d4fe87.   Closing.
