### ISSUE TITLE
Build GFSv16 tag with hpc stack libraries on Hera

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#197]
@KateFriedman-NOAA requested the GFS v16 tag be updated to build on Hera with the hpc stack libraries.  Will create a support branch from the `ops-gfsv16.0.0` tag for this update.

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA Try this branch to build on Hera using the hpc stack:
https://github.com/NOAA-EMC/UFS_UTILS/tree/support/ops-gfsv16.0.0

Go under ./sorc and you will see "build_all_ufs_utils.hpc.stack".  That will build with the hpc stack on Hera.  I can add Orion and Dell later.  The old build system was retained (for now) - 'build_all_ufs_utils.sh' still works on Hera and other supported machines.

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA This issue has not been updated in a while. What do you want to do with this?

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA I forgot about this, apologies! Since the develop branch of UFS_UTILS now uses hpc-stack this isn't needed. You can discontinue and close this issue. Thanks!

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA The `support/ops-gfsv16.0.0` branch was created under this issue. Can I delete that branch?

https://github.com/NOAA-EMC/UFS_UTILS/tree/support/ops-gfsv16.0.0

**Comment by KateFriedman-NOAA** [comment]
Yes, it can be deleted, thanks!

**Comment by GeorgeGayno-NOAA** [comment]
> Yes, it can be deleted, thanks!

Will do!
