### ISSUE TITLE
UFS_UTILS will not build with gnu v10+ compilers

### ISSUE THREAD

**Issue by mkavulich** [NOAA-EMC/UFS_UTILS#206]
This is due to stricter requirements on argument types between subroutines per the Fortran 2008 standards (https://www.scivision.co/gfortran-type-mismatch-error/).

**Comment by GeorgeGayno-NOAA** [comment]
@mkavulich  Can this be closed?

**Comment by mkavulich** [comment]
Sorry @GeorgeGayno-NOAA I thought this would auto-close when the PR was merged. 

Resolved by #205
