### ISSUE TITLE
Incorporate NESDIS VIIRS-based surface data

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#216]
NESDIS will deliver new VIIRS-based surface type (vegetation type) data. These data will have the same classification scheme (17-class IGBP + 3 EMC-suggested tundra classes). The data projection will be on the same grid/projection (30" global lat-lon) as the current MODIS-based data.

Incorporate this data into the grid generation process.

**Comment by barlage** [comment]
@GeorgeGayno-NOAA I would restate the issue as this:

NESDIS will deliver new VIIRS-based surface type (vegetation type) data. These data will have the same classification scheme (17-class IGBP + 3 EMC-suggested tundra classes). The data projection will be on the same grid/projection (30" global lat-lon) as the current MODIS-based data.

**Comment by GeorgeGayno-NOAA** [comment]
Began work on a program to convert the data to convenient global resolutions and output it in the format expected by sfc_climo_gen: `/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/climo_fields_netcdf/sorc/fv3.soilt.vegt.hires.netcdf`

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA shouldn't that program also be part of the repo?

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA shouldn't that program also be part of the repo?

Probably.  When I get the actual dataset from NESDIS I will find a place for the program.

**Comment by GeorgeGayno-NOAA** [comment]
@barlage I wrote some prototype programs to process the expected NESDIS data.   When will NESDIS deliver it?

**Comment by GeorgeGayno-NOAA** [comment]
A set of vegetation type files readable by the `sfc_climo_gen` program were created using 14e7237 on Dell (Venus).  The global files were created using `./util/veg_type/interp`.  The CONUS file was created using `./util/veg_type/chop`.  All files are in `/gpfs/dell2/emc/modeling/noscrub/George.Gayno/fv3.vegt.new.tundra.netcdf/fix_sfc_climo`

**Comment by GeorgeGayno-NOAA** [comment]
The `./ush/sfc_climo_gen.sh` script was updated at da7a9ed to point to the location of the new vegetation type file on Dell.  

Also, a new script - `./util/veg_type/sfc_climo_gen/run.sh` - was added to run (on Dell) the `sfc_climo_gen` program stand-alone, using the  'grid', 'orog' and 'mosaic' files used by GFS v16 (located in `./fix/fix_fv3_gmted2010/CXXX`)

**Comment by GeorgeGayno-NOAA** [comment]
Note, changing the vegetation type data will also change other static surface fields.  That is because permanent land ice points are identified by vegetation class 15.  And the soil type, substrate temperature, greenness fraction and slope type are adjusted to be consistent at land ice points.  For details, see routine `adjust_for_landice` in `./sorc/sfc_climo_gen/interp.F90`.  Therefore, users will need to replace all tiled surface fields for their tests - not just the the vegetation type files.

**Comment by GeorgeGayno-NOAA** [comment]
@barlage @HelinWei-NOAA @YihuaWu-NOAA 

How to create your own surface fields using the new veg type data.  Only works on Dell right now.  Only works for the global grids right now.

- Clone my fork - git clone git@github.com:GeorgeGayno-NOAA/UFS_UTILS.git
- Checkout the 'feature/vegt' branch
- Link to the fix directories - `./fix/link_fixdirs.sh emc dell`
- Build the repo - `build_all.sh`
- Edit the `./util/veg_type/sfc_climo_gen/run.sh` for the grid you want (variable $res)
- Run the script - `cat run.sh | bsub`.  Data will be in $SAVE_DIR

For experiments, you must replace all the surface files, not just the vegetation type files.  See
https://github.com/NOAA-EMC/UFS_UTILS/issues/216#issuecomment-738180158 for more details.

**Comment by HelinWei-NOAA** [comment]
Where should I put the input surface files?  WORK_DIR? Can you have a test
on those surface files
in /gpfs/dell3/ptmp/Helin.Wei/gfsv16newveg/gdas.20190701/18/RESTART? Thanks.

**Comment by edwardhartnett** [comment]
I'm super uncomfortable with all these changes going in without tests.

Can we stop updating UFS_UTILS code until we get some tests in place? Then we can require tests for all changes.

As it is, we are simply building up our technical debt here. This is the equivalent of paying the mortgage with a credit card. It's just procrastination to avoid writing test code for these changes...

**Comment by GeorgeGayno-NOAA** [comment]
> I'm super uncomfortable with all these changes going in without tests.
> 
> Can we stop updating UFS_UTILS code until we get some tests in place? Then we can require tests for all changes.
> 
> As it is, we are simply building up our technical debt here. This is the equivalent of paying the mortgage with a credit card. It's just procrastination to avoid writing test code for these changes...

@edwardhartnett  Helin just wants to start testing the data in the model.  We are months away from any pull requests.  It is possible the new data won't improve model results.  In that case a PR won't even happen.

**Comment by YihuaWu-NOAA** [comment]
I believe that the changes made by George is only on his branch.  So, we can check out his branch for testing.
When tastings are done and the results show that the new data can improve model performance, then a PR can be requested.

**Comment by GeorgeGayno-NOAA** [comment]
> Where should I put the input surface files? WORK_DIR? Can you have a test on those surface files in /gpfs/dell3/ptmp/Helin.Wei/gfsv16newveg/gdas.20190701/18/RESTART? Thanks.

@HelinWei-NOAA The new surface files are based on the GFS v16 'grid', 'oro', and 'mosaic' files here: `/gpfs/dell2/emc/modeling/noscrub/emc.glopara/git/fv3gfs/fix/fix_fv3_gmted2010/C768`  So I would make a local copy of that directory, then replace the surface files in `./fix_sfc` with the new ones based on the new veg type.   The next step will be to run `chgres_cube` using the new surface files.  I can set up a script for you to run chgres_cube.

**Comment by GeorgeGayno-NOAA** [comment]
@HelinWei-NOAA @YihuaWu-NOAA To use the tiled surface files in the forecast model, you will need to adjust the sfcsub namelist options.  For details, see my presentation from September: https://drive.google.com/file/d/1JjnDlRkM5ACjJGEym14SGNFGO2wTkkB7/view?usp=sharing

See slides 23 thru 26.

**Comment by GeorgeGayno-NOAA** [comment]
@HelinWei-NOAA A sample script and config file to run `chgres_cube` using the input data in `/gpfs/dell3/ptmp/Helin.Wei/gfsv16newveg/gfs.20190701/00`  is on Venus: `/gpfs/dell2/emc/modeling/noscrub/George.Gayno/fv3.vegt.new.tundra.netcdf/chgres_cube`

Some details on the config file namelist:
- fix_dir_target_grid - the directory where the tiled surface files (using the new veg data) reside
- mosaic_file_target_grid - points to the model mosaic file.  Want to use the GFS v16 version.
- orog_dir_target_grid - directory containing the 'grid' and 'oro' files.  Want to use the GFS v16 version.

**Comment by GeorgeGayno-NOAA** [comment]
@barlage To follow up on your question, the sfc_climo_gen code - which maps the vegetation type and other static surface fields - works with model grid boxes that are partial land.  There is logic that checks for the existence of the "lake_frac" record in the orography file.  If that record exists, then any point with a "land_frac" greater than zero will be assigned a veg type (and the other surface fields).  So if you use the run script in `./util/veg_type/sfc_climo_gen` and point to orography files with a 'lake_frac' record (via the FIX_FV3 variable), then it should do what you want.

**Comment by barlage** [comment]
OK, thanks @GeorgeGayno-NOAA . I know that Shan has the oro files that she is currently using (maybe you created those?). Just want to make sure that the surface files we create for the land spin-up is as close to final as possible to those used for the prototype 7 simulations.

**Comment by GeorgeGayno-NOAA** [comment]
> OK, thanks @GeorgeGayno-NOAA . I know that Shan has the oro files that she is currently using (maybe you created those?). Just want to make sure that the surface files we create for the land spin-up is as close to final as possible to those used for the prototype 7 simulations.

No, I don't recall how Shan created the files.  It is important that we know exactly how all of these fixed files were created before any official parallel testing begins.  In other words, we need to document that under this issue or another future issue. (i.e., What branch/commit number was used and what machine the files were created on).
