### ISSUE TITLE
Include 2D coordinate arrays (geolat and geolon) and associated variable attributes in orog.fd, chgres_cube.fd, and sfc_climo_gen.fd for correct output viewing in ncview

### ISSUE THREAD

**Issue by JeffBeck-NOAA** [NOAA-EMC/UFS_UTILS#22]

**Comment by JeffBeck-NOAA** [comment]
Gerard and I would like to work on this during the next couple weeks

**Comment by GeorgeGayno-NOAA** [comment]
I think everything is working.  Using cd0aafc on Hera, I created a C96 uniform global grid.  The 'oro' and 'surface' files had the required geo-referencing records.  I was able to add a map background when viewing them with 'ncview'.  I fed the 'oro' and 'surface' file into chgres_cube for a Feb 2, 2020 test case.  It ran without issue.  And the files output from chgres_cube had the required geo-referencing records, which were recognized by 'ncview'.  All files were then fed to the forecast model, which ran successfully for a 24-hour forecast.

**Comment by GeorgeGayno-NOAA** [comment]
After the reviewers gave their blessing, the branch at a3ea604 was compiled on Hera, Jet, Dell and Cray.  Then all regression tests were run.  As expected the `chgres_cube` and `grid_gen` regression tests failed.  The output files did not match the official baseline according to the `nccmp` utility.  However, the differences were due solely to the additional metadata and lat/lon records in the files.   All other records were identical, as they should be.

Will merge to the authoritative repository.

**Comment by GeorgeGayno-NOAA** [comment]
Merged to 'develop' at 7448e0a.  Closing ticket.
