### ISSUE TITLE
Release planning for next release

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#226]
I will start a project for the next release, and we can begin to do release planning on this repo.

@GeorgeGayno-NOAA I am going to select 1.1.0 as the next release number. Let me know if you think it should be something different.

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA what is this release about: ops-gefsv12.0.1?

What is this for? What is it named oddly?

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA what is this release about: ops-gefsv12.0.1?
> 
> What is this for? What is it named oddly?

That is the EIB naming convention for release branches and tags.  They are named after the operational system they support.  In this case the GEFS v12.

**Comment by edwardhartnett** [comment]
What is EIB? Are we required to follow their conventions?

Is this update to be included in the upcoming hpc-stack 1.1.0 release? (@kgerheiser )

**Comment by edwardhartnett** [comment]
OK, I see from google that EIB is the EMC Engineering and Implementation Branch (EIB). 

So this is a full release of UFS_UTILS? What is the version number of this release? I think we should do a proper version number, and version tag, just like the rest of NCEPLIBS.

If EIB need a special tag in their naming convention, we can add that as a tag that points to the release tag.

So is the recent release the 1.1.0 release of UFS_UTILS? If so, let's go through the release process for 1.1.0, and get start on the process for 1.2.0. And in the README, let's list the special tags that we use and indicate what versions of UFS_UTILS they refer to.
