### ISSUE TITLE
fortran warning about nested comments

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#231]
I see this:

`/home/ed/UFS_UTILS/sorc/fre-nctools.fd/tools/fregrid/bilinear_interp.c:1138: warning: Reached end of file while still inside a (nested) comment. Nesting level 4 (probable line reference: 933, 921, 916, 912)
`

Sure enough, there are some poorly nested comment delimiters in the file. I will fix and submit with my next batch of doxygen chagnes.

**Comment by edwardhartnett** [comment]
Similarly:

`/home/ed/UFS_UTILS/sorc/fre-nctools.fd/tools/make_hgrid/create_gnomonic_cubic_grid.c:1307: warning: Reached end of file while still inside a (nested) comment. Nesting level 1 (probable line reference: 1231)
`

**Comment by GeorgeGayno-NOAA** [comment]
@edwardhartnett Just curious which compiler is giving these warnings.  I tried Intel and Gnu (v9) on Hera and did not see this.

**Comment by edwardhartnett** [comment]
Doxygen gives them. ;-)
