### ISSUE TITLE
Filter_topo code seg fault with ESG grid

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#236]
@JiliDong-NOAA reported a seg fault in the filter_topo code when creating an ESG grid with these dimensions:

- idim=1301
- jdim=600
- delx/dely=0.0145
- target_lon=-97.5
- target_lat=35.5

The error occurs at line 725 of filter_topo.F90.

I am able to reproduce the error on Hera using 'develop' at 005f9a0.  It is due to an out-of-range subscript in this loop:

```
   else
      do t = 1, ntiles
         do j = js, je
            do i = is, ie+1
               dy(i,j,t) = dx(j,i,t)
            enddo
         enddo
      enddo
   endif
```

These arrays are allocated as follows:

```
  !--- compute dx, dy
    allocate(dx(isd:ied,jsd:jed+1,ntiles))
    allocate(dy(isd:ied+1,jsd:jed,ntiles))
```

I suspect the loop assumed square tiles.  But ESG grids can be certainly non-square.

**Comment by GeorgeGayno-NOAA** [comment]
Using the branch at 1c7e4bc on Hera, the problem reported by @JiliDong-NOAA is fixed.  And the grid generation regression tests passed.

**Comment by GeorgeGayno-NOAA** [comment]
@BenjaminBlake-NOAA @JeffBeck-NOAA @gsketefian I know you were involved with the implementation of the ESG grid.  Tom updated the filtering code for regional grids.  But he retired.  Who is the best expert for that code?  Is my fix reasonable?  Has anyone else encountered this problem?

**Comment by JeffBeck-NOAA** [comment]
@gsketefian, we've created many non-square ESG grids, so I'm wondering why we haven't run into this bug?

**Comment by gsketefian** [comment]
@JeffBeck-NOAA @GeorgeGayno-NOAA We have run into this bug.  That's why when using the ESGgrid, we set STRETCH_FAC to 0.999 instead of exactly 1 so as to not trigger that section of code (see line 124 in ush/set_gridparams_ESGgrid.sh and preceeding comments).  I remember fixing it a long time ago locally but never pushed it back because we didn't have have PRs, etc set up.  Then I completely forgot about it.  Glad it came up again.  Once this fix goes in we'll test again by setting our stretch_fac to 1.

**Comment by JeffBeck-NOAA** [comment]
@gsketefian, that makes sense!  I had always wondered why we couldn't use stretch_fac=1, and I guess this is it.  Can you explain how it is related to the above code blocks that @GeorgeGayno-NOAA shows?

**Comment by GeorgeGayno-NOAA** [comment]
@gsketefian Is my fix acceptable?  Should I start a PR?

**Comment by edwardhartnett** [comment]
Can we have a test for this please?

**Comment by GeorgeGayno-NOAA** [comment]
> Can we have a test for this please?

@edwardhartnett  There is a small set of regression tests for the grid generation process (./reg_tests/grid_gen).  The topo filtering is one step in that process.  Currently, the test suite includes a global uniform grid and a GFDL regional grid.  I can add another test for an ESG regional grid.  I can use the same ESG grid definition that resulted in the failure.

**Comment by edwardhartnett** [comment]
Can we automate these tests please?

**Comment by GeorgeGayno-NOAA** [comment]
Using the branch at 8fcbd1b, I created baseline files for the new ESG grid generation regression test (Jet, Hera, Orion, WCOSS-Cray, WCOSS-Dell).
