### ISSUE TITLE
chgres_cube, release/public-v2: Soil type issue at land ice vegetation points

### ISSUE THREAD

**Issue by LarissaReames-NOAA** [NOAA-EMC/UFS_UTILS#246]
Due to inconsistencies in landmask between HRRR and FV3, and how HRRR data handles vegetation and soil type at frozen lakes / land ice points, some points exist in surface output data with soil type of 0 at land ice points. 

The fix for this, while not ideal, is a brute force method of forcing all grid points with land use type of land ice to have soil type 16 in the qc_check subroutine. I have been unsuccessful, despite many many efforts, to implement a fix by modifying the input data just after reading in, or by making changes in the interp subroutine. Will use this brute force fix for now, but will contact ESMF support before implementing a fix in the develop branch.

**Comment by GeorgeGayno-NOAA** [comment]
Do you know why the problem (soil type 0) only happens at land ice points?

**Comment by lharris4** [comment]
Hello. I don't understand how this is a problem with FV3. FV3 is a
dynamical core and has no conception of vegetation type, lakes, or land ice.

**Comment by LarissaReames-NOAA** [comment]
> Do you know why the problem (soil type 0) only happens at land ice points?

It's honestly a complete mystery. I've tracked the total number of problem points on the target grid (by checking places where soil type is 0 over land points) and they are remedied by doing a soil type interpolation along with the other land ice  to land ice interpolation calls, but then they reappear (the exact same number) after the land, non-land ice interpolation. I confirmed that there are no soil type of 0 at any land points on the input grid, so I'm honestly not sure where those points are originating from.

**Comment by LarissaReames-NOAA** [comment]
> Hello. I don't understand how this is a problem with FV3. FV3 is a dynamical core and has no conception of vegetation type, lakes, or land ice.
> […](#)

Larry, this is the UFS_UTILS GitHub, not FV3.

**Comment by lharris4** [comment]
I am referring to this line in the original message.

> Due to inconsistencies in landmask between HRRR and FV3, and how HRRR
data handles vegetation and soil type at frozen lakes / land ice points,
some points exist in surface output data with soil type of 0 at land ice
points.

**Comment by LarissaReames-NOAA** [comment]
> I am referring to this line in the original message.
> Due to inconsistencies in landmask between HRRR and FV3, and how HRRR
> data handles vegetation and soil type at frozen lakes / land ice points, some points exist in surface output data with soil type of 0 at land ice points.
> […](#)

Yeah, I realized that after I read your message again and my original post. My apologies. Please see the edit in my reply comment where I clarified that statement.

**Comment by lharris4** [comment]
Thanks :-)

**Comment by GeorgeGayno-NOAA** [comment]
> > Do you know why the problem (soil type 0) only happens at land ice points?
> 
> It's honestly a complete mystery. I've tracked the total number of problem points on the target grid (by checking places where soil type is 0 over land points) and they are remedied by doing a soil type interpolation along with the other land ice to land ice interpolation calls, but then they reappear (the exact same number) after the land, non-land ice interpolation. I confirmed that there are no soil type of 0 at any land points on the input grid, so I'm honestly not sure where those points are originating from.

Do you want me to take a quick look at your branch?

**Comment by LarissaReames-NOAA** [comment]
> > > Do you know why the problem (soil type 0) only happens at land ice points?
> > 
> > 
> > It's honestly a complete mystery. I've tracked the total number of problem points on the target grid (by checking places where soil type is 0 over land points) and they are remedied by doing a soil type interpolation along with the other land ice to land ice interpolation calls, but then they reappear (the exact same number) after the land, non-land ice interpolation. I confirmed that there are no soil type of 0 at any land points on the input grid, so I'm honestly not sure where those points are originating from.
> 
> Do you want me to take a quick look at your branch?

Sure, you're welcome to do that. More eyes on the problem can never hurt. The branch that I've applied the suggested fix to, but haven't attached to a PR, is feature/chgres_cube_landice_fix.

**Comment by GeorgeGayno-NOAA** [comment]
How do you set "soiltyp_from_climo" (and the other 'from_climo' settings)?

**Comment by LarissaReames-NOAA** [comment]
Fix merged, regression tests updated and passing on all systems. Issue closed.
