### ISSUE TITLE
Update to the official hpc stack v1.1.0

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#248]
Currently, UFS_UTILS is built with a beta version (v1.0.0) of the hpc stack on Jet, Hera, Dell and Orion.  Update to the official version (v1.1.0) to be consistent with other repositories (such as the global workflow).

**Comment by KateFriedman-NOAA** [comment]
Cloned your fork's feature/stack branch in my global-workflow feature/hpc-stack branch on Hera. It build successfully without issue:

/scratch1/NCEPDEV/global/Kate.Friedman/git/feature-hpc-stack/sorc/ufs_utils.fd

Let me know if I can test the updated build for other platforms too. Have not tried running any of it yet.

**Comment by GeorgeGayno-NOAA** [comment]
> Cloned your fork's feature/stack branch in my global-workflow feature/hpc-stack branch on Hera. It built successfully without issue:
> 
> /scratch1/NCEPDEV/global/Kate.Friedman/git/feature-hpc-stack/sorc/ufs_utils.fd
> 
> Let me know if I can test the updated build for other platforms too. Have not tried running any of it yet.

I am running my regression tests on Hera right now.  One of the chgres_cube tests is timing out.  And I am looking into it.  But that test is not relevant to the global workflow.   So go ahead and give it a try.

**Comment by GeorgeGayno-NOAA** [comment]
Tested e977f89 on Hera, Jet, Dell and Orion.  All regression tests were passing.  However, the chgres_cube sigio test was timing out during the conversion of the input atmospheric fields from spectral to grid point space.  A similar problem happened during a previous test of the beta version of the stack under a different issue.  The problem was the splib was not compilied with threads.  

The NCEPLIBS team checked the compilation of v1.1.0 of the stack and confirmed splib was compiled with threads.  So why is the chgres test timing out?   In addition to updating to v1.1.0 of the stack, I also updated to snapshot 36 of the esmf library.  @kgerheiser ran a test that reverted back to esmf snapshot 27.  The chgres_cube sigio test ran to completion.   

I can't explain why esmf snapshot 36 is not working the our sigio library.  I will revert back to esmf 27.

**Comment by GeorgeGayno-NOAA** [comment]
Reverted from ESMF snapshot 36 (448e24a).  Reran the regression tests on Jet, Orion, Hera and Dell.  All tests passed.

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA All my regression tests pass using the new stack.  Have you tried my branch within the global workflow?

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA I have not yet tested, I'm working up to that now that the GSI has a version I can also test. I will now try to start a test this week and will report back. Thanks!

**Comment by edwardhartnett** [comment]
As part of this issue we must modify the CMake build of UFS_UTILS so that it checks the version of each dependency and ensures that a correct version has been found.

**Comment by kgerheiser** [comment]
This can be done by modifying `FindESMF` to query the version and passing a version to `find_package`. There's this `ESMF_Info` executable that may be helpful.

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA I've used your feature/stack branch in workflow tests on Hera and WCOSS successfully. I also successfully ran gdas_init from it on Hera. Thanks!

**Comment by edwardhartnett** [comment]
@kgerheiser we need to solve the problem of ESMF versioning not just in UFS_UTILS, but everywhere else as well. It seems to be one of the packages we are most sensitive to.

Is it generally the case that once we upgrade to a new ESMF version, all previous versions will no longer work?

Or is there a range of versions of ESMF which will work for UFS_UTILS?

**Comment by kgerheiser** [comment]
The same `FindESMF` is used for UFS_UTILS and the weather model so this fix can be extended. 

UFS_UTILS should not be too sensitive to the ESMF version. It's not on the bleeding edge like the weather model, which uses beta snapshots for new ESMF features, but it looks like there was a regression somewhere in the beta snapshots that caused George's timeout.

I've looked into the executable `ESMF_Info` and it reports is `ESMF_VERSION_STRING: 8.1.0 beta snapshot`, which works for actual ESMF releases, but isn't precise enough because the weather model is sensitive to individual beta numbers (i.e. 27, 47).

**Comment by edwardhartnett** [comment]
First let's get UFS_UTILS to check for the most recent ESMF release, if that will work with UFS_UTILS. That will be a good first step.

**Comment by GeorgeGayno-NOAA** [comment]
> The same `FindESMF` is used for UFS_UTILS and the weather model so this fix can be extended.
> 
> UFS_UTILS should not be too sensitive to the ESMF version. It's not on the bleeding edge like the weather model, which uses beta snapshots for new ESMF features, but it looks like there was a regression somewhere in the beta snapshots that caused George's timeout.
> 
> I've looked into the executable `ESMF_Info` and it reports is `ESMF_VERSION_STRING: 8.1.0 beta snapshot`, which works for actual ESMF releases, but isn't precise enough because the weather model is sensitive to individual beta numbers (i.e. 27, 47).

I was not the only group that had a problem with ESMF 8.1.0 snapshot 36. Apparently, that version of the library turned off threading in everyone's program. The forecast model ran slow and my chgres consistency tests ran slow. But normally, UFS_UTILS should not be too sensitive to the ESMF version (it uses ESMF mainly for its regridding capability).

**Comment by GeorgeGayno-NOAA** [comment]
> As part of this issue we must modify the CMake build of UFS_UTILS so that it checks the version of each dependency and ensures that a correct version has been found.

Modify how? Like this?

```
-find_package(gfsio REQUIRED)
+find_package(gfsio 1.4.0 REQUIRED)
```

And what does the version number mean? When I build using hpc/1.1.0, I see this:

` Found sigio: /gpfs/dell2/usrx/local/nceplibs/dev/hpc-stack/libs/hpc-stack/ips-18.0.1.163/sigio/2.3.2/lib/libsigio.a (found version "2.3.0")
`

Why does it find version 2.3.0 when the directory name (and I assume version number) is 2.3.2? For some libraries number matches, but for others it does not.

**Comment by edwardhartnett** [comment]
Yes, that is how. (If I understand CMake correctly, @kgerheiser @aerorahul your opinion would be welcome.)

We must resolve all version issues that we encounter, so let's raise this issue with the hpc-stack people. I have entered an issue.

**Comment by aerorahul** [comment]
This is an issue in sigio release. 
The release tag is 2.3.2 but the VERSION file contains 2.3.0

**Comment by edwardhartnett** [comment]
Whats not clear to me from the CMake documentation is how find_package() behaves when given a single version, as we do here. The implication from the documentation is that version 2.3.0 or later will be accepted, because we don't use the EXACT argument.

**Comment by GeorgeGayno-NOAA** [comment]
I will need help to update the ESMF package find to return the version number.

**Comment by edwardhartnett** [comment]
@kgerheiser and @aerorahul does the FindESMF.cmake file find the version of ESMF so we can check the version number?

If not, how shall we check the version number?

**Comment by aerorahul** [comment]
`FindESMF.cmake` does not return the version, but it is trivial to add that.
The information is contained within the `esmf.mk` file that is used within `FindESMF.cmake`

If you add any updates to `FindESMF.cmake` or other ones that have been copied here from `CMakeModules`, I would expect a PR in CMakeModules so the other projects that rely on a central copy benefit from this update.

**Comment by aerorahul** [comment]
It should also be noted, that `PROJECT_VERSION` in CMake follows versioning; i.e. MAJOR.MINOR.PATCH.TWEAK which are expected to be numbers.  There are open tickets to follow semantic versioning in projects.  CMake itself follows semantic versioning for its releases.

ESMF versions are e.g. 8.1.0-beta_snapshot_21.  So it is not going to be helpful to do:

`find_package(ESMF REQUIRED 8.1.0)`, because we want the minimum to be a particular snapshot, not just the last stable release.

So, I don't know what actual benefit one will get by adding a minimum version for CMake until ESMF actually releases software following semantic versioning.  

My 2c.

**Comment by edwardhartnett** [comment]
OK, yet another way in which ESMF is special, and that causes troubles. 

There's a good reason for every software project to not invent new ways of doing everything! ;-) A misplaced originality, combined with ignorance of standard practice, results in downstream problems for all users.

However annoying this is, it is a problem we have to solve. Not coincidentally, ESMF is one of the most rapidly changing packages, with frequent backward compatibility failures. So checking it's version is even more important than if it were a well behaved package.

**Comment by aerorahul** [comment]
@edwardhartnett 
I am looking at `esmf.mk` and `FindESMF.cmake` and I think we can "trick" `FindESMF.cmake` to report a version in a format `MAJOR.MINOR.PATCH.TWEAK` so that it can be used here and elsewhere in the desired manner.

**Comment by kgerheiser** [comment]
What are your thoughts? The information is all there depending on how we handle it.

```
#----------------------------------------------
ESMF_VERSION_STRING=8.1.0 beta snapshot
ESMF_VERSION_STRING_GIT=ESMF_8_1_0_beta_snapshot_47
#----------------------------------------------

ESMF_VERSION_MAJOR=8
ESMF_VERSION_MINOR=1
ESMF_VERSION_REVISION=0
ESMF_VERSION_PATCHLEVEL=0
ESMF_VERSION_PUBLIC='F'
ESMF_VERSION_BETASNAPSHOT='T'
```

**Comment by kgerheiser** [comment]
Can we store the beta snapshot as the tweak version, maybe with a flag indicating that based on `ESMF_VERSION_BETASNAPSHOT`?

**Comment by edwardhartnett** [comment]
If we ignore beta_snapshot versions and focus on released versions, it's straightforward, right?

Can we also return a CMAKE variable to communicate that this is a beta-release? Then we can give a warning whenever a beta release is used.

We can allow programmers to manage their own dependencies in the beta_snapshot release phase, and only cope with actual releases. (So all these beta_snapshots would count as release 8.1.0.0.)

**Comment by aerorahul** [comment]
In `FindESMF.cmake`, I am thinking of constructing a `PROJECT_VERSION` from `ESMF_VERSION_STRING_GIT`

Something in shell terms:
MAJOR=$(echo $ESMF_VERSION_STRING_GIT | cut -d_ -f2)
MINOR=$(echo $ESMF_VERSION_STRING_GIT | cut -d_ -f3)
PATCH=$(echo $ESMF_VERSION_STRING_GIT | cut -d_ -f4)
TWEAK=$(echo $ESMF_VERSION_STRING_GIT | rev | cut -d_ -f1 | rev)

**Comment by edwardhartnett** [comment]
@aerorahul what does your magic formula yield?

**Comment by aerorahul** [comment]
```
ESMF_VERSION_STRING_GIT=ESMF_8_1_0_beta_snapshot_47
```
will yield 
```
ESMF_VERSION=8.1.0.47
```

**Comment by edwardhartnett** [comment]
Well that's excellent I think. 

The only problem will come when the ESMF team decides they want to do a 8.1.0.1 release. ;-) But we can tell them never to do that and they probably will comply - it's not a very normal thing to do such a release anyway...

@aerorahul can you submit these changes as a PR?

We will need to promulgate the version checking of ESMF to every package that uses it, and help their programmers understand how and when to update the required version. 

I know fv3atm will be something we have to worry about - what other repos use ESMF?

**Comment by aerorahul** [comment]
I am working on a PR and will open one momentarily.
ESMF releases (thankfully) are MAJOR.MINOR.0 (for the most part), I think!  
If they really are going to make a "release" out of a "tweak", then ...

**Comment by aerorahul** [comment]
@edwardhartnett @kgerheiser I opened a PR #452.  Please take a look.

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA UFS_UTILS was updated to use the official stack. Please point to this release:
https://github.com/NOAA-EMC/UFS_UTILS/releases/tag/ufs_utils_1_3_0
