### ISSUE TITLE
Adding creation of orographic data files (Cxxx_oro_data_*) for GSL orographic drag suite to orog_mask_tools.fd

### ISSUE THREAD

**Issue by mdtoy** [NOAA-EMC/UFS_UTILS#253]
The GSL orographic drag suite, available on CCPP, requires it's own set of subgrid-scale orographic statistics fields.  A directory similar to sorc/orog_mask_tools.fd/orog.fd will be made to create these INPUT "oro_data" files.  The new directory will be called "orog_gsl.fd".  A Fortran 90 program creates the netCDF "oro_data" files.

**Comment by GeorgeGayno-NOAA** [comment]
@mdtoy I took a quick look through your branch.  Does your code output the same GWD fields as orog.fd?  Does your code compute them differently?

**Comment by mdtoy** [comment]
George,

My code computes the first 10 of the 14 fields that orog.fd calculates.  Yes, it does calculate them differently.

Examples of the new oro_data files are:

Regional:
/scratch2/BMC/wrfruc/mtoy/FV3GFS/GWD_static_files/C775_oro_data_ss.tile7.halo0.nc
/scratch2/BMC/wrfruc/mtoy/FV3GFS/GWD_static_files/C775_oro_data_ls.tile7.halo0.nc

Global:
/scratch2/BMC/wrfruc/mtoy/FV3GFS/GWD_static_files/C96_oro_data_ss.tile6.nc
/scratch2/BMC/wrfruc/mtoy/FV3GFS/GWD_static_files/C96_oro_data_ls.tile6.nc

Regards,
Mike
