### ISSUE TITLE
GFS v16 support

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#26]
Support GFS v16.

**Comment by GeorgeGayno-NOAA** [comment]
Created the following release branch to Kate's testing: https://github.com/NOAA-EMC/UFS_UTILS/tree/release/v2.0.0

**Comment by GeorgeGayno-NOAA** [comment]
Before I create the tag, remove the chgres_cube run directory.  And maybe the reg_tests directory?

**Comment by GeorgeGayno-NOAA** [comment]
Kate requested a tag that contains the Hera port changes but not Xu Li's NSST changes.  She also found a small glitch in the `fv3gfs_chgres.sh` script:

```
Line 16 should have "-A" instead of "-q" when discussing the account on Hera:
 16 #    "#SBATCH -q $account".  On WCOSS, this is "#BSUB -P $account".
...should be:
   16 #    "#SBATCH -A $account".  On WCOSS, this is "#BSUB -P $account". 
```

I will delete the 'release/v2.0.0' branch.  Then create a 'release/v1.1.0' branch, fix the script error and merge back to 'develop'.  When she is ready for Xu Li's changes, I will create another 'release/v2.0.0' branch.

**Comment by GeorgeGayno-NOAA** [comment]
Fanglin requested a switch to these libraries to support v16:

```
On Dell
module use /usrx/local/nceplibs/dev/NCEPLIBS/modulefiles
module load hdf5_parallel/1.10.6
module load netcdf_parallel/4.7.4
module load esmf/8.0.0_ParallelNetCDF

On Hera
module use /scratch2/NCEPDEV/nwprod/NCEPLIBS/modulefiles
module load hdf5_parallel/1.10.6
module load netcdf_parallel/4.7.4
module load esmf/8.0.0_ParallelNetCDF
```

global_cycle was recompiled with the new libraries (Dell) at f172a06.  A canned case gave bit identical results.

**Comment by GeorgeGayno-NOAA** [comment]
Fanglin's changes will eventually be merged to a new release branch.  Remove the out-of-date release/v2.0.0 branch (6cd4b8c).  Kate verified she is not pointing to it.

**Comment by GeorgeGayno-NOAA** [comment]
Arun's proposed nomenclature for release branches: release/ops-gfsv16

**Comment by GeorgeGayno-NOAA** [comment]
Performed a quick test on Dell using 1225f98.  A canned global_cycle test gave bit-identical results.  Running chgres using ./ush/fv3gfs_chgres.sh also gave bit identical results.   Switching to the parallel versions of netcdf and hdf seems to have no impact.

**Comment by GeorgeGayno-NOAA** [comment]
Ran a canned global_cycle and global_chgres test on Hera using the branch at 14da500.  Both tests gave bit identical results to 'develop'.

**Comment by GeorgeGayno-NOAA** [comment]
Some final tests using feature/PNetcdf at 14da500 before merging.

Branch successfully compiled on Jet, Hera, Dell and Cray.

The ./ush/fv3gfs_chgres.sh script was run on Hera, Dell and Cray.  All runs completed normally and gave correct results.

Merge to 'develop'.

**Comment by GeorgeGayno-NOAA** [comment]
Created "release/ops-gfsv16" branch from 'develop' at e339b26.

Latest from Fanglin: "code handoff will be in September/October time. Let's keep using the branch for now, and create a tag before code handoff".

**Comment by GeorgeGayno-NOAA** [comment]
The 'release/ops-gfsv16 branch must be ported to Orion.  Will work it under this issue.

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA The release branch was updated to compile and work on Orion.  Please try it.  Note: use 'release/ops-gfsv16' under **_my fork_**.  If it works, I will merge to the release branch under the authoritative fork.

Also, this release branch no longer compiles on Jet.  Recall a few months ago the big name change to the directories on that machine.  I will update the branch accordingly.

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA I no longer see build_all.sh for building. How should I build it now? Thanks!

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA I no longer see build_all.sh for building. How should I build it now? Thanks!

The release branch was created before the new CMake build.  So you have to use the old build script - ./sorc/build_all_ufs_utils.sh.

**Comment by KateFriedman-NOAA** [comment]
Got it, thanks!

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA  I updated the branch to compile/run on Jet.  Is the global_workflow officially supported on Jet currently?

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA global-workflow isn't officially supported on Jet yet but having UFS_UTILS supported is a big help towards that goal so thank you!

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA I tested driver_grid.orion.sh (as is) from your fork's release/ops-gfsv16 on Orion. See log and output here:

log: /work/noaa/global/kfriedma/git/port2orion/sorc/ufs_utils.fd/driver_scripts/log.fv3_grid_driver
output: /work/noaa/stmp/kfriedma/C96
temp directory: /work/noaa/stmp/kfriedma/fv3_grid.uniform

I have this branch running in my long-term test on Orion now too. No build issues after updating to the older build steps.

Thanks!

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA I tested driver_grid.orion.sh (as is) from your fork's release/ops-gfsv16 on Orion. See log and output here:
> 
> log: /work/noaa/global/kfriedma/git/port2orion/sorc/ufs_utils.fd/driver_scripts/log.fv3_grid_driver
> output: /work/noaa/stmp/kfriedma/C96
> temp directory: /work/noaa/stmp/kfriedma/fv3_grid.uniform
> 
> I have this branch running in my long-term test on Orion now too. No build issues after updating to the older build steps.
> 
> Thanks!

Looks like it worked correctly.

**Comment by KateFriedman-NOAA** [comment]
Sweet...is there anything else I should test on Orion for this version before it merges into the auth repo release/ops-gfsv16 branch? I don't see gdas_init in this version.

**Comment by GeorgeGayno-NOAA** [comment]
> Sweet...is there anything else I should test on Orion for this version before it merges into the auth repo release/ops-gfsv16 branch? I don't see gdas_init in this version.

The 'gdas_init' scripts were baselined after the release branch was created.  That is why they are missing.  Also, without HPSS access from Orion, I would not know how to create a set anyway.

Other than 'global_cycle', I am not sure what UFS_UTILS programs are used in the global workflow.  The snow and sea ice programs are not used, correct?   Because you store the snow and ice analyses in the dump directories.   I ran my unit tests and everything worked.  But it is always good if you can verify my work.

**Comment by KateFriedman-NOAA** [comment]
Correct, we don't run the snow/sea ice programs and instead use the GDA files. I have run a cycle on Orion with the updated UFS_UTILS and it looks like global_cycle worked without issues in the analysis job. See this log:

/work/noaa/stmp/kfriedma/comrot/testcyc768n/logs/2020040206/gdasanal.log

**Comment by GeorgeGayno-NOAA** [comment]
> Correct, we don't run the snow/sea ice programs and instead use the GDA files. I have run a cycle on Orion with the updated UFS_UTILS and it looks like global_cycle worked without issues in the analysis job. See this log:
> 
> /work/noaa/stmp/kfriedma/comrot/testcyc768n/logs/2020040206/gdasanal.log

Kate, looks like it ran without error.  I see global_cycle is run twice - at the current cycle time and three hours prior.  Is that for IAU?

**Comment by KateFriedman-NOAA** [comment]
> I see global_cycle is run twice - at the current cycle time and three hours prior. Is that for IAU?

I would guess so but I'm not sure. @RussTreadon-NOAA Is global_cycle run twice for IAU? Thanks!

**Comment by RussTreadon-NOAA** [comment]
Script exglobal_analysis_fv3gfs.sh.ecf executes $CYCLESH (global_cycle)
twice when $DOIAU = "YES".   The first execution is to update surface
restarts at the start of the IAU window.   If $DOIAU = "NO", this $CYCLESH
is not run.  The second execution of $CYCLESH is not related to IAU.   The
second execution updates surface restarts at the middle of the analysis
window.   The second execution is necessary because we must create a sfcanl
file on the gaussian grid.   Script exglobal_analcalc_fv3gfs.sh.ecf creates
a gaussian grid sfcanl file when $DOGAUSFCANL = "YES".

**Comment by KateFriedman-NOAA** [comment]
Good to know, thanks @RussTreadon-NOAA !

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA  Should I merge?

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA Yes please, thanks!

**Comment by GeorgeGayno-NOAA** [comment]
Latest from @KateFriedman-NOAA 

`It was just decided that we will retire the ".ecf" script name extension with GFSv16. This means removing ".ecf" from any ex-script you have in your respective components and updating files/scripts that reference it.`

UFS_UTILS has one script - exemcsfc_global_sfc_prep.sh.ecf - that will need to be changed.

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA is ready for a tag.  Will create it from release/ops-gfsv16.  Will keep the release branch for a few weeks before deleting it.

**Comment by GeorgeGayno-NOAA** [comment]
Created tag: https://github.com/NOAA-EMC/UFS_UTILS/releases/tag/ops-gfsv16.0.0

**Comment by GeorgeGayno-NOAA** [comment]
Delete tag.  Create new one from the latest release branch.  The branch was updated to only compile programs uses by GFS v16.  Also, the global_cycle and global_chgres build were updated to point to the official netcdf library.

**Comment by GeorgeGayno-NOAA** [comment]
Update the link script to point to gfs v16 fixed directories (a45f87e) and recreate the tag.

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA Can I remove the release branch?:  https://github.com/NOAA-EMC/UFS_UTILS/tree/release/ops-gfsv16

It was tagged as: https://github.com/NOAA-EMC/UFS_UTILS/releases/tag/ops-gfsv16.0.0

**Comment by KateFriedman-NOAA** [comment]
Assuming no additional changes need to come into it for v16 then yes, please feel free to delete the branch. Thanks!

**Comment by GeorgeGayno-NOAA** [comment]
> Assuming no additional changes need to come into it for v16 then yes, please feel free to delete the branch. Thanks!

Ok.  Just wanted to make sure you are not pointing to it.  Or provided it to NCO as part of the code delivery.

**Comment by KateFriedman-NOAA** [comment]
Nope! We sent the ops-gfsv16.0.0 tag in the hand-off so you're good. Thanks!

**Comment by GeorgeGayno-NOAA** [comment]
Removing release/ops-gfsv16.0

**Comment by KateFriedman-NOAA** [comment]
THANK YOU! Once I commit incoming updates to global-workflow develop I will let you know you can actually remove it for good, lol! THANKS!

**Comment by GeorgeGayno-NOAA** [comment]
Latest guidance from Fanglin:  I'd suggest to make the following changes to  gfs.v16.0.0/sorc/ufs_utils.fd/sorc/link_fixdirs.sh 
1) comment out the line [[ $RUN_ENVIR = nco ]] && LINK="cp -rp"
2) after line 48, add [[ $RUN_ENVIR = nco ]] &&  FIX_DIR=../../../fix
3) Please note fix_sfc_climo is not copied to  gfs.v16.0.0/fix.  Please consider to skip it in link_fixdirs.sh  for NCO installation.

Will open a hotfix branch for this.

**Comment by KateFriedman-NOAA** [comment]
Tested, looks ok but please check (Mars)

[Kate.Friedman@m71a2 sorc]$ pwd
/gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/NCO_test_fix/sorc
[Kate.Friedman@m71a2 sorc]$ ll ufs_utils.fd/fix/
total 0
lrwxrwxrwx 1 Kate.Friedman emcmodel 19 Nov  3 21:33 fix_am -> ../../../fix/fix_am
lrwxrwxrwx 1 Kate.Friedman emcmodel 30 Nov  3 21:33 fix_fv3_gmted2010 -> ../../../fix/fix_fv3_gmted2010
lrwxrwxrwx 1 Kate.Friedman emcmodel 21 Nov  3 21:33 fix_orog -> ../../../fix/fix_orog

Screen output for build_all.sh and "sh link_fv3gfs.sh nco dell":

/gpfs/dell2/emc/modeling/save/Kate.Friedman/git/global-workflow/NCO_test_fix/sorc/setup.log

**Comment by edwardhartnett** [comment]
Can this issue be closed?

**Comment by GeorgeGayno-NOAA** [comment]
I want to keep it open until v16 is officially implemented.

**Comment by KateFriedman-NOAA** [comment]
FYI, word on the street is v16 will implement mid-March (maybe the 17th) but waiting for confirmation and the SCN to go out.

**Comment by GeorgeGayno-NOAA** [comment]
And the tag should be updated to a release.
