### ISSUE TITLE
chgres_cube,inland,and sfc_climo_gen  are not bitwise identical between two builds

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/UFS_UTILS#262]
Please check on the current build process for chgres_cube,inland,and sfc_climo_gen as they are not bitwise identical on Dell P3 system between two build.

**Comment by edwardhartnett** [comment]
It surprises me that you are checking the bitwise comparison of the binaries. I've never done that. I would expect them to be the same, if you built it the same on the same system, unless some update occurred between your builds...

**Comment by lgannoaa** [comment]
I agree there should be bitwise identical. But it is not. I try to use the original make instead of CMAKE. Same issue found. We need to check on the build and link arguments with the code manager to ensure it is certified for the architecture.
