### ISSUE TITLE
write unit tests for chgres_cube.fd/search_util.f90

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#279]
OK, now it's time to move on to some more challenging testing. ;-)

We have this function in chgres_cube.fd/search_util.f90:

```
!> @brief Replace undefined surface values.
!!
!! Replace undefined values on the model grid with a valid value at
!! a nearby neighbor.  Undefined values are typically associated
!! with isolated islands where there is no source data.
!!
!! Routine searches a neighborhood with a radius of 100 grid points.
!! If no valid value is found, a default value is used.
!!
!! @note This routine works for one tile of a cubed sphere grid.  It
!! does not consider valid values at adjacent faces.  That is a 
!! future upgrade.
 subroutine search (field, mask, idim, jdim, tile, field_num, latitude, terrain_land, soilt_climo)

```

As a first step, can we add param tags in the doxygen to describe each of these parameters?

As a second step, write a test which constructs some parameters, calls this function, and checks the results. 

Seems like this code must be run with MPI, is that right @GeorgeGayno-NOAA ? If so, we can use the same techniques as the ParallelIO project to run the test with MPI. Basically:

```
# This is some custom CMake code from ParallelIO project.
include (LibMPI)

  add_mpi_test(pio_unit_test
    EXECUTABLE ${CMAKE_CURRENT_BINARY_DIR}/pio_unit_test
    NUMPROCS 4
    TIMEOUT ${DEFAULT_TEST_TIMEOUT})
```

I will see if I can get an empty test running with mpi to demonstrate.

**Comment by GeorgeGayno-NOAA** [comment]
My chgres_cube regression tests already check these routines.  Why can't you get my regression tests to run under github?

**Comment by edwardhartnett** [comment]
Your regression tests won't work on GitHub because they require too much data to operate.

In any case, system tests are not a substitute for unit testing. As we develop unit tests for the code, you will find that it's easier to develop and you will come to rely on the unit tests, and only look at the regression testing as backup.

In fact, if anything fails in regression testing that did not cause a unit test failure, we will treat that as a bug and add a unit test to catch the problem. ;-) But that will be the future.

One thing you should be considering in review is unused code. That is, you may have code in here that you know is never used. Now is the time to remove that code.

**Comment by edwardhartnett** [comment]
@lgannoaa perhaps you can do a documentation PR on this code today. See my recently submitted PR #287 for the kind of changes needed to convert existing documentation to doxygen.

**Comment by edwardhartnett** [comment]
@lgannoaa our general requirement to add unit testing is here: https://github.com/NOAA-EMC/NCEPLIBS/issues/130

Next NCEPLIBS meeting @jbathegit is going to go over the current testing of NCEPLIBS-bufr.

**Comment by edwardhartnett** [comment]
Any progress here? I expected to see a doxygen pull request by now...

**Comment by edwardhartnett** [comment]
Let's break this issue into two parts, documentation and testing. Documentation must come first. I will write a separate issue for that.

**Comment by GeorgeGayno-NOAA** [comment]
This issue is getting stale.  How about I work on this next?
