### ISSUE TITLE
write unit tests for chgres_cube/program_setup.f90 read_varmap() subroutine

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#280]
First step is to put doxygen comments on every subroutine. Also the public variables are documented in a list at the top of the file. Instead, each public variable should be individually documented with doxygen, this will allow the generated output to list these vars and their meanings, without us maintaining a list.

Second step is to test the subroutines in this file. There is a namelist reading function, so we can create some test namelists, read them in, and make sure the values are correct.

There's a lot of places where the code prints some output, but nothing else. For example:

```
!-------------------------------------------------------------------------
! Ensure program recognizes the input data type.  
!-------------------------------------------------------------------------

 select case (trim(input_type))
   case ("restart")
     print*,'- INPUT DATA FROM FV3 TILED RESTART FILES.'
   case ("history")
     print*,'- INPUT DATA FROM FV3 TILED HISTORY FILES.'
   case ("gaussian_nemsio")
     print*,'- INPUT DATA FROM FV3 GAUSSIAN NEMSIO FILE.'
   case ("gfs_gaussian_nemsio")
     print*,'- INPUT DATA FROM SPECTRAL GFS GAUSSIAN NEMSIO FILE.'
   case ("gfs_sigio")
     print*,'- INPUT DATA FROM SPECTRAL GFS SIGIO/SFCIO FILE.'
   case ("gaussian_netcdf")
     print*,'- INPUT DATA FROM FV3 GAUSSIAN NETCDF FILE.'
   case ("grib2")
     print*,'- INPUT DATA FROM A GRIB2 FILE'
   case default
     call error_handler("UNRECOGNIZED INPUT DATA TYPE.", 1)
 end select
```

So I guess to test this we have to look at stdout and see what's there? I'm not sure... suggestions welcome.

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA can you cut and paste varmap file to this issue?

**Comment by GeorgeGayno-NOAA** [comment]
dzdt               dzdt         set_to_fill   0        D
sphum           sphum     set_to_fill   1E-7     T
liq_wat           liq_wat     set_to_fill   0        T
o3mr              o3mr       set_to_fill   1E-7     T
ice_wat           ice_wat    set_to_fill   0        T
rainwat           rainwat    set_to_fill   0        T
snowwat         snowwat   set_to_fill   0        T
graupel           graupel   set_to_fill   0        T
vtype              vtype      skip            0        S
sotype            stype      skip            0        S
vfrac               vfrac       skip            0        S
fricv                uustar    set_to_fill    0        S
sfcr                 zorl       set_to_fill    0.01     S
tprcp              tprcp     set_to_fill    0.00     S
ffmm              ffmm      set_to_fill   0.00     S
f10m              f10m      set_to_fill   0.00     S
soilw               smc       stop           0        S
soill                slc         set_to_fill    0.0      S
soilt                stc         stop           0        S
cnwat             cnwat     set_to_fill   0.0      S
hice                icetk       set_to_fill   1.5      S
weasd            weasd     set_to_fill   0.0      S
snod              snod       set_to_fill   0.0      S

**Comment by GeorgeGayno-NOAA** [comment]
The varmap tables are under ./parm/varmap_tables.  I cut and pasted the one for GFSphys.

**Comment by GeorgeGayno-NOAA** [comment]
I don't know if the columns need to be lined up.  I did not add this functionality.

**Comment by edwardhartnett** [comment]
Thanks, that's great. I'll give it a try.

**Comment by GeorgeGayno-NOAA** [comment]
This issue is getting stale. Should I work on it?

**Comment by edwardhartnett** [comment]
No I'll take another swing at it - I was trying to get some answers to #374 and now I have some.

What would be good would be to select another part of chgres_cube, add an issue, and start writing tests for that.
