### ISSUE TITLE
improve doxygen documentation for chgres_cube.fd/surface.F90

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#281]
The first part of the testing effort is always going to be to improve the doxygen documentation. For example, in chgres_cube.fd/surface.F90 we have:

```
!---------------------------------------------------------------------------------------------
! Horizontally interpolate surface fields using esmf routines.
!---------------------------------------------------------------------------------------------

 subroutine interp(localpet)

```

Firstly, the existing documentation needs to be converted to doxygen. Then we need a param tag, an author tag (if known). More explanation would be welcome.

Consider how @lgannoaa will approach this task and put some documentation in for each subroutine or function, so that a tester will have some idea of how to start writing a test for that subroutine or function. Of course, you cannot put everything you know into documentation. But more than one sentence would be welcome.

If we can ask you @GeorgeGayno-NOAA to target each code file in chgres_cube.fd in turn, and do a doxygen upgrade, that would speed testing quite a bit, and also bring up the quality of the documentation.

**Comment by edwardhartnett** [comment]
Any progress here?

**Comment by lgannoaa** [comment]
Working on other task these couple of days. Will resume this work when time permit.

**Comment by edwardhartnett** [comment]
I was actually asking @GeorgeGayno-NOAA as this task is assigned to him. ;-)

**Comment by lgannoaa** [comment]
Thank you for clarify

**Comment by GeorgeGayno-NOAA** [comment]
Looks like most of this routine has been doxygenated.  Just a couple of small routines need to be updated.  Will work on this now.
