### ISSUE TITLE
complete doxygen documentation of sorc/sfc_climo_gen.fd/interp.F90

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#309]
Part of #191 

This file needs its doxygen documentation to be completed.

Work with @GeorgeGayno-NOAA to complete this.

**Comment by lgannoaa** [comment]
It is now included within https://github.com/NOAA-EMC/UFS_UTILS/pull/302.

Please take a look and let me know.

**Comment by edwardhartnett** [comment]
For future issues, do a separate PR, instead of combining with an already open PR.

Also please use a more descriptive title for the PR, including the name of the file you are documenting.

**Comment by lgannoaa** [comment]
Request noted. If solution is accepted, please help to close this issue. Thanks
