### ISSUE TITLE
complete doygen documentation of sorc/sfc_climo_gen.fd/utils.f90

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#310]
Part of #191

This file needs its doxygen documentation to be completed.

Work with @GeorgeGayno-NOAA to complete this.

**Comment by lgannoaa** [comment]
Pull request is in for [this issue](https://github.com/NOAA-EMC/UFS_UTILS/pull/324). Waiting for approve.

**Comment by edwardhartnett** [comment]
Can you please assign the issue to yourself?

As noted, I am not allowed to assign you work. ;-) And every issue that you resolve should be assigned to you.

**Comment by lgannoaa** [comment]
I do not see an option on this page to assign this issue 310 to myself...

**Comment by edwardhartnett** [comment]
Upper-right, under "Assignees", there is a button "assign yourself"

**Comment by edwardhartnett** [comment]
@lgannoaa can you assign this to yourself? If the work is complete, we can then close this issue.
