### ISSUE TITLE
Add location of readthedocs documentation to the README

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#320]
@GeorgeGayno-NOAA I believe there is some official readthedocs documentation for UFS_UTILS. Can you put a link to it in this issue? Then I will add that link to the README, and it will help us getting this code documented and tested.

**Comment by GeorgeGayno-NOAA** [comment]
The readthedocs documentation is under ./docs/source  It only includes information about chgres_cube currently.

**Comment by edwardhartnett** [comment]
Is the readthedocs documentation hosted on-line anywhere?

**Comment by GeorgeGayno-NOAA** [comment]
> Is the readthedocs documentation hosted on-line anywhere?

https://noaa-emcufs-utils.readthedocs.io/en/latest/
https://readthedocs.org/projects/noaa-emcufs-utils/
