### ISSUE TITLE
Document the fix directory (and other directories) in the README

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#321]
What is the fix directory all about?

**Comment by GeorgeGayno-NOAA** [comment]
It is where we set links to directories containing large, static data files used by UFS_UTILS programs.

**Comment by edwardhartnett** [comment]
The README should contain this info for future reference.

**Comment by edwardhartnett** [comment]
I have added some text describing different directories in the project to the README. @GeorgeGayno-NOAA please fill in the ???.
