### ISSUE TITLE
doxygen documentation for sorc/grid_tools.fd

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#343]
Part of #191

**Comment by lgannoaa** [comment]
In review of this issue, it included 4 directories and 12 f90 source codes. I think it will be helpful if @GeorgeGayno-NOAA can take a view and input high level description document before we can finish this issue with detail doxygen update.

**Comment by edwardhartnett** [comment]
We need these files doxygenated. Please add doxygen formatting as best you can. Do one or two files and put up a PR, and we will start filling in the missing information.

**Comment by edwardhartnett** [comment]
I am working with Jim Purser to get the rest of these question marks filled in...

**Comment by edwardhartnett** [comment]
OK, in sorc/grid_tools.fd/regional_esg_grid.fd there is one file with three remaining undocumented fields, I have sent that to Jim Purser to get the answers.

The other undocumented file is filter_topo.f90. This was written by two GFDL programmers. I have sent the file to Rusty Benson and asked them to fill in the missing fields.

**Comment by edwardhartnett** [comment]
@bensonr any progress getting the programmers to document their work in filter_topo.f90?

**Comment by bensonr** [comment]
@edwardhartnett  - there is a section dedicated to the topography filtering algorithm in the soon to be released comprehensive, scientific description of FV3 "the dycore" documentation.  As this offline filtering algorithm comes directly from FV3 "the dycore", that will be the authoritative source.  Once it is released, proper referencing will be available.

**Comment by edwardhartnett** [comment]
@bensonr scientific documentation of the algorithm is pretty different from code documentation.

Can we have the programmers document the code as well?
