### ISSUE TITLE
doxygen documentation for sorc/orog_mask_tools.fd

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#344]
Part of #191

**Comment by edwardhartnett** [comment]
Note that @GeorgeVandenberghe-NOAA is doing some doxygen work in this directory.

**Comment by GeorgeVandenberghe-NOAA** [comment]
Proceeded while waiting for review of #191 changes.   Most of these routines are undocumented with no information on how
they work or what they do (no fortran docblocks, just code with some documentation).  Some do have docblocks.  It is not
clear who the author is.
