### ISSUE TITLE
Document soil param calculations in chgres_cube.fd/program_setup.f90

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#350]
Is there a paper or other reference for the soil parameter calculations in chgres_cube.fd/program_setup.f90?

**Comment by GeorgeGayno-NOAA** [comment]
The calculations are those used by the Noah LSM. The original reference for The Noah LSM is: https://doi.org/10.1029/2002JD003296  There may be newer or better references.  I would ask our land team.

@barlage what is the official citation(s) for the Noah LSM?

**Comment by edwardhartnett** [comment]
Excellent thanks! I will add this link to the documentation.

**Comment by barlage** [comment]
@edwardhartnett @GeorgeGayno-NOAA @HelinWei-NOAA  if you're looking for some details about the soil parameters/properties, you may also want to reference this (more details):

https://journals.ametsoc.org/view/journals/mwre/129/4/1520-0493_2001_129_0569_caalsh_2.0.co_2.xml

The original source for soil properties is here:

Cosby, B. J., G. M. Hornberger, R. B. Clapp, and T. R. Ginn, 1984:A statistical exploration of the relationships of soil moisture characteristics to the physical properties of soils. Water Resour. Res.,20, 682–690.

**Comment by edwardhartnett** [comment]
Thanks! I have added these to the documentation...
