### ISSUE TITLE
Improve error message in global_cycle

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#368]
NCO wants an improved error message in global cycle.  Here is their comment:

```
We tested the gfs_atmos_analysis job with missing gfs.t$CCz.snogrb_t1534.3072.1536 data, and got 
following message: "error in opening file
 /gpfs/dell1/nco/ops/com/gfs/test/gfs.20211219/12/atmos/gfs.t12z.snogrb_t1534.30
"

Please update the source code in sorc/global_cycle.fd/ to add "FATAL ERROR" in the front of the message 
for those critical problems that would cause job failure.
```

The update must be done before the next implementation (v17) of GFS.

This request was opened under Bugzilla:  http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1197

**Comment by GeorgeGayno-NOAA** [comment]
The branch at ea153d9 was compiled on Orion, Hera, Jet, WCOSS-Cray and WCOSS-Dell. And the `global_cycle` regression test passed as expected.

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA Is this fix slated to go into ops with GFSv17 or earlier in GFSv16? I'm reviewing the open bugzillas for the GFS and GEFS.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA Is this fix slated to go into ops with GFSv17 or earlier in GFSv16? I'm reviewing the open bugzillas for the GFS and GEFS.

This was merged after the creation of the GFSv16 tags. So, the tag I just gave you - https://github.com/ufs-community/UFS_UTILS/releases/tag/ops-gfsv16.3.20 - does **_not_** have these updates. Looking through the `global_cycle` source code, I see many (but not all) of the error statements start with FATAL ERROR. **_Do I need to update the v16 tag?_**

For v17, I will likely need to cut a new tag from develop, which includes these updates.

**Comment by KateFriedman-NOAA** [comment]
I think it's fine to wait to resolve it in v17. NCO is installing the v16.3.20 package this morning to test with obsproc/v1.3 so we can't include anything else with that tag now. If there is another UFS_UTILS tag that gets cut for v16 we can make the changes but otherwise we'll make them in v17. Thanks for confirming where the bugzilla fixes are.
