### ISSUE TITLE
Update chgres_cube for GFS v16 netcdf history files

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#38]
GFS v16 will output gaussian history files in netcdf format instead of the current nemsio format.   Update chgres_cube accordingly.

**Comment by GeorgeGayno-NOAA** [comment]
According to Bing Fu and Hong, the GEFS will need this capability.

**Comment by bingfu-NOAA** [comment]
Thanks George for developing this utility. This utility will help GEFS to still get 64-level 6-tile analysis files as initial fields for GEFS v12 after GFSv16 implementation.

**Comment by GeorgeGayno-NOAA** [comment]
The update chgres_cube has been successfully tested by Jun Wang, Bing Fu and Hong Guan.

```Bing Fu: "I have finished running a full cycle GEFS for testing the new chgres, it works for us."```

Will merge to 'develop'.

**Comment by GeorgeGayno-NOAA** [comment]
Merged to 'develop' at ad909ed.  Closing ticket.
