### ISSUE TITLE
NCEPLIBS not cached in Github Action

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/UFS_UTILS#381]
There's a cache step, but it's never checked before building here:

https://github.com/NOAA-EMC/UFS_UTILS/blob/75349eaae645818e3349e763b08aa5fdfc2b1afc/.github/workflows/esmf-8.0.1_jasper-2.0.22_nceplibs-1.3.0.yml#L105

**Comment by edwardhartnett** [comment]
Good catch!

**Comment by kgerheiser** [comment]
Fixed with #380
