### ISSUE TITLE
generate a text report on what hpc-stack installs, and where it comes from

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#389]
We need a list of what hpc-stack installs, and where it is getting each package from.

Instead of generating a one-time list, I think hpc-stack should be able to output a simple list of what it would install. Possible?

**Comment by aerorahul** [comment]
First part is easy and can be done before it starts building anything.
I think that is a good idea to do anyways.
We just need to add a function in `stack_helpers.sh` to print out what is `ON/OFF`.
The second part is not easily done.
The sources are wired in the build script.  It won't get to that point until its turn arrives during the build process.

**Comment by aerorahul** [comment]
@edwardhartnett you probably intended to make this an issue in hpc-stack and not in ufs_utils.

**Comment by kgerheiser** [comment]
Wrong repository? This is UFS_UTILS.

**Comment by edwardhartnett** [comment]
Duh. There's a way to move issues, let me see if I can find it...
