### ISSUE TITLE
Code files in  emcsfc_snow2mdl.fd should have .F90 extension, not .f extension

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#394]
In sorc/emcsfc_snow2mdl.fd we have:
```
  -rwxrwxr-x  1 ed ed  8732 Mar  8 04:17 driver.f
  -rw-rw-r--  1 ed ed 24767 Mar  8 04:57 grib_utils.f
  -rwxrwxr-x  1 ed ed 19525 Mar  8 04:57 model_grid.f
  -rwxrwxr-x  1 ed ed  6247 Mar  8 04:40 program_setup.f
  -rwxrwxr-x  1 ed ed 42026 Mar  8 05:01 snow2mdl.f
  -rwxrwxr-x  1 ed ed 43207 Mar  8 04:55 snowdat.f
```

These are Fortran 90 files, but have a .f extension. The convention is that .f (or .F) is used for F77 code (i.e. fixed format Fortran) and .F90 is used for free-format fortran. This convention is observed by doxygen and make, as well as many code editing tools (like emacs). So it would be good if we followed this convention.

**Comment by GeorgeGayno-NOAA** [comment]
I can knock this out today.
