### ISSUE TITLE
Inconsistency in branch names

### ISSUE THREAD

**Issue by climbfuji** [NOAA-EMC/UFS_UTILS#42]
UFS_UTILS is the only submodule of the NCEPLIBS umbrella build that uses a branch name `release/ufs_release_1.0` for the UFS public release branch. All others just have `ufs_release_1.0`. Should this be changed, i.e, should a branch `ufs_release_1.0` be created from `release/ufs_release_1.0` and the latter then deleted? Note that in this case the `.gitmodules` file in the NCEPLIBS umbrella repository should be updated (because it contains the branch name).

See also https://github.com/NOAA-EMC/NCEPLIBS/pull/12.

**Comment by GeorgeGayno-NOAA** [comment]
@climbfuji Can this issue be closed?

**Comment by climbfuji** [comment]
Yes, thanks!
