### ISSUE TITLE
do a version 1.3.0 release

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#442]
When a release (or tag) is desired, the following steps need to be followed:

1 - Open an issue "release version XXX" so that everyone knows that a release is imminent.
2 - Write release notest.
3 - Do a versioned release. (Add any other tag name you like, but there release tag should be a version number).
4 - Update gh-pages branch with documentation.

So we have just done a release. We need better release notes, and we need to tag and name the release with a version number. (1.3.0).

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA what is going on with these new tags? There seem to be several tags added all at similar points in the code.

What is going on with this?

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA what do you say about doing a release?

There have been many changes and the documentation has had a lot of updates since the last release. This would also allow us to put a release close to the two tags that were recently added.

**Comment by GeorgeGayno-NOAA** [comment]
Who is this release for?

**Comment by edwardhartnett** [comment]
This release is for everyone.

Instead of thinking of releases as being for a specific purpose, think of dong releases every 3 months. When someone wants a tag, instead of creating a new one, we will just give them the tag for the latest release.

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA what are the major science issues that were resolve since the 1.2.0 release? They should be listed in the release notes...

I have started draft release notes, you can just add your items there. Make sure you hit "save draft" instead of "publish release".

**Comment by edwardhartnett** [comment]
OK, we are going to merge one more PR from @GeorgeGayno-NOAA , then let everything run overnight testing, then we will release version 1.3.0 tomorrow...

**Comment by edwardhartnett** [comment]
We have done the release. Onward to 1.4.0!
