### ISSUE TITLE
check versions of all dependent packages

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#443]
When we look for dependent packages in the CMake build we must know what versions of each package are acceptable. That is, what version of ESMF is required to run the code.

**Comment by edwardhartnett** [comment]
Can we get this in soon, so we can do this checking in the 1.3.0 release?

**Comment by kgerheiser** [comment]
How to tell what version of ESMF (8.0, 7.0, farther?) and NetCDF (4.0.0?) are required?

**Comment by edwardhartnett** [comment]
As you suggest, the real question is: what do we do if UFS_UTILS needs netcdf-c-4.3.x or better, and fv3atm requires netcdf-c-4.7.4?

I think, as a starting point, let's require what hpc-stack is using right now. So let's require netcdf-c-4.7.4, and every other version currently used in hpc-stack.

These might be too strict (i.e. earlier versions of many packages may work fine with UFS_UTILS) but that's OK.

Over time, it may be that fv3atm requires different versions of netcdf-c than UFS_UTILS, but let's think of everyone synced up, as a starting point.
