### ISSUE TITLE
some packages required in CMakeLists.txt which are no longer needed?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#449]
I think the list of required packages in CMakeLists.txt contains some packages that are no longer needed:

```
find_package(gfsio REQUIRED)
find_package(sfcio REQUIRED)
find_package(w3nco REQUIRED)
find_package(bacio REQUIRED)
find_package(nemsio REQUIRED)
find_package(sigio REQUIRED)
find_package(sp REQUIRED)
find_package(ip REQUIRED)
find_package(w3emc REQUIRED)
find_package(g2 REQUIRED)
find_package(wgrib2 REQUIRED)
```

w3emc does not seem to be used. Haven't we eliminated use of some of the others as well?

**Comment by GeorgeGayno-NOAA** [comment]
Good catch. gfsio is not used either.

Recall we eliminated a few libraries when global_chgres was removed from UFS_UTILS:
https://github.com/NOAA-EMC/UFS_UTILS/pull/299#pullrequestreview-596742674

**Comment by GeorgeGayno-NOAA** [comment]
Can I fold this in with #248 in one pull request?
