### ISSUE TITLE
questions about email from cron job running consistency checks

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#458]
I see these emails and they are great:

![image](https://user-images.githubusercontent.com/38856240/116089863-7f6f3d80-a660-11eb-99f4-b1cffc51606d.png)

Some questions:

1. I note the "From" field is not George's real email. Should it be? Are we revealing any information that we should not be here?
2. What does this mean: Started on  v71r1

**Comment by kgerheiser** [comment]
It is from the machine's email when using the `mail` command. I don't think there's anything particularly interesting about this information.

`v71r1` is the result of `hostname -s`, which is just the particular head node that the job was started on. In this case `v` for `Venus` (WCOSS Cray).

**Comment by edwardhartnett** [comment]
I believe we can fix the
