### ISSUE TITLE
Canopy moisture content output from GEFSv12 grib2 input has erroneously high canopy water content

### ISSUE THREAD

**Issue by LarissaReames-NOAA** [NOAA-EMC/UFS_UTILS#481]
This issue was noted and fixed by @christinaholtNOAA (and others) in their branch (see [commit 11f31c53](https://github.com/NOAA-GSL/UFS_UTILS/commit/11f31c533001799271d13e6863c6927218810ffe) in the NCAR fork) by correcting the data in qc_check, but I will instead adjust the input data just after read. This change will be tested with a simple unit test to check that values greater than the max allowed value (0.5) are properly replaced by 0.

**Comment by GeorgeGayno-NOAA** [comment]
@LarissaReames-NOAA What exactly is the problem with the grib2 data? Does the land mask not match the data? I suggest we make a list (and some graphics) of all the problems with the grib2 data so it can be fixed.
