### ISSUE TITLE
Set up CI testing with free intel fortran compiler

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#494]
I'm reading on the interwebs that intel has a free version of its fortran compiler for non-commercial use on Linux. Well, that's us!

So it seems like we could use this to get Intel testing as well as GNU. Perhaps we can do this on GitHub actions, perhaps on private Jenkins servers.

**Comment by kgerheiser** [comment]
Yes, I've had this on my mind recently. I use it on my personal machine.

You can download it via APT (or other package manager) https://software.intel.com/content/www/us/en/develop/articles/installing-intel-oneapi-toolkits-via-apt.html

**Comment by edwardhartnett** [comment]
Want to try a GitHub action with this?

I would be very, very nice and comforting to be running our CI testing on Intel as well as GNU. There's rarely a difference, but we want to know every time there is.

**Comment by kgerheiser** [comment]
Yes, I think I can do that. I've been trying it out on an Ubuntu VM.
