### ISSUE TITLE
write test for chgres_cube atmosphere.F90, subroutine read_vcoord_info()

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#499]
In atmosphere.F90 we have:

```
!! namelist variable vcoord_file_target_grid).
!!
!! @author George Gayno
 subroutine read_vcoord_info
```

@GeorgeGayno-NOAA can you give me some one or more samples of a vcoord_info file? Then I will write a test for this subroutine.

**Comment by GeorgeGayno-NOAA** [comment]
Look under ./fix/fix_am.  Use any of the global_hyblev.l??.txt files.

**Comment by edwardhartnett** [comment]
OK, looks like the fix directory causes links to be made to various directories on our machines.

This is not good. How are outside users supposed to see these files?

What is the size of these files? Can we package them up in a tarball on the FTP site? Then users can download them...

**Comment by GeorgeGayno-NOAA** [comment]
This issue is getting stale. I can work on it today.
