### ISSUE TITLE
use ctest options --rerun-failed --output-on-failure in CI runs

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#501]
@kgerheiser this is super helpful.

Using ctest with these options shows the output of a failing test in the CI. Otherwise, all we know is that a test failed, and there's no way to see the output.

We should be using these options everywhere...

**Comment by kgerheiser** [comment]
Cool, I didn't know about those options.

**Comment by kgerheiser** [comment]
While I'm working with the NetCDF and Intel builds I'll add this as well.
