### ISSUE TITLE
Add fortran subprogram gblevents.f from w3emc to UFS_UTILS to solve circular dependency problem in NCEPLIBS?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#523]
@GeorgeGayno-NOAA we have a fortran subprogram in NCEPLIBS-w3emc which should probably be in UFS_UTILS.

According to @kgerheiser:

> It's that gblevents.f program which uses nemsio and sigio.
> 
> https://github.com/NOAA-EMC/NCEPLIBS-w3emc/blob/develop/src/gblevents.f
> 
> It seems to me that it should be moved out of w3emc. Into it's own repo? UFS_UTILS? I think it was put there just because that repo is the dumping ground for miscellaneous things. Then, w3emc would have no dependencies.

**Comment by kgerheiser** [comment]
It's not a program though. Everything else here is an executable.

**Comment by edwardhartnett** [comment]
I think the fact that it's a library is a problem.

But perhaps it should be in NCEPLIBS-bufr? @jbathegit and @jack-woollen do you guys know about this program?

**Comment by kgerheiser** [comment]
I say we track this in the w3emc repo

https://github.com/NOAA-EMC/NCEPLIBS-w3emc/issues/71

**Comment by edwardhartnett** [comment]
If added to UFS_UTILS it will introduce a dependency on NCEPLIBS-bufr, which is new. All other dependencies are already in use by other parts of UFS_UTILS. So that does look like a good fit...

**Comment by edwardhartnett** [comment]
What I wonder is - who calls this function?

**Comment by kgerheiser** [comment]
That, I don't know. I know @BoiVuong-NOAA worked on it.

**Comment by kgerheiser** [comment]
I also don't think it would be appropriate here because we don't install UFS_UTILS. Depending on what applications use gblevents.f it wouldn't be available pre-installed.

**Comment by edwardhartnett** [comment]
Well I really don't want to create a new repo for one subprogram!

**Comment by jbathegit** [comment]
> I think the fact that it's a library is not a problem.
> 
> But perhaps it should be in NCEPLIBS-bufr? @jbathegit and @jack-woollen do you guys know about this program?

For my part, I don't have any knowledge of or familiarity with this program.  But if the main docblock is correct, it looks like it also has dependencies on NCEPLIBS-sigio, NCEPLIBS-sp, and NCEPLIBS-nemsio.

**Comment by edwardhartnett** [comment]
Although there are certainly some valid objections to putting glbevents into UFS_UTILS (including the fact that UFS_UTILS is not built by hpc-stack), it seems to be the best available option.

@Hang-Lei-NOAA will do this in coordination with @GeorgeGayno-NOAA .

**Comment by GeorgeGayno-NOAA** [comment]
@edwardhartnett and @Hang-Lei-NOAA - I see that gblevents.f was removed from w3emc at [v2.9.0](https://github.com/NOAA-EMC/NCEPLIBS-w3emc/releases/tag/v2.9.0). Have you received any complaints about its absence from later releases? I suspect no one uses gblevents.f anymore and I would like to remove it from UFS_UTILS.

**Comment by Hang-Lei-NOAA** [comment]
Hi George, please keep it in UFS_util. Prep team may be still using it. As
we previously informed them, so they know it is under ufs_util. Removing it
should get agreement from obsproprep team.

**Comment by GeorgeGayno-NOAA** [comment]
Just heard back from Iliana Genkova, they keep their own copy in [prepobs](https://github.com/NOAA-EMC/prepobs/blob/OT.prepobs.v1.0.1_20220628/sorc/gblevents.fd/gblevents.f).

I can keep in in UFS_UTILS. I am getting some Doxygen warnings from that routine and was looking for an excuse not to fix them.
