### ISSUE TITLE
PR #388 broke how chgres handles tracers in grib2 files

### ISSUE THREAD

**Issue by LarissaReames-NOAA** [NOAA-EMC/UFS_UTILS#525]
The recent change to the use of a num_tracers and num_tracers_input (instead of just num_tracers) was improperly implemented for grib2 files. This breaks every use of grib2 files that relies on the variable mapping table to provide tracer names, which is how I designed all grib2 file reading to function. I believe I've found some of the places that need to be fixed, so I'm hopeful this can be resolved quickly.

**Comment by GeorgeGayno-NOAA** [comment]
Sorry about that. The GRIB2 consistency check did not catch that. Do we need better/additional tests?

**Comment by edwardhartnett** [comment]
Yes, we need better and additional tests. Make sure that when this is fixed, tests are included to demonstrate and confirm the fix.

So if, next month, this accidentally gets broken again, it is immediately noticed.

For this, consistency checks are not ideal, because they are delayed. Unit tests are needed, so that programmers can immediately know if they have caused a regression such as this.

**Comment by LarissaReames-NOAA** [comment]
While I agree consistency checks aren't ideal, the ones pending for the release branch would have caught this, and they should be included regardless. I'm going to make a PR to the develop branch later today. 

Ideally, program_setup_varmaps would have caught this issue since it checks that the variable num_tracers coming out of read_varmap is correct, but since all instances of num_tracers in input_data were changed to num_tracers_input, it didn't matter that num_tracers was being computed properly in read_varmap. How do we write a unit test that can account for a PR that changes the name of an important variable without also modifying the unit test to go with it?

**Comment by LarissaReames-NOAA** [comment]
PR #519 fixed this problem. We're adding in more consistency tests in PR #530 which will hopefully prevent this issue in the future.
