### ISSUE TITLE
Do a 1.5.0 release

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#534]
We will need to do a release after #523 is resolved.

**Comment by GeorgeGayno-NOAA** [comment]
#523 has been merged. I can do the release if you want.

**Comment by edwardhartnett** [comment]
Yes please.

**Comment by GeorgeGayno-NOAA** [comment]
Here is the 'to do' list:

- Update the VERSION file.
- Use tag name `ufs_utils_1_5_0`.
- Rebuild the documentation and update the `gh-pages` branch.
- Update the bullet list of items in the release notes, with links to the issues closed.
- Update `master` to match `develop`.
- After doing the release, create draft release notes (via cut and paste) for the next release.

**Comment by GeorgeGayno-NOAA** [comment]
Documentation updated at 5c0d655.
