### ISSUE TITLE
Fix filter_topo return code to be non-zero on error

### ISSUE THREAD

**Issue by gsketefian** [NOAA-EMC/UFS_UTILS#547]
In the filter_topo code, when a non-existent namelist variable is read in, the code fails (as it should), but apparently the return value is still 0, indicating success.  This was noticed in the discussion in PR#[546](https://github.com/NOAA-EMC/regional_workflow/issues/546) into regional_workflow.   For this reason, the following line in exregional_make_orog.sh in regional_workflow fails to catch the failure:
```
$APRUN "${exec_fp}" || \
  print_err_msg_exit "\
Call to executable that generates filtered orography file returned with
non-zero exit code."
```
In the log file for the make_orog task, the error message is:
```
Starting filtering of orography...
 Unknown ErrorError reading input.nml
Stopped
0.00user 0.00system 0:00.01elapsed 50%CPU (0avgtext+0avgdata 2744maxresident)k
15192inputs+0outputs (0major+748minor)pagefaults 0swaps
```
But the script continues to execute because the way filter_topo works is that it replaces the input raw orography file with the output filtered orography file (without changing the file name).  So the raw orography data simply gets passed down the line as if it were filtered.

This is another deficiency of the code.  To reduce changes of confusion and undetected errors like this, the input file should be different than the output file.  Users have been running with unfiltered orography for quite a while now (not sure when this bug was first introduced).

@GeorgeGayno-NOAA @JacobCarley-NOAA Who would be the best person to assign this to?

**Comment by JiliDong-NOAA** [comment]
Thanks @gsketefian for bringing this up. I am wondering why the exit code is 0 when filter_topo fails at reading the namelist? Do we also want to modify the code to get a non-zero exit code where it fails?

**Comment by JeffBeck-NOAA** [comment]
@JiliDong-NOAA, yes, there are two deliverables for this PR:  1) Modify the name of the filtered topography file that is generated by filter_topo to be different than the raw file, and 2) Make sure it fails with a non-zero status when a namelist error is encountered.

**Comment by gsketefian** [comment]
@JiliDong-NOAA I do not know why the exit code is zero even if there is an error.  That is the thing that needs to be looked into.  The other thing is the name of the output file.  Maybe the best approach would be to have the user specify (via the namelist) the names of both the input and output files.  But whatever is done, it will likely affect others such as the global model workflow users, so it has to be done in a coordinated way.
