### ISSUE TITLE
issues on chgres_cube handling missing levels for specific humidity or tracers

### ISSUE THREAD

**Issue by JiliDong-NOAA** [NOAA-EMC/UFS_UTILS#555]
When chgres_cube reads in the combined grib2 files (pgrb2+pgr2b) from GFSV16, the isobaric levels of specific humidity (SPFH) are fewer than the zonal wind (UGRD): 41 vs. 57 levels. The current method of handling missing levels for humidity is setting the fill value of 1E-7, which appears to be problematic. For example, in lower troposphere, we may have the valid spfh10g/kg at 900 mb, 9g/kg at 850 mb but 1E-7 g/kg at 875 mb. Setting spfh as NaN on the missing levels is also not a good option either, which seems to cause problems in the later vertical interpolation. Setting spfh as "skip" in varmap appears to throw out all spfh.

@GeorgeGayno-NOAA @LarissaReames-NOAA is there any solution to this issue? Or does chgres_cube need to be modified to handle the missing levels for specific humidity or tracers better in a general approach? Could chgres be modified to read each variables based on each individual var's isobaric levels?

**Comment by LarissaReames-NOAA** [comment]
Presently, chgres_cube assumes that all 3-d variables are on the same vertical grid. All variables are read in, and then a later routine does vertical re-gridding of all variables with that same assumption. It would take a significant amount of re-working to allow for each 3-d variable to exist on its own vertical coordinate. Is there some way these files could be pre-processed to do vertical interpolation of the variables with missing levels on to those levels?

**Comment by JiliDong-NOAA** [comment]
> Presently, chgres_cube assumes that all 3-d variables are on the same vertical grid. All variables are read in, and then a later routine does vertical re-gridding of all variables with that same assumption. It would take a significant amount of re-working to allow for each 3-d variable to exist on its own vertical coordinate. Is there some way these files could be pre-processed to do vertical interpolation of the variables with missing levels on to those levels?

@LarissaReames-NOAA I agree it will require a lot of work to rewrite the code to handle 3d variables on different levels. For an easier solution, I am thinking to add a new method, say "interp", to the varmap to allow chgres_cube to do the vertical interpolation for missing levels. It could be as simple as a linear interpolation. Do you think it is doable? I think we can also do the interpolation before the grib2 enters chgres_cube but I kind of prefer chgres_cube to do the job.

**Comment by LarissaReames-NOAA** [comment]
> > Presently, chgres_cube assumes that all 3-d variables are on the same vertical grid. All variables are read in, and then a later routine does vertical re-gridding of all variables with that same assumption. It would take a significant amount of re-working to allow for each 3-d variable to exist on its own vertical coordinate. Is there some way these files could be pre-processed to do vertical interpolation of the variables with missing levels on to those levels?
> 
> @LarissaReames-NOAA I agree it will require a lot of work to rewrite the code to handle 3d variables on different levels. For an easier solution, I am thinking to add a new method, say "interp", to the varmap to allow chgres_cube to do the vertical interpolation for missing levels. It could be as simple as a linear interpolation. Do you think it is doable? I think we can also do the interpolation before the grib2 enters chgres_cube but I kind of prefer chgres_cube to do the job.

I think it's **possible**, but still more involved than just dropping in an interpolation routine. You'd have to consider the logic of which levels to choose and the order that you do things in very carefully. I also would advise against linear interpolation since the final interpolation to the target grid is pressure-weighted so you'd want to keep with that, especially in the upper levels of the atmosphere where pressure change with height is way off of linear.

**Comment by GeorgeGayno-NOAA** [comment]
@JiliDong-NOAA If your GRIB2 data has that many missing levels, then why use it? There are better options.

**Comment by JiliDong-NOAA** [comment]
> > > Presently, chgres_cube assumes that all 3-d variables are on the same vertical grid. All variables are read in, and then a later routine does vertical re-gridding of all variables with that same assumption. It would take a significant amount of re-working to allow for each 3-d variable to exist on its own vertical coordinate. Is there some way these files could be pre-processed to do vertical interpolation of the variables with missing levels on to those levels?
> > 
> > 
> > @LarissaReames-NOAA I agree it will require a lot of work to rewrite the code to handle 3d variables on different levels. For an easier solution, I am thinking to add a new method, say "interp", to the varmap to allow chgres_cube to do the vertical interpolation for missing levels. It could be as simple as a linear interpolation. Do you think it is doable? I think we can also do the interpolation before the grib2 enters chgres_cube but I kind of prefer chgres_cube to do the job.
> 
> I think it's **possible**, but still more involved than just dropping in an interpolation routine. You'd have to consider the logic of which levels to choose and the order that you do things in very carefully. I also would advise against linear interpolation since the final interpolation to the target grid is pressure-weighted so you'd want to keep with that, especially in the upper levels of the atmosphere where pressure change with height is way off of linear.

Good points on the interpolation. Is there any existing subroutine for vertical interpolation we can borrow? I wonder if EMC_post has any.

**Comment by JiliDong-NOAA** [comment]
> @JiliDong-NOAA If your GRIB2 data has that many missing levels, then why use it? There are better options.

@GeorgeGayno-NOAA The combined GRIB2 still has 41 levels for SPFH, enough for initialization, just fewer than wind/temp etc. Some clarification: 
1. The vertical levels in pgrb2 from GFSV16 are consistent for major prognostic variables. 
2. The inconsistency of vertical levels only happens when pgrb2 and pgrb2 of GFSV16 are combined: extra levels are added for wind/temp etc. but not for spfh. It may sound strange that adding more levels of data creates "missing levels" for other variable which was ok originally. In the combined file, wind/temp etc. have 57 levels and spfh has 41 levels. 
3. For the purpose of faster data transfer and saving disk space, grib2 files are still preferred for LBC in regional applications.   
Currently we stop combining pgrb2 and pgrb2b (only use pgrb2) and it should solve the issue for now. I just hope chgres_cube can handle this scenario (3d variables in different vertical levels) in the long run.

**Comment by LarissaReames-NOAA** [comment]
> > > > Presently, chgres_cube assumes that all 3-d variables are on the same vertical grid. All variables are read in, and then a later routine does vertical re-gridding of all variables with that same assumption. It would take a significant amount of re-working to allow for each 3-d variable to exist on its own vertical coordinate. Is there some way these files could be pre-processed to do vertical interpolation of the variables with missing levels on to those levels?
> > > 
> > > 
> > > @LarissaReames-NOAA I agree it will require a lot of work to rewrite the code to handle 3d variables on different levels. For an easier solution, I am thinking to add a new method, say "interp", to the varmap to allow chgres_cube to do the vertical interpolation for missing levels. It could be as simple as a linear interpolation. Do you think it is doable? I think we can also do the interpolation before the grib2 enters chgres_cube but I kind of prefer chgres_cube to do the job.
> > 
> > 
> > I think it's **possible**, but still more involved than just dropping in an interpolation routine. You'd have to consider the logic of which levels to choose and the order that you do things in very carefully. I also would advise against linear interpolation since the final interpolation to the target grid is pressure-weighted so you'd want to keep with that, especially in the upper levels of the atmosphere where pressure change with height is way off of linear.
> 
> Good points on the interpolation. Is there any existing subroutine for vertical interpolation we can borrow? I wonder if EMC_post has any.

Some code from the present vertical interpolation could certainly be borrowed. The interpolation itself won't be the difficult part, it would be the workflow and logic for reading in the variables properly in preparation for interpolation.

**Comment by edwardhartnett** [comment]
When writing these changes please consider the requirement to provide unit testing for all new and changed code. Writing unit tests as the code is developed is a lot less work than attempting to retrofit tests after code has been written. All new code and changes must be proven to be correct, and that proof must be available as unit tests to continue to ensure that the code is not broken in future evolution of the package.

**Comment by JacobCarley-NOAA** [comment]
A quick, short term suggestion: Could we put a check in the code to confirm the assumption that all 3d variables are on the same levels? We'd have caught this much sooner if the code aborted with a helpful error.

This at least saves all users now while we figure out the longer term approach.

**Comment by LarissaReames-NOAA** [comment]
> A quick, short term suggestion: Could we put a check in the code to confirm the assumption that all 3d variables are on the same levels? We'd have caught this much sooner if the code aborted with a helpful error.
> 
> This at least saves all users now while we figure out the longer term approach.

The file type that they're attempting to use here is an un-tested, not-officially-supported type of grib2 file. The code that fills in missing vertical levels according to the varmap table was designed to work with the public-availably NCEP GFS files that have levels near TOA that don't have tracers, hence the default to fill these levels in with very small (1E-7) values. These types of grib2 files are officially supported, so providing an error in the event that levels are missing would actually break functionality for these files.

**Comment by JacobCarley-NOAA** [comment]
> The file type that they're attempting to use here is an un-tested, not-officially-supported type of grib2 file. The code that fills in missing vertical levels according to the varmap table was designed to work with the publicly-available NCEP GFS files that have levels near TOA that don't have tracers, hence the default to fill these levels in with very small (1E-7) values. These types of grib2 files are officially supported, so providing an error in the event that levels are missing would actually break functionality for these files.
>
>If you'd like the code to quit if not all variables are available on all vertical levels, change the "set_to_fill" option in the varmap_table to "stop"

Thanks @LarissaReames-NOAA for the additional explanation as well as the suggestion!

Perhaps a constraint could be added to the code such that it does not fill SPFH with very small values at levels where such an assumption is no longer reasonable? (e.g., if missing at 850 hPa). That would catch the issue at hand and ideally maintain the current code's capability.

For what it's worth, the grib2 files are ones that we use extensively at EMC and I think GSL uses them as well (we both got bit by this issue). Probably another issue to open to elevate the files to 'official' support status - I'm not sure of the procedure there.

**Comment by LarissaReames-NOAA** [comment]
> Perhaps a constraint could be added to the code such that it does not fill SPFH with very small values at levels where such an assumption is no longer reasonable? (e.g., if missing at 850 hPa). That would catch the issue at hand and ideally maintain the current code's capability.

I think we could implement one specifically for specific humidity at levels say below 200 mb. 

> For what it's worth, the grib2 files are ones that we use extensively at EMC and I think GSL uses them as well (we both got bit by this issue). Probably another issue to open to elevate the files to 'official' support status - I'm not sure of the procedure there.

So one of the main reason these files aren't yet supported is that in their native state, they have duplicate entries with identical data for some variables (I believe winds in particular, again), which makes reading in the data difficult. 

In the past, as the only way to get min/max vegetation fraction included in the grib2 files (since the grib2 tables were lacking), we had duplicate entries in some HRRR files for VEG, but the data was not identical. However, we knew the exact grib2 entry numbers associated with these duplicate entries, so we could choose the correct entry using that knowledge. 

In the case of duplicate entries with identical data and no known grib2 entry numbers, the only way the code could possibly read these in is to just pick one of the duplicate entries and assume that's correct. I don't think that's a good practice, as it leaves the door open for a user with a malformed file to end up with very incorrect output. I believe it was suggested that these duplicate entries be removed in some sort of pre-processing step before providing them as input to chgres_cube, but I don't know whether that was ever agreed to or not. Once that issue is solved, and we can deal with this RH issue, I imagine we could create some system tests so we could say these (modified) pgrb2+pgrb2b files are supported.

**Comment by JiliDong-NOAA** [comment]
> > Perhaps a constraint could be added to the code such that it does not fill SPFH with very small values at levels where such an assumption is no longer reasonable? (e.g., if missing at 850 hPa). That would catch the issue at hand and ideally maintain the current code's capability.
> 
> I think we could implement one specifically for specific humidity at levels say below 200 mb.
> 
> > For what it's worth, the grib2 files are ones that we use extensively at EMC and I think GSL uses them as well (we both got bit by this issue). Probably another issue to open to elevate the files to 'official' support status - I'm not sure of the procedure there.
> 
> So one of the main reason these files aren't yet supported is that in their native state, they have duplicate entries with identical data for some variables (I believe winds in particular, again), which makes reading in the data difficult.
> 
> In the past, as the only way to get min/max vegetation fraction included in the grib2 files (since the grib2 tables were lacking), we had duplicate entries in some HRRR files for VEG, but the data was not identical. However, we knew the exact grib2 entry numbers associated with these duplicate entries, so we could choose the correct entry using that knowledge.
> 
> In the case of duplicate entries with identical data and no known grib2 entry numbers, the only way the code could possibly read these in is to just pick one of the duplicate entries and assume that's correct. I don't think that's a good practice, as it leaves the door open for a user with a malformed file to end up with very incorrect output. I believe it was suggested that these duplicate entries be removed in some sort of pre-processing step before providing them as input to chgres_cube, but I don't know whether that was ever agreed to or not. Once that issue is solved, and we can deal with this RH issue, I imagine we could create some system tests so we could say these (modified) pgrb2+pgrb2b files are supported.

The duplicate records are removed in the combination step in EMC by using the first record when duplicated. 

I am working to implement a new method in chgres_cube for simple linear interpolation with missing levels for tracers. The interpolation could be done in logP space to avoid Larissa's concern on the upper levels. As it will be a new method/option, I don't expect it will break/change any current applications.

**Comment by JamesAbeles-NOAA** [comment]
@GeorgeGayno-NOAA you wrote "If your GRIB2 data has that many missing levels, then why use it? There are better options." As Jacob mentioned there are several different groups using grib2 and I would add that we are running on the cloud so our options for data are limited. What is a better option?

**Comment by JeffBeck-NOAA** [comment]
Hi @JiliDong-NOAA, based on the issue conversion, there was discussion of adding a check that will cause chgres_cube to fail if 1) Interp isn't selected, and 2) levels of a tracer are missing below 200 mb.  We need to figure out how to incorporate that change into this PR, but also making sure it won't fail for older GFS files that just don't contain certain fields.  It needs to differentiate between whether levels are missing (and fail in that instance if "interp" isn't selected), but also allow the code to continue if it's just a field that simply doesn't exist in that external model data.  @LarissaReames-NOAA has a good idea on how to implement this check, so I'll let her chime in.

**Comment by JiliDong-NOAA** [comment]
> Hi @JiliDong-NOAA, based on the issue conversion, there was discussion of adding a check that will cause chgres_cube to fail if 1) Interp isn't selected, and 2) levels of a tracer are missing below 200 mb. We need to figure out how to incorporate that change into this PR, but also making sure it won't fail for older GFS files that just don't contain certain fields. It needs to differentiate between whether levels are missing (and fail in that instance if "interp" isn't selected), but also allow the code to continue if it's just a field that simply doesn't exist in that external model data. @LarissaReames-NOAA has a good idea on how to implement this check, so I'll let her chime in.

sounds good @JeffBeck-NOAA . I am opening access of the branch add_intrp to both you and @LarissaReames-NOAA . Feel free to make any changes. Or let me know any modifications you propose and I am happy to implement them in this PR.
