### ISSUE TITLE
Support documentation for historical releases on gh-pages branch?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#570]
Currently we just have the documentation for the most recent release on the gh-pages branch.

But it has come up that some people may want to point to specific versions of the documentation. So what we can do is, on our gh-pages branch, put a top-level HTML page that lists the versions and links to their documentation, then, subdirectories for each version, with their documentation. 

Then, as part of a new release, instead of completely overwriting the gh-pages branch, the process would be to just add a directory for the new version, and add a link to it at the top level.

**Comment by GeorgeGayno-NOAA** [comment]
I will work this under #610.

**Comment by edwardhartnett** [comment]
OK, awesome. I already did this for one of the repos, I can't remember which.

Basically just create a directory for each release, and have the top-level page point to those subdirectories.

Then build the documentation as usual, but copy it to one of the subdirectories of the gh-pages branch.
