### ISSUE TITLE
Create sample unit test to assist developers

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#573]
Unit tests are now required before any changes can be merged. When developers are told this, their first question is: "How do I create a unit test and run it under Github actions?" Then, I write a basic test for him. If we had a sample, working test baselined under the repo, it would serve as a guide for developers (and save the admins a lot of time).

**Comment by kgerheiser** [comment]
Maybe a `README.md` in the `tests` directory with a brief explanation of what a unit test should do (exercise the code, check results), and a sample (or point to a simple test like `tst_quicksort`)?

**Comment by edwardhartnett** [comment]
I suggest pointing such users at an existing test which most closely matches their proposed test. That will get easier as tests are added.

Adding a section to the README: "How to Add a Unit Test" would be a good idea.

**Comment by GeorgeGayno-NOAA** [comment]
Reopen so @LarissaReames-NOAA can add her sample unit test.

**Comment by GeorgeGayno-NOAA** [comment]
Merged to 'develop' at 7c31411.
