### ISSUE TITLE
Need to change dependency from w3nco to w3emc

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#579]
Need to change dependency from w3nco to w3emc.

The w3nco library has been deprecated, and all functionality moved to the w3emc library.

**Comment by GeorgeGayno-NOAA** [comment]
Which version number of w3emc should be used?

**Comment by edwardhartnett** [comment]
I believe the current release is the one we need...

**Comment by GeorgeGayno-NOAA** [comment]
Done under #801.  Closing.
