### ISSUE TITLE
Port ops-hrefv3.1 to WCOSS2

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#582]
Port to WCOSS2. Then create a formal release.

Work on this was started under #559. But too many tasks under one issue was getting confusing.

**Comment by GeorgeGayno-NOAA** [comment]
Working under this branch - 40b8084

**Comment by GeorgeGayno-NOAA** [comment]
@MatthewPyle-NOAA What machines (other than WCOSS2) must this new release support?

**Comment by MatthewPyle-NOAA** [comment]
This release is purely for WCOSS2.  What is currently in the hrefv3.1-wcoss2 branch in your fork works for me.

**Comment by GeorgeGayno-NOAA** [comment]
@MatthewPyle-NOAA Sorry I forgot about this. I need to create an official release under the authoritative fork. What did you deliver to NCO?

**Comment by MatthewPyle-NOAA** [comment]
Looks like I included the branch from your fork:

branch = hrefv3.1-wcoss2
repo_url = https://github.com/GeorgeGayno-NOAA/UFS_UTILS.git

**Comment by GeorgeGayno-NOAA** [comment]
> Looks like I included the branch from your fork:
> 
> branch = hrefv3.1-wcoss2 repo_url = https://github.com/GeorgeGayno-NOAA/UFS_UTILS.git

We will need to fix that. I hope it is not too late.

**Comment by MatthewPyle-NOAA** [comment]
Let me know when you have it where you want NCO to point at it.  Probably not that critical as they've already built and run the system, so may never again be pulling it from github, but I'm sure they be okay changing where the externals.cfg points.

**Comment by GeorgeGayno-NOAA** [comment]
> Let me know when you have it where you want NCO to point at it. Probably not that critical as they've already built and run the system, so may never again be pulling it from github, but I'm sure they be okay changing where the externals.cfg points.

@MatthewPyle-NOAA Here is your tag: https://github.com/ufs-community/UFS_UTILS/releases/tag/ops-hrefv3.2

**Comment by edwardhartnett** [comment]
A formal, versioned release needs to be created.

Is this release a snapshot of the current develop branch?

Or is it a branch of a previous release, which is not the same as the develop branch?
