### ISSUE TITLE
Documentation on gh-pages not working?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#593]
Documentation on gh-pages not working?

**Comment by GeorgeGayno-NOAA** [comment]
I went thru the repository and changed all references from NOAA-EMC to ufs-community.

**Comment by edwardhartnett** [comment]
You need to change the README, which has a link to the docs on gh-pages...

**Comment by GeorgeGayno-NOAA** [comment]
> You need to change the README, which has a link to the docs on gh-pages...

Got it.  See f0ca668.

**Comment by GeorgeGayno-NOAA** [comment]
Here is the updated doxygen: https://www.emc.ncep.noaa.gov/jcsda/ggayno/doxygen/html/index.html

**Comment by GeorgeGayno-NOAA** [comment]
Here is the update readthedocs: https://georgegayno-noaaufs-utils.readthedocs.io/en/bugfix-move/ufs_utils.html

**Comment by GeorgeGayno-NOAA** [comment]
Updated gh-pages at 0e7b877.

**Comment by GeorgeGayno-NOAA** [comment]
I missed a few references to the old NOAA-EMC organization. Reopening
