### ISSUE TITLE
Update UFS_UTILS for new role accounts

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#600]
Role accounts for the repo managers have been established on Hera, Jet and Orion.
- Move all data associated with the consistency tests from @GeorgeGayno-NOAA personal directory to a directory owned by the role account.
- Update the consistency test scripts to point to the new location of the data.
- Cron the daily running of these tests under the role account.

**Comment by GeorgeGayno-NOAA** [comment]
@LarissaReames-NOAA and @JeffBeck-NOAA - Let's each pick a machine and submit a PR when we get it working.

**Comment by GeorgeGayno-NOAA** [comment]
Created a directory on Hera to host ufs_utils: /scratch1/NCEPDEV/nems/role.ufsutils

Was able to checkout the ufs_utils repo and compile it under the role account.

**Comment by edwardhartnett** [comment]
BTW I still need to be added as an admin to the UFS_UTILS repo. Make sure you add edward.hartnett (not ed.hartnett, which is my private GitHub account.)

**Comment by GeorgeGayno-NOAA** [comment]
I will install on Orion here: /work/noaa/nems/role-nems/ufs_utils

**Comment by GeorgeGayno-NOAA** [comment]
Work on this issue was completed via these PRs: #605, #606, #607, #608.

Closing issue.
