### ISSUE TITLE
Build failures on Cheyenne, and executables not created correctly on Cheyenne (and potentially other platforms) when it does build

### ISSUE THREAD

**Issue by mkavulich** [NOAA-EMC/UFS_UTILS#616]
- See also https://github.com/ufs-community/ufs-srweather-app/issues/201

# Description

Building the develop branch of the app results in a "successful" build of UFS_UTILS and other components. However, the executables produced will not run, due to having incorrectly linked libraries:

```
time /glade/scratch/kavulich/UFS_SRW/testing/test_core_hours/ufs-srweather-app/bin/regional_esg_grid /glade/scratch/kavulich/UFS_SRW/testing/test_core_hours/expt_dirs/develop/GST_release_public_v1/grid/tmp/regional_grid.nml
/glade/scratch/kavulich/UFS_SRW/testing/test_core_hours/ufs-srweather-app/bin/regional_esg_grid: error while loading shared libraries: libnetcdff.so.7: cannot open shared object file: No such file or directory
0.00user 0.00system 0:00.02elapsed 12%CPU (0avgtext+0avgdata 492maxresident)k
```

Using the `ldd` command reveals that the executables have broken links to missing library files:

```
ldd ../bin/bin/regional_esg_grid 
	linux-vdso.so.1 (0x00007ffe06eb1000)
	libnetcdff.so.7 => not found
	libnetcdf.so.19 => not found
	libm.so.6 => /glade/u/apps/ch/os/lib64/libm.so.6 (0x00007f55b9619000)
	libpthread.so.0 => /glade/u/apps/ch/os/lib64/libpthread.so.0 (0x00007f55b93fc000)
	libdl.so.2 => /glade/u/apps/ch/os/lib64/libdl.so.2 (0x00007f55b91f8000)
	libc.so.6 => /glade/u/apps/ch/os/lib64/libc.so.6 (0x00007f55b8e55000)
	libgcc_s.so.1 => /glade/u/apps/ch/os/lib64/libgcc_s.so.1 (0x00007f55b8c3d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f55b9916000)
```

This appears to be due to a default setting in CMake where at the `make install` step, the executable RPATH is reset to only look in system paths. I believe this problem is only showing up on Cheyenne and not other platforms because the LD_LIBRARY_PATH just happens to be set to include all the necessary libraries on other platforms, though I am not 100% sure of this explanation.

A fix is mentioned on [this page](https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling#common-questions) which involves adding the line `set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)` to CMakeLists.txt. I will be working on a PR to implement this fix soon, unless there are other ideas about a best way to fix this issue.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. On Cheyenne, build UFS_UTILS using the instructions in README.md
```
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=.. ..
make -j2
make install
```
2. Attempt to run any executable, observe shared library errors as shown above
3. Use `ldd` to view the broken library links for any executable as shown above

## Additional Context

This occurs on Cheyenne with Intel compilers. Testing with GNU was not possible due to a separate failure to build the weather model.

As a side note, using the build_all.sh script on Cheyenne results in build failure. I notice it is no longer mentioned in the documentation, so should the old build scripts be removed?

**Comment by mkavulich** [comment]
I have gotten to the bottom of this issue and now fully understand what is happening. A combination of Cheyenne environment changes and the specific build rules within hpc-stack are causing this issue; see https://github.com/NOAA-EMC/hpc-stack/issues/376 for more details

Note: I have applied a hard-fix on disk to the Cheyenne intel module, so this issue should no longer occur for Intel. I have not applied a fix for GNU in order to preserve a way to reproduce the error for the hpc-stack issue.

A fix should not be needed in this repository, but I am leaving this issue open for reference. Feel free to close if one of the code managers feels that would be appropriate.

**Comment by GeorgeGayno-NOAA** [comment]
Instead of leaving this issue open, would it be better to make a note in the wiki page (https://github.com/ufs-community/UFS_UTILS/wiki) or the readme file (https://github.com/ufs-community/UFS_UTILS/blob/develop/README.md)
