### ISSUE TITLE
Build fails on Hera (ESMF version no longer available)

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/UFS_UTILS#618]
The build system is now failing on Hera because the ESMF module being used (8_1_0_beta_snapshot_27) is no longer available from the standard hpc-stack installation.

See also https://github.com/NOAA-EMC/global-workflow/issues/561

**Comment by GeorgeGayno-NOAA** [comment]
@WalterKolczynski-NOAA Thanks. There is a PR to fix this #614. We will merge today.

**Comment by GeorgeGayno-NOAA** [comment]
@WalterKolczynski-NOAA As a temporary work-around, you can modify build.hera.intel to point to v8.1.1.

https://github.com/ufs-community/UFS_UTILS/blob/develop/modulefiles/build.hera.intel

**Comment by GeorgeGayno-NOAA** [comment]
Fixed under #613 and #614. Closing this issue.
