### ISSUE TITLE
Have build system download data files if needed (was: How to obtain data files for unit tests?)

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/UFS_UTILS#619]
Trying to run the unit tests and many failed because of missing files. 

Then, I found [files.txt](https://github.com/ufs-community/UFS_UTILS/blob/develop/tests/chgres_cube/data/files.txt) and found I had to wget them from https://github.com/ufs-community/UFS_UTILS/blob/04ad17e27163b93a53ba3bfdbf38fd0ea82d9b1b/.github/workflows/intel.yml#L173

`files.txt` should be documented here https://github.com/ufs-community/UFS_UTILS/tree/develop/tests or built into the build system.

**Comment by GeorgeGayno-NOAA** [comment]
@kgerheiser Is it difficult to make the file downloads a part of the build system?

**Comment by edwardhartnett** [comment]
No it is not difficult and should certainly be done. Just make sure to test for the existence of the file before downloading it. Then every user, when building UFS_UTILS, will have a very slow first test run (as the files are downloaded) but then could run all the tests without re-downloading the data.

Actually I thought that's what we were doing already. ;-) @kgerheiser could you please implement this?

**Comment by kgerheiser** [comment]
Yeah, it's pretty easy to do with CMake. I can take a stab at it later today.

**Comment by GeorgeGayno-NOAA** [comment]
> Yeah, it's pretty easy to do with CMake. I can take a stab at it later today.

@kgerheiser Do you have an example in NCEPLIBS or another repo that I can follow?

**Comment by kgerheiser** [comment]
Bufr downloads files with CMake using `file(DOWNLOAD)`

https://github.com/NOAA-EMC/NCEPLIBS-bufr/blob/3f2e10bdfa3c6ef179e9e0e9ffb03287b3eba31a/test/CMakeLists.txt#L9-L17

**Comment by GeorgeGayno-NOAA** [comment]
I am able to compile the tests on WCOSS, Hera and Orion. And on Hera I am able to run the tests. On Jet, the data download does not work (because it can't connect to our ftp site?). It takes a few minutes before the download failure happens, so to the user the compilation appears to hang. Adjusting the INACTIVITY_TIMEOUT did not seem to help. For now, I added logic to the build_all.sh script to only compile the tests on WCOSS, Hera and Orion.

**Comment by kgerheiser** [comment]
Firewall on Jet does block the ftp site
