### ISSUE TITLE
Move to newer Intel compiler on Hera, Jet and Orion

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#634]
The 2018 and 2019 Intel compilers are no longer supported by Intel. The system admins recommend switching to the 2022.1.2 version. 

There is an updated version of the hpc-stack on Hera, but not on Jet. The NCEPLIBS team (@kgerheiser) is aware of this requirement.

**Comment by GeorgeGayno-NOAA** [comment]
The only version of ESMF v8.2.0 I could find on Hera uses the 2018 version. Doing `module spider esmf_8_2_0` showed:

```
hpc/1.1.0  hpc-gnu/9.2.0  hpc-mpich/3.3.2
hpc/1.1.0  hpc-intel/18.0.5.274  hpc-impi/2018.0.4
hpc/1.2.0  hpc-gnu/9.2.0  hpc-mpich/3.3.2
hpc/1.2.0  hpc-intel/18.0.5.274  hpc-impi/2018.0.4
```

**Comment by kgerheiser** [comment]
Hey @GeorgeGayno-NOAA we're ready to try this. Newer Intel compilers are complete on all of our systems. 2022.1.2 on Hera, Orion, Jet, and 2021.3.0 on Gaea.

**Comment by GeorgeGayno-NOAA** [comment]
The branch at f374d1a was successfully compiled on Hera, Orion, Jet, WCOSS-Cray and WCOSS-Dell. And the regression tests were run on Hera and Jet. All tests passed.

**Comment by GeorgeGayno-NOAA** [comment]
All regression tests passed on Orion using the branch at b57d186.
