### ISSUE TITLE
GitHub workflows can't find netcdf-c library

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#638]
Some of the workflows build the netcdf-c library. For example, 

https://github.com/ufs-community/UFS_UTILS/blob/570ea3966c125ead7e90b4342be2efc22a8b1f41/.github/workflows/intel.yml#L59

That library is no longer available at that web site. As a result, some of the workflows are failing.

Update the workflows to pull this library from github: https://github.com/Unidata/netcdf-c/tags

**Comment by edwardhartnett** [comment]
Unidata reorganized their web site and moved stuff around. Getting netcdf-c from GitHub is the correct answer, as you have done in your PR.
