### ISSUE TITLE
HPC modules to be updated and in sync with those used for ufs-weather-model 

### ISSUE THREAD

**Issue by natalie-perlin** [NOAA-EMC/UFS_UTILS#645]
HPC modules used on supported systems in .UFS_UTILS/modulefiles/ need to be updated with the hpc-stack modules built and used for the  `ufs-weather-model`.

Updates of the module list for cheyenne , for both Intel and GNU compilers, is proposed for the ufs-weather-model in a PR#250 and is under review: [
](https://github.com/ufs-community/ufs-srweather-app/pull/250)
This list in [PR#250](https://github.com/ufs-community/ufs-srweather-app/pull/250) could be the target for UFS_UTILS module updates for cheyenne.

Other systems need to be updated gradually as well.

**Comment by GeorgeGayno-NOAA** [comment]
@natalie-perlin Is this required for the SRW App v2?
