### ISSUE TITLE
Add 'atmos' subfolder to global_cycle_driver.sh

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#652]
Per request of the global workflow group.

See https://github.com/NOAA-EMC/global-workflow/issues/802

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA Is this correct?

```
diff --git a/ush/global_cycle_driver.sh b/ush/global_cycle_driver.sh
index 3ae35094..10273e20 100755
--- a/ush/global_cycle_driver.sh
+++ b/ush/global_cycle_driver.sh
@@ -38,9 +38,9 @@ export DELTSFC=${DELTSFC:-6}
 PDY=$(echo $CDATE | cut -c1-8)
 cyc=$(echo $CDATE | cut -c9-10)

-export FNTSFA=${FNTSFA:-$DMPDIR/$CDATE/$CDUMP/${CDUMP}.t${cyc}z.rtgssthr.grb}
-export FNSNOA=${FNSNOA:-$DMPDIR/$CDATE/$CDUMP/${CDUMP}.t${cyc}z.snogrb_t1534.3072.1536}
-export FNACNA=${FNACNA:-$DMPDIR/$CDATE/$CDUMP/${CDUMP}.t${cyc}z.seaice.5min.blend.grb}
+export FNTSFA=${FNTSFA:-$DMPDIR/${CDUMP}.${PDY}/$cyc/atmos/${CDUMP}.t${cyc}z.rtgssthr.grb}
+export FNSNOA=${FNSNOA:-$DMPDIR/${CDUMP}.${PDY}/$cyc/atmos/${CDUMP}.t${cyc}z.snogrb_t1534.3072.1536}
+export FNACNA=${FNACNA:-$DMPDIR/${CDUMP}.${PDY}/$cyc/atmos/${CDUMP}.t${cyc}z.seaice.5min.blend.grb}
```

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA Looks good! One comment, perhaps use the `$COMPONENT` variable to set "atmos"? Thanks!

```
export COMPONENT=${COMPONENT:-atmos}
export FNTSFA=${FNTSFA:-$DMPDIR/${CDUMP}.${PDY}/$cyc/$COMPONENT/${CDUMP}.t${cyc}z.rtgssthr.grb}
export FNSNOA=${FNSNOA:-$DMPDIR/${CDUMP}.${PDY}/$cyc/$COMPONENT/${CDUMP}.t${cyc}z.snogrb_t1534.3072.1536}
export FNACNA=${FNACNA:-$DMPDIR/${CDUMP}.${PDY}/$cyc/$COMPONENT/${CDUMP}.t${cyc}z.seaice.5min.blend.grb}
```

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA Try my branch at 28500be -

```
git clone --recursive git@github.com:GeorgeGayno-NOAA/UFS_UTILS.git
git checkout feature/dmpdir
```

**Comment by KateFriedman-NOAA** [comment]
> Try my branch at [28500be](https://github.com/ufs-community/UFS_UTILS/commit/28500beec8118f122f6fbaed39836c606839a0f9) -

This is for GFSv17+ right? I double checked and don't see `global_cycle_driver.sh` being invoked by the GFS in ops (GFSv16.2.0). I see `global_cycle.sh` but that script doesn't use `DMPDIR` files. I'm guessing this is an offline script only then? If so, what is the best way to test it?

**Comment by GeorgeGayno-NOAA** [comment]
> > Try my branch at [28500be](https://github.com/ufs-community/UFS_UTILS/commit/28500beec8118f122f6fbaed39836c606839a0f9) -
> 
> This is for GFSv17+ right? I double checked and don't see `global_cycle_driver.sh` being invoked by the GFS in ops (GFSv16.2.0). I see `global_cycle.sh` but that script doesn't use `DMPDIR` files. I'm guessing this is an offline script only then? If so, what is the best way to test it?

If the global_workflow does not use `global_cycle_driver.sh`, then maybe I should remove it from the repository. Are there future plans to use that script in global_workflow?

**Comment by KateFriedman-NOAA** [comment]
> If the global_workflow does not use global_cycle_driver.sh, then maybe I should remove it from the repository. Are there future plans to use that script in global_workflow?

No plans that I am aware of. @aerorahul @RussTreadon-NOAA @yangfanglin Do you happen to know of any reason for George to keep `global_cycle_driver.sh` around? The global-workflow uses `global_cycle.sh` at runtime in the GFS but I see no mention or use of `global_cycle_driver.sh`. Thanks!

**Comment by yangfanglin** [comment]
@GeorgeGayno-NOAA  Shouldn't we keep it so one can run glocal_cycle offline test ?

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA Shouldn't we keep it so one can run glocal_cycle offline test ?

Alright, I can keep it.

**Comment by GeorgeGayno-NOAA** [comment]
Tested on Mars using my branch at 28500be. The test was done with one of the `global_cycle` regression tests. That test uses local copies of the operational snow, ice and SST analysis for that date, and calls `global_cycle.driver.sh`. Modify the regression test script to point to Kate's dump directory, which contains the same snow, ice and SST files as my local directory. The script was updated to pass in DMPDIR to `global_cycle.driver.sh` as follows:

```
index c86792ff..a982be55 100755
--- a/reg_tests/global_cycle/C768.fv3gfs.sh
+++ b/reg_tests/global_cycle/C768.fv3gfs.sh
@@ -22,10 +22,13 @@ export DELTSFC=6

 export CASE=C768

+export CDUMP=gdas
+
 export COMIN=$HOMEreg/input_data
-export FNTSFA=$COMIN/gdas.t00z.rtgssthr.grb
-export FNSNOA=$COMIN/gdas.t00z.snogrb_t1534.3072.1536
-export FNACNA=$COMIN/gdas.t00z.seaice.5min.blend.grb
+#export FNTSFA=$COMIN/gdas.t00z.rtgssthr.grb
+#export FNSNOA=$COMIN/gdas.t00z.snogrb_t1534.3072.1536
+#export FNACNA=$COMIN/gdas.t00z.seaice.5min.blend.grb
+export DMPDIR=/gpfs/dell3/emc/global/dump
 export NST_FILE=$COMIN/gdas.t00z.dtfanl.nc

 export JCAP=1534
```

The output from the test showed it to correctly point to Kate's directories -

```
+ export FNTSFA=/gpfs/dell3/emc/global/dump/gdas.20190730/00/atmos/gdas.t00z.rtgssthr.grb
+ export FNSNOA=/gpfs/dell3/emc/global/dump/gdas.20190730/00/atmos/gdas.t00z.snogrb_t1534.3072.1536
+ export FNACNA=/gpfs/dell3/emc/global/dump/gdas.20190730/00/atmos/gdas.t00z.seaice.5min.blend.grb
```

The test passed as expected:

```
+ set +x

*********************************
<<< C768 GLOBAL CYCLE TEST PASSED. >>>
*********************************

------------------------------------------------------------
Sender: LSF System <lsfadmin@m52c19f>

```
