### ISSUE TITLE
release/public-v1: sorc/sfc_climo_gen.fd is incomplete

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [NOAA-EMC/UFS_UTILS#67]
sorc/sfc_climo_gen.fd is incomplete. And since it's not compiled in release/public-v1 branch it should be removed.

**Comment by climbfuji** [comment]
I am loosing track of all the issues you are reporting (thanks for going through all the libraries, by the way). Do you think you can create a small (temporary) google doc with links to all the open issues that need to be addressed for the public release branches?

**Comment by DusanJovic-NOAA** [comment]
@GeorgeGayno-NOAA @climbfuji sorc/sfc_climo_gen.fd is still incomplete. We should either delete it from the release/public-v1 branch or add missing files?

**Comment by GeorgeGayno-NOAA** [comment]
> 
> 
> @GeorgeGayno-NOAA @climbfuji sorc/sfc_climo_gen.fd is still incomplete. We should either delete it from the release/public-v1 branch or add missing files?

sfc_climo_gen is not part of the public release.  It should be removed.

**Comment by GeorgeGayno-NOAA** [comment]
@DusanJovic-NOAA Can we close this issue?

**Comment by DusanJovic-NOAA** [comment]
We can. But sorc/sfc_climo_gen.fd is still incomplete. It should be either removed or missing files added.
