### ISSUE TITLE
Utility to generate weights for interpolation.

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/UFS_UTILS#673]
The global-workflow houses a utility [weight_gen](https://github.com/NOAA-EMC/global-workflow/tree/develop/sorc/gaussian_sfcanl.fd/weight_gen).  Its description is contained in this [README](https://github.com/NOAA-EMC/global-workflow/blob/develop/sorc/gaussian_sfcanl.fd/weight_gen/README).

This utility is not used in the workflow and does not belong in the workflow.  

This issue is opened to document migrating the utility from global-workflow to ufs-utils.  The developers can assist in creating appropriate tests.

Tagging @yangfanglin @GeorgeGayno-NOAA for next steps.

**Comment by GeorgeGayno-NOAA** [comment]
Do you want just 'weight_gen' or the entire 'gaussian_sfcanl' suite of programs?

**Comment by aerorahul** [comment]
Just weight_gen, as it seems a much more general utility. The Gaussian Surface analysis utility has a specific application for global applications. 
We can discuss it's use and appropriate location later. 
This issue was to start that conversation. 
Thank you.

**Comment by GeorgeGayno-NOAA** [comment]
> Just weight_gen, as it seems a much more general utility. The Gaussian Surface analysis utility has a specific application for global applications. We can discuss it's use and appropriate location later. This issue was to start that conversation. Thank you.

I will look at `weight_gen` today.

**Comment by aerorahul** [comment]
Thank you @GeorgeGayno-NOAA 
The version in develop has not been converted to cmake.
I have a branch in review that builds this utility w/ CMake.
It is [here](https://github.com/NOAA-EMC/global-workflow/tree/feature/remove-obsolete-platforms/sorc/gaussian_sfcanl.fd/weight_gen)

**Comment by GeorgeGayno-NOAA** [comment]
> Thank you @GeorgeGayno-NOAA The version in develop has not been converted to cmake. I have a branch in review that builds this utility w/ CMake. It is [here](https://github.com/NOAA-EMC/global-workflow/tree/feature/remove-obsolete-platforms/sorc/gaussian_sfcanl.fd/weight_gen)

Thanks. It is working.

**Comment by GeorgeGayno-NOAA** [comment]
@aerorahul I think I have everything working. Do you have some existing 'scrip' files I can use for a baseline test? If not, can you try my branch at 5934dbc and let me know if it is working.

**Comment by GeorgeGayno-NOAA** [comment]
> @aerorahul I think I have everything working. Do you have some existing 'scrip' files I can use for a baseline test? If not, can you try my branch at [5934dbc](https://github.com/ufs-community/UFS_UTILS/commit/5934dbced55f54573b27cb7b3a93a75b24ea675c) and let me know if it is working.

@KateFriedman-NOAA Are there some existing 'scrip' files in our 'fix' directories?

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA Did you meant "script"? Please clarify.

In case it's useful, here is the list of high-level diffs between fix and fix_NEW right now:

/scratch1/NCEPDEV/global/glopara/diff_fix_fix_NEW.out

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA Did you meant "script"? Please clarify.
> 
> In case it's useful, here is the list of high-level diffs between fix and fix_NEW right now:
> 
> /scratch1/NCEPDEV/global/glopara/diff_fix_fix_NEW.out

No, I mean ESMF 'scrip'. When I run the 'weight_gen' program, it outputs a gaussian 'scrip' file (in NetCDF) for different resolutions. Are those files stored under 'fix' somewhere? I saw some 'scrip' files under 'fix_reg2grb2', but they were not gaussian.

@aerorahul and @yangfanglin Who uses this program?

**Comment by yangfanglin** [comment]
@GeorgeGayno-NOAA   You can find similar files under /scratch1/NCEPDEV/global/glopara/fix_nco_gfsv16/fix_fv3_gmted2010 on Hera.   They were use to convert forecast output on tiles written out by FMS to Gaussian grid.  I and Phil/Jeff used these SCRIP files for FV3GFS early development when the WRITE GRID COMPONENT capability was still under development.    The driver script that uses these SCRIP files is ./global-workflow/ush/fv3gfs_regrid_nemsio.sh

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA I think @yangfanglin answered your question, he would know more than me anyway. :)
