### ISSUE TITLE
Capability of converting RRFS restart files to cold start files

### ISSUE THREAD

**Issue by chunhuazhou** [NOAA-EMC/UFS_UTILS#682]
This capability is needed to get initial conditions files (in same format as from chgres_cube) from RRFS restart files after DA analysis.

**Comment by chunhuazhou** [comment]
@LarissaReames-NOAA @GeorgeGayno-NOAA @JeffBeck-NOAA This is the issue we talked about during today's meeting, about converting RRFS restart files to cold start format. Thank you so much in advance for your work on this!

**Comment by GeorgeGayno-NOAA** [comment]
What is the status of this issue? It does not look like any work has been done on it.

**Comment by GeorgeGayno-NOAA** [comment]
No movement on this issue. Will close.
