### ISSUE TITLE
Update for new 'fixed' directories

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#687]
The 'fixed' directories are undergoing a reorganization. This will require several script changes. For details, see:

https://github.com/NOAA-EMC/global-workflow/issues/966#issuecomment-1227692287

**Comment by KateFriedman-NOAA** [comment]
I will submit a PR into UFS_UTILS `develop` with the changes I made in my own testing and work with you to plan the merge into `develop` when we're ready. Stay tuned...
