### ISSUE TITLE
Add cmake test support for WCOSS2

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/UFS_UTILS#690]
There are currently only mpiexec scripts for Hera and Orion to submit the cmake test jobs to the job scheduler. Support for running the tests should be added for WCOSS2.

**Comment by WalterKolczynski-NOAA** [comment]
@GeorgeGayno-NOAA What account do you want me to use for the commit? I used GFS-DEV to run, but that probably isn't what you want in the repo.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA What account do you want me to use for the commit? I used GFS-DEV to run, but that probably isn't what you want in the repo.

GFS-DEV is fine. A user can change it if needed.
