### ISSUE TITLE
`cp` in NCO mode of `RUN_ENVIR`.

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/UFS_UTILS#694]
https://github.com/ufs-community/UFS_UTILS/blob/fb34823bc1f76986c495100d2d7928d4d94b70ed/sorc/link_fixdirs.sh#L31

This line needs to be uncommented when operating under NCO mode.
Please recut the tag `ops-gfsv16.2.1`

**Comment by GeorgeGayno-NOAA** [comment]
Should I keep the name of the tag the same or can I increment the number to 16.2.2?

**Comment by aerorahul** [comment]
If you will create a new tag, let it be 16.3.0 since that's the current implementation. 
@KateFriedman-NOAA please take note.

**Comment by GeorgeGayno-NOAA** [comment]
Updated at 8313030.

@aerorahul and @KateFriedman-NOAA Please check my branch. If correct, I will create a release tag.

**Comment by KateFriedman-NOAA** [comment]
Trying this update in a fresh checkout/build/link of the GFSv16.3.0 global-workflow package (with the hotfix/gfsv16.3.0 branch)...

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA Please also update the `FIX_DIR` paths to the special v16.3.0 fix set: `../fix_nco_gfsv16.3.0`

Here is the full block in the global-workflow link script:
```
if [ $machine == "cray" ]; then
    FIX_DIR="/gpfs/hps3/emc/global/noscrub/emc.glopara/git/fv3gfs/fix_nco_gfsv16"
elif [ $machine = "dell" ]; then
    FIX_DIR="/gpfs/dell2/emc/modeling/noscrub/emc.glopara/git/fv3gfs/fix_nco_gfsv16.3.0"
elif [ $machine = "wcoss2" ]; then
    FIX_DIR="/lfs/h2/emc/global/save/emc.global/FIX/fix_nco_gfsv16.3.0"
elif [ $machine = "hera" ]; then
    FIX_DIR="/scratch1/NCEPDEV/global/glopara/fix_nco_gfsv16.3.0"
elif [ $machine = "orion" ]; then
    FIX_DIR="/work/noaa/global/glopara/fix_nco_gfsv16.3.0"
fi
```

Apologies for not making sure you knew of this set earlier!

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA Please also update the `FIX_DIR` paths to the special v16.3.0 fix set: `../fix_nco_gfsv16.3.0`
> 
> Here is the full block in the global-workflow link script:
> 
> ```
> if [ $machine == "cray" ]; then
>     FIX_DIR="/gpfs/hps3/emc/global/noscrub/emc.glopara/git/fv3gfs/fix_nco_gfsv16"
> elif [ $machine = "dell" ]; then
>     FIX_DIR="/gpfs/dell2/emc/modeling/noscrub/emc.glopara/git/fv3gfs/fix_nco_gfsv16.3.0"
> elif [ $machine = "wcoss2" ]; then
>     FIX_DIR="/lfs/h2/emc/global/save/emc.global/FIX/fix_nco_gfsv16.3.0"
> elif [ $machine = "hera" ]; then
>     FIX_DIR="/scratch1/NCEPDEV/global/glopara/fix_nco_gfsv16.3.0"
> elif [ $machine = "orion" ]; then
>     FIX_DIR="/work/noaa/global/glopara/fix_nco_gfsv16.3.0"
> fi
> ```
> 
> Apologies for not making sure you knew of this set earlier!

No problem. I will also remove the references to our WCOSS1 system.

**Comment by GeorgeGayno-NOAA** [comment]
> > @GeorgeGayno-NOAA Please also update the `FIX_DIR` paths to the special v16.3.0 fix set: `../fix_nco_gfsv16.3.0`
> > Here is the full block in the global-workflow link script:
> > ```
> > if [ $machine == "cray" ]; then
> >     FIX_DIR="/gpfs/hps3/emc/global/noscrub/emc.glopara/git/fv3gfs/fix_nco_gfsv16"
> > elif [ $machine = "dell" ]; then
> >     FIX_DIR="/gpfs/dell2/emc/modeling/noscrub/emc.glopara/git/fv3gfs/fix_nco_gfsv16.3.0"
> > elif [ $machine = "wcoss2" ]; then
> >     FIX_DIR="/lfs/h2/emc/global/save/emc.global/FIX/fix_nco_gfsv16.3.0"
> > elif [ $machine = "hera" ]; then
> >     FIX_DIR="/scratch1/NCEPDEV/global/glopara/fix_nco_gfsv16.3.0"
> > elif [ $machine = "orion" ]; then
> >     FIX_DIR="/work/noaa/global/glopara/fix_nco_gfsv16.3.0"
> > fi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Apologies for not making sure you knew of this set earlier!
> 
> No problem. I will also remove the references to our WCOSS1 system.

What about jet? Will these files be hosted there at some point?

**Comment by KateFriedman-NOAA** [comment]
Jet won't be supported for GFSv16. We will support Jet in GFSv17+. The developmental fix set for GFSv17+ is on Jet, so you can add it to your `develop` branch for supporting GFSv17+: `/lfs4/HFIP/hfv3gfs/glopara/git/fv3gfs/fix`

**Comment by GeorgeGayno-NOAA** [comment]
Successfully tested 34ff043 on Orion, Hera and Cactus. 

@KateFriedman-NOAA go ahead and try it for yourself.

**Comment by KateFriedman-NOAA** [comment]
It works (thanks!) but need one more edit. Since this copy of fix for v16.3 is mostly symlinks to the prior v16 set (except for a few files that were modified for this implementation) both UFS_UTILS and global-workflow need to use the `L` flag with `cp` to copy the files through the symlinks and resolve them for NCO mode. Any file that isn't a symlink will be copied normally. This is the first implementation where we are using symlinks in the fix set, I overlooked this.

Please change this line to include `L`:
```
[[ $RUN_ENVIR = nco ]] && LINK="cp -rpL"
```

I tested the above change in my copy of UFS_UTILS hotfix branch, it worked. I am making the same update on the global-workflow side. Thanks!

**Comment by GeorgeGayno-NOAA** [comment]
> It works (thanks!) but need one more edit. Since this copy of fix for v16.3 is mostly symlinks to the prior v16 set (except for a few files that were modified for this implementation) both UFS_UTILS and global-workflow need to use the `L` flag with `cp` to copy the files through the symlinks and resolve them for NCO mode. Any file that isn't a symlink will be copied normally. This is the first implementation where we are using symlinks in the fix set, I overlooked this.
> 
> Please change this line to include `L`:
> 
> ```
> [[ $RUN_ENVIR = nco ]] && LINK="cp -rpL"
> ```
> 
> I tested the above change in my copy of UFS_UTILS hotfix branch, it worked. I am making the same update on the global-workflow side. Thanks!

Done at cfc4ca4.

**Comment by KateFriedman-NOAA** [comment]
Looks good! Feel free to merge and cut a new tag for v16.3.0 now, thanks! I'll update the UFS_UTILS tag name in global-workflow checkout script and the release notes once created.

**Comment by GeorgeGayno-NOAA** [comment]
Tag has been created. Closing.
