### ISSUE TITLE
link_fixdirs.sh does not error when an invalid run environment is provided

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/UFS_UTILS#700]
If an invalid `$RUN_ENVIR` is passed to `link_fixdirs.sh`, the script does not exit with a non-zero return code. It turns off the trace and prints an error message, but does not exit immediately.

**Comment by GeorgeGayno-NOAA** [comment]
@WalterKolczynski-NOAA Thanks for finding this bug. 

Does the LINK need to be fixed as well?

`[[ $RUN_ENVIR = nco ]] && LINK="cp -rp"`

Didn't you add the `-L` option for one of the GFS tags?

**Comment by WalterKolczynski-NOAA** [comment]
Looks like we're just using `cp -rp` in our link script, at least in develop.
