### ISSUE TITLE
Incorporate BNU soil type data

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#705]
Incorporate the BNU soil type data to support the regional model.

Data is available here: https://www2.mmm.ucar.edu/wrf/users/download/get_sources_wps_geog.html#optional

**Comment by GeorgeGayno-NOAA** [comment]
Data was pulled to Cactus using this command:

`wget https://www2.mmm.ucar.edu/wrf/src/wps_files/geog_alt_lsm.tar.gz`

The tar file was decompressed, then untarred:

`gzip -d geog_alt_lsm.tar.gz`
`tar -xvf geog_alt_lsm.tar`

All data was placed in `/lfs/h2/emc/global/noscrub/George.Gayno/ufs_utils.git/bnu.soil/orig_data`

**Comment by GeorgeGayno-NOAA** [comment]
Rongqian has created a file from the original dataset, not from the WRF tiles as I did. Hold further work for now.

**Comment by barlage** [comment]
@GeorgeGayno-NOAA The global 30" BNU soil type data in the same format as the global 30" VIIRS vegetation are stored in the land data space on hera: /scratch2/NCEPDEV/land/data/input_data/soil_type/soil_type.bnu.30s.nc

Note this is not internally compressed. If you want me to compress George, let me know. I will follow up with some more documentation.

**Comment by barlage** [comment]
@GeorgeGayno-NOAA for documentation and scripts, do you want a new directory added to the util directory with a readme and scripts?

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA The global 30" BNU soil type data in the same format as the global 30" VIIRS vegetation are stored in the land data space on hera: /scratch2/NCEPDEV/land/data/input_data/soil_type/soil_type.bnu.30s.nc
> 
> Note this is not internally compressed. If you want me to compress George, let me know. I will follow up with some more documentation.

Thanks, I will run a test grid with this data.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA for documentation and scripts, do you want a new directory added to the util directory with a readme and scripts?

We will add a new sub-directory under 'util': https://github.com/ufs-community/UFS_UTILS/tree/develop/util

It can contain a readme file and the source code. I would also include a simple build script and run script for the machine you used to create the data. How much source code/scripts are associated with this project?

**Comment by barlage** [comment]
@GeorgeGayno-NOAA I started a PR with the README and scripts/code. Let me know what else you would like done.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA The global 30" BNU soil type data in the same format as the global 30" VIIRS vegetation are stored in the land data space on hera: /scratch2/NCEPDEV/land/data/input_data/soil_type/soil_type.bnu.30s.nc
> 
> Note this is not internally compressed. If you want me to compress George, let me know. I will follow up with some more documentation.

Yes. Go ahead and compress the data.

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA - Yet another file to add to ./sfc_climo - /scratch2/NCEPDEV/land/data/input_data/soil_type/soil_type.bnu.30s.nc

No hurry.

**Comment by KateFriedman-NOAA** [comment]
Pulled into the Hera set:
```
[glopara@hfe07 20221017]$ pwd
/scratch1/NCEPDEV/global/glopara/fix/sfc_climo/20221017
[glopara@hfe07 20221017]$ ll soil_type.bnu.30s.nc 
-rw-r--r-- 1 glopara global 19578661 Oct 27 16:14 soil_type.bnu.30s.nc
```
I have some other new fix files to pull in from Russ so I'll rsync this new soil_type file to the other platforms when I rsync the others.

**Comment by GeorgeGayno-NOAA** [comment]
Note to self - file is on Hera, Orion and WCOSS2, but not Jet. Will hold off on merge.

**Comment by KateFriedman-NOAA** [comment]
Updated fix file is now on Jet as well.
