### ISSUE TITLE
In chgres_cube, increase character length of string array containing grid file names

### ISSUE THREAD

**Issue by gsketefian** [NOAA-EMC/UFS_UTILS#708]
DESCRIPTION:
--------------
In chgres_cube, in file `model_grid.F90`, the array containing the names of the grid tile files is declared as follows:
```
character(len=25)                 :: grid_files(num_tiles)
```
In the SRW App (ufs-srweather-app), the name of the grid file can exceed 25 characters when the grid gets very fine (e.g. 1km or less) and the C-resolution goes into 5 digits, e.g. a file name of `C10010_grid.tile7.halo4.nc`, which is 26 characters.

SOLUTION:
-----------
Change the declaration of the `grid_files` array to have a longer string length, e.g. 50 characters:
```
character(len=50)                 :: grid_files(num_tiles)
```
I have tested this and it works for the specific case described above.

**Comment by GeorgeGayno-NOAA** [comment]
Branch at 91049dc was tested on Jet. All chgres regression tests passed. Will issue PR.
