### ISSUE TITLE
MacOS workflow is broken

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#712]
Over the past month, the MacOS CI workflows have been breaking. I first noticed it in my fork. Then they started breaking after a PR was issued. Here is the error. 

https://github.com/ufs-community/UFS_UTILS/actions/runs/3413598831/jobs/5680502313

Needs to be fixed before any merges can be performed.

**Comment by GeorgeGayno-NOAA** [comment]
After a lot of trial and error, I was able to get it to run - but with using a previous version of macOS (11) and by removing the gcovr install step - 61384a5.

But this solution is not ideal. We want to continue to use the latest macOS. Try some other tests...

**Comment by GeorgeGayno-NOAA** [comment]
Let's start over using macos-latest:

1. Remove install of 'gcovr' (4d9d388). Now it breaks during the compile of mpi. Apparently, the latest version of macOS does not include gfortran09.  See: https://github.com/GeorgeGayno-NOAA/UFS_UTILS/actions/runs/3421393795/jobs/5697479326
2. Update to gfortran 11 (79d2f8e). Now it breaks because gfortan-11 does not allow for argument mismatches. See: https://github.com/GeorgeGayno-NOAA/UFS_UTILS/actions/runs/3422147871/jobs/5699191022
3. After a brief google search of other folks who had the same problem, try to fix this by updating the version of mpich (ffc4424).  But this broke because of a missing compiler flag. See: https://github.com/GeorgeGayno-NOAA/UFS_UTILS/actions/runs/3422335644/jobs/5699621718
4. Add the missing fortran flag (6eeeca2). Now it breaks building ESMF. See: https://github.com/GeorgeGayno-NOAA/UFS_UTILS/actions/runs/3422475799/jobs/5700295591

Hmmm. Will continue tomorrow...

**Comment by edwardhartnett** [comment]
Yes I just saw this on g2.

Change gfortran-9 to gfortran-12.

I also had to rebuild the caches, which I do by just adding "-1" to the cache key. 

See https://github.com/NOAA-EMC/NCEPLIBS-g2/pull/322/files

**Comment by GeorgeGayno-NOAA** [comment]
Added the '-fallow-argument-mismatch' flag to the ESMF build (7a6c930). The ESMF build was successful. But then the NCEPLIBS build failed: https://github.com/GeorgeGayno-NOAA/UFS_UTILS/actions/runs/3431897877/jobs/5720818549

Here is the error: _error: implicit declaration of function 'times' is invalid in C99 [-Werror,-Wimplicit-function-declaration]_

NCEPLIBS team (@edwardhartnett et. al), how do you build with newer versions of gnu?

**Comment by edwardhartnett** [comment]
Did Kyle switch the NCEPLIBS build to use spack for UFS_UTILS?

**Comment by GeorgeGayno-NOAA** [comment]
> Did Kyle switch the NCEPLIBS build to use spack for UFS_UTILS?

No. But @aerorahul said he would help.

**Comment by GeorgeGayno-NOAA** [comment]
The broken workflows will be fixed under #719. Closing.
