### ISSUE TITLE
orography and mask generation fails to create a value for high resolution grids

### ISSUE THREAD

**Issue by barlage** [NOAA-EMC/UFS_UTILS#714]
Current orography and mask generation fails to create a value for high resolution grids when no source inputs are contained in an FV3 grid.

The current code takes a subset of source points surrounding the fv3 grid to create a mask and orography stats based on the source points that are in the fv3 grid. The current failure happens when there are no source points in the fv3 grid.

**Comment by GeorgeGayno-NOAA** [comment]
Here is an illustration of the problem. This is a plot of the orography for a fire weather nest in California. The model points in purple have no source orography points located within its boundaries.

![Orog_raw](https://user-images.githubusercontent.com/52789452/200925626-27e01e0b-5cf2-498b-90be-ebd2b524eee4.jpeg)

**Comment by GeorgeGayno-NOAA** [comment]
The same problem exists in routines MAKEPC2 and MAKEOA2. These routines create the GWD fields. If there are no source points within a model grid box, then the GWD fields are set to initial values of zero. Updating these routines will be more complicated.

**Comment by GeorgeGayno-NOAA** [comment]
Also, some of these GWD fields require multiple source points within a model box for a proper calculation. So, I suspect none of these fields are well calculated. We really need to use higher-resolution input data. Is GWD used in the fire WX domain?

**Comment by barlage** [comment]
@GeorgeGayno-NOAA I spoke with the NESDIS/UMD developers of the water fraction product last week and they will produce a 7.5" global water fraction for us, which we can pair with the 7.5" GMTED elevation product. Hopefully this resolution will suffice for near future needs.
