### ISSUE TITLE
Orographic asymmetry (OA) fields generated by orog_gsl have a negative bias, especially for high-resolution grids

### ISSUE THREAD

**Issue by mdtoyNOAA** [NOAA-EMC/UFS_UTILS#716]
The orographic asymmetry (OA) fields generated by orog_gsl have a negative bias, especially for high resolution grids.  In the presentation by Michael Toy at NOAA/GSL (attached), the difference between the OA3 fields for C768 (13km) and C96 (100km) are shown.  The C96 shows a slight negative bias, while the C768 grid has a large negative bias.  The issue is that with higher-resolution grids, there are fewer fine-grid (5km spacing for large-scale fields, and 1km for small-scale fields) topographic data points within each model grid cell to use for sampling and determining the statistical properties, such as OA.  Songyou Hong (NOAA/PSL) discovered that the cause of the negative bias is due to the case when there are an odd number of fine-grid points along a cardinal direction relative to the model grid cell.  The limits of the "do-loops" for OA calculation cause fewer points to be sampled in one-half of the grid cell than the other.  Songyou found a fix to this problem (see his attached 11/14/22 presentation), which is to modify the limits of the "do-loops" when there are an odd number of fine-grid points along a cardinal direction so that the number of points in each half of the grid are the same.

[Songyou Hong presentation -- Nov 14, 2022](https://github.com/ufs-community/UFS_UTILS/files/10069676/20221114_oGWD-2022NOV-SOS.pdf)

[Michael Toy presentation -- Nov 21, 2022](https://github.com/ufs-community/UFS_UTILS/files/10069663/mdtoy_oa3_presentation_2022_11_21.pdf)

**Comment by barlage** [comment]
@mdtoyNOAA @yangfanglin Just want to let you know that we have run into some issues with needing higher resolution "fine-grid" data for fire weather domains (~1.5km) so we have asked our collaborators at UMD and NESDIS to produce a land mask (consistent with the current global water fraction data) at 7.5 arcsec (~250m) coupling this with the same resolution of GMTED2010 elevation data. Do you think this will help solve any of your issues? We have a quick fix for orography and mask (https://github.com/ufs-community/UFS_UTILS/pull/713) but this doesn't solve the OA and other derived inputs issues.

**Comment by mdtoyNOAA** [comment]
> 

Thank you for the info, @barlage.  I think we will be able to use the new high-res dataset you mentioned.  For now, the fix we implemented will work down to about ~3km grids, but for any finer grids, we'll need to investigate the 7.5 arcsec dataset.
