### ISSUE TITLE
Update sfc_climo_gen to include soil color dataset needed by noahmp land model

### ISSUE THREAD

**Issue by barlage** [NOAA-EMC/UFS_UTILS#720]
Noah-MP land model defines soil albedo through a lookup table based on a soil color classification. There is a readily available dataset developed for the CLM/CTSM land model (see Lawrence and Chase(2007) JGR, doi:10.1029/2006JG000168) that can be used. This dataset has already been formatted to be consistent with sfc_climo_gen input requirements (/scratch2/NCEPDEV/land/data/input_data/soil_color/soil_color.clm.0.05.nc). The capability to produce this data on the UFS grid is needed.

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA Can you please add this file to the `./fix/sfc_climo` directory on each machine - /scratch2/NCEPDEV/land/data/input_data/soil_color/soil_color.clm.0.05.nc

No hurry. Thanks!

**Comment by RongqianYang-NOAA** [comment]
The tiled soil color data on various fractional grids (C48,C96,C192,C384,C768 and C1152) is 
available on Hera under "/scratch2/NCEPDEV/land/data/input_data/soil_color_clm_tiled/".
The data was generated using the 'sfc_climo_gen' utility of UFS_utils , with code changes made
necessary for the addition of the new soil color field. The addition of the soil color field follows 
exactly the same way as for the soil type field. The existing fractional orography data under 
"/scratch1/NCEPDEV/global/glopara/fix/orog/20220805/'RES'.'OCN'_frac/" was used in the 
generation runs (where 'RES' represents resolution - e.g.,'C48','C96' ..., and 'OCN' is the 
resolution of MOM6 used in the water fraction creation - e.g.,'mx500' for C48, 'mx100' for C96 ...).

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA Can you please add this file to the `./fix/sfc_climo` directory on each machine - /scratch2/NCEPDEV/land/data/input_data/soil_color/soil_color.clm.0.05.nc

I've pulled that file into the `fix` set on Hera an rsync'd it to Jet, Orion, and WCOSS2-Dogwood. Will be available on WCOSS2-Cactus as soon as the dev_transfer rsync job starts.

**Comment by KateFriedman-NOAA** [comment]
I should also have pointed out, it's in the newer 20221017 sfc_climo subfolder:
```
[glopara@hfe12 20221017]$ pwd
/scratch1/NCEPDEV/global/glopara/fix/sfc_climo/20221017
[glopara@hfe12 20221017]$ ll soil_color.clm.0.05.nc 
-rw-r--r-- 1 glopara global 103865024 Dec  8 19:53 soil_color.clm.0.05.nc
```

**Comment by GeorgeGayno-NOAA** [comment]
> I should also have pointed out, it's in the newer 20221017 sfc_climo subfolder:
> 
> ```
> [glopara@hfe12 20221017]$ pwd
> /scratch1/NCEPDEV/global/glopara/fix/sfc_climo/20221017
> [glopara@hfe12 20221017]$ ll soil_color.clm.0.05.nc 
> -rw-r--r-- 1 glopara global 103865024 Dec  8 19:53 soil_color.clm.0.05.nc
> ```

Thanks, @KateFriedman-NOAA, I did not realize that file was already hosted.

@RongqianYang-NOAA has mapped this data to our standard fractional grids - ./orog/C???.mx???_frac. At some point, he will want his data added to those directories.

**Comment by KateFriedman-NOAA** [comment]
> Thanks, [@KateFriedman-NOAA](https://github.com/KateFriedman-NOAA), I did not realize that file was already hosted.

In case my words confused...it wasn't already in there, I added it new to that specific timestamp subfolder. :)

**Comment by StevePny** [comment]
@GeorgeGayno-NOAA @KateFriedman-NOAA 

The file soil_color.clm.0.05.nc is not available in the public link pointed to by:
https://noaa-emcufs-utils.readthedocs.io/en/latest/ufs_utils.html

Which points to:
https://noaa-ufs-srw-pds.s3.amazonaws.com/index.html#fix/fix_sfc_climo/

I also do not see it at any of these locations:
https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/GFS/fix/
https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/GFS/fix_nco_gfsv16/
https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/GFS/fix_nco_gfsv15/

This missing file is currently breaking my execution of fv3gfs_driver_grid.sh

```
 - OPEN FILE: /UFS_UTILS/ush/..//fix/sfc_climo/soil_color.clm.0.05.nc
 
 FATAL ERROR: OPENING INPUT SOURCE FILE: No such file or directory
```
Is there a place this file can be found online?

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA @KateFriedman-NOAA
> 
> The file soil_color.clm.0.05.nc is not available in the public link pointed to by: https://noaa-emcufs-utils.readthedocs.io/en/latest/ufs_utils.html
> 
> Which points to: https://noaa-ufs-srw-pds.s3.amazonaws.com/index.html#fix/fix_sfc_climo/
> 
> I also do not see it at any of these locations: https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/GFS/fix/ https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/GFS/fix_nco_gfsv16/ https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/GFS/fix_nco_gfsv15/
> 
> This missing file is currently breaking my execution of fv3gfs_driver_grid.sh
> 
> ```
>  - OPEN FILE: /UFS_UTILS/ush/..//fix/sfc_climo/soil_color.clm.0.05.nc
>  
>  FATAL ERROR: OPENING INPUT SOURCE FILE: No such file or directory
> ```
> 
> Is there a place this file can be found online?

@JeffBeck-NOAA Do you know who hosts the 'fixed' data to amazonaws?

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA @KateFriedman-NOAA
> 
> The file soil_color.clm.0.05.nc is not available in the public link pointed to by: https://noaa-emcufs-utils.readthedocs.io/en/latest/ufs_utils.html
> 
> Which points to: https://noaa-ufs-srw-pds.s3.amazonaws.com/index.html#fix/fix_sfc_climo/
> 
> I also do not see it at any of these locations: https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/GFS/fix/ https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/GFS/fix_nco_gfsv16/ https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/GFS/fix_nco_gfsv15/
> 
> This missing file is currently breaking my execution of fv3gfs_driver_grid.sh
> 
> ```
>  - OPEN FILE: /UFS_UTILS/ush/..//fix/sfc_climo/soil_color.clm.0.05.nc
>  
>  FATAL ERROR: OPENING INPUT SOURCE FILE: No such file or directory
> ```
> 
> Is there a place this file can be found online?

@StevePny You don't have access to our NOAA RDHPCS machines?

**Comment by StevePny** [comment]
@GeorgeGayno-NOAA No longer, I'm running everything on AWS ec2 right now. Also, in general for the UFS community many others will not have access to RDHPCS.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA @KateFriedman-NOAA
> 
> The file soil_color.clm.0.05.nc is not available in the public link pointed to by: https://noaa-emcufs-utils.readthedocs.io/en/latest/ufs_utils.html
> 
> Which points to: https://noaa-ufs-srw-pds.s3.amazonaws.com/index.html#fix/fix_sfc_climo/
> 
> I also do not see it at any of these locations: https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/GFS/fix/ https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/GFS/fix_nco_gfsv16/ https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/GFS/fix_nco_gfsv15/
> 
> This missing file is currently breaking my execution of fv3gfs_driver_grid.sh
> 
> ```
>  - OPEN FILE: /UFS_UTILS/ush/..//fix/sfc_climo/soil_color.clm.0.05.nc
>  
>  FATAL ERROR: OPENING INPUT SOURCE FILE: No such file or directory
> ```
> 
> Is there a place this file can be found online?

@KateFriedman-NOAA do you host the files on https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/GFS/fix/fix_sfc_climo/

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA do you host the files on https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/GFS/fix/fix_sfc_climo/

I do. Apologies, I see we failed to keep the ftp server fix set updated with the on-disk sets. Let me look into doing this, I need to make sure we have the room on the ftp server since we've tripled the fix set since it was last updated there. Stay tuned...

**Comment by KateFriedman-NOAA** [comment]
Note the restructuring that happened last year would also occur in the fix set if I update it with the current state of things.

**Comment by KateFriedman-NOAA** [comment]
> @JeffBeck-NOAA Do you know who hosts the 'fixed' data to amazonaws?

I second @GeorgeGayno-NOAA 's question. Sounds like that set needs to get updated. I'm not getting good news on available space on ftp to keep adding fix files there.

**Comment by JeffBeck-NOAA** [comment]
@MichaelLueken, could you put us in contact with whoever manages the fixed files on AWS?  Thanks!

**Comment by MichaelLueken** [comment]
@JeffBeck-NOAA,  I'm working on trying to figure out to put you in contact with to add this fix file to AWS.  How urgent is it that the file is added?  Thanks!

**Comment by GeorgeGayno-NOAA** [comment]
> @JeffBeck-NOAA, I'm working on trying to figure out to put you in contact with to add this fix file to AWS. How urgent is it that the file is added? Thanks!

@MichaelLueken The file was requested by @StevePny.

**Comment by MichaelLueken** [comment]
@StevePny I have been asked to see the urgency of making this file available on AWS.  Please let me know if you still require this file so that I can let the Project Owner of the team who would need to add this file know.  Thanks!

**Comment by StevePny** [comment]
Hi @MichaelLueken, at the moment, the absence of this file is crashing my use of UFS_UTILS to generate grids, as of the change associated with this issue (~December 8). This breaks the functionality described at https://noaa-emcufs-utils.readthedocs.io/en/latest/ufs_utils.html for any outside users. I suppose I can pull a tag from before this change in the meantime, but in general I would consider that high priority. 

For example, this documentation says:
```
The surface climatological data is located here [./fix/fix_sfc_climo](https://noaa-ufs-srw-pds.s3.amazonaws.com/index.html#fix/fix_sfc_climo/). All NetCDF.

Global 1-degree fractional coverage strong/weak zenith angle albedo - facsf.1.0.nc
Global 0.05-degree maximum snow albedo - maximum_snow_albedo.0.05.nc
Global 2.6 x 1.5-degree soil substrate temperature - substrate_temperature.2.6x1.5.nc
Global 0.05-degree four component monthly snow-free albedo - snowfree_albedo.4comp.0.05.nc
Global 1.0-degree categorical slope type - slope_type.1.0.nc
Global 0.05-degree CLM soil color (Lawrence and Chase, 2007 JGR) - soil_color.clm.0.05.nc
```
and yet the file soil_color.clm.0.05.nc is not in the location stated.

**Comment by JeffBeck-NOAA** [comment]
@StevePny, the soil color file now exists in the AWS bucket.  Can you check that it works for you?  Thanks!

**Comment by StevePny** [comment]
Hi @JeffBeck-NOAA, thanks yes I am able to wget the file now and run both  ./fv3gfs_driver_grid.sh and ./chgres_cube.sh successfully.

**Comment by JeffBeck-NOAA** [comment]
Thanks @StevePny, glad to hear it's working!  @MichaelLueken, thanks for your help!

**Comment by cigdemakan** [comment]
Hello all. I also need the soil_color.clm.0.05.nc, and I can't find it in any of the links provided in this thread. Is there a new link for this file?

**Comment by JeffBeck-NOAA** [comment]
HI @MichaelLueken , do you know where the soil_color.clm.0.05.nc file can be found on AWS? It's not in any of the "develop" folders here: https://noaa-ufs-srw-pds.s3.amazonaws.com/index.html. Is it possible to get it repopulated for @cigdemakan? For reference, it's available on Ursa here: "/scratch3/NCEPDEV/global/role.glopara/fix/sfc_climo/20230925/soil_color.clm.0.05.nc" (Thanks, @barlage!)

**Comment by MichaelLueken** [comment]
Hi @cigdemakan and @JeffBeck-NOAA, the file currently isn't available in the SRW App's S3 bucket.  I have requested that the data manager in EPIC add the file back to the S3 bucket.

In the meantime, it looks like the same file can be pulled from the [global S3 bucket](https://noaa-nws-global-pds.s3.amazonaws.com/fix/sfc_climo/20230925/soil_color.clm.0.05.nc) - https://noaa-nws-global-pds.s3.amazonaws.com/index.html#fix/sfc_climo/20230925/

**Comment by JeffBeck-NOAA** [comment]
Thanks, @MichaelLueken !

**Comment by cigdemakan** [comment]
Thank you all very much! I appreciate it.

**Comment by MichaelLueken** [comment]
Hi @cigdemakan and @JeffBeck-NOAA - I just wanted to let you know that the [soil_color.clm.0.05.nc](https://noaa-ufs-srw-pds.s3.amazonaws.com/develop-20250702/fix/fix_sfc_climo/soil_color.clm.0.05.nc) file is once again available in the SRW S3 bucket - https://noaa-ufs-srw-pds.s3.amazonaws.com/index.html#develop-20250702/fix/fix_sfc_climo/.

Please let me know if you encounter any issues.
