### ISSUE TITLE
Is this really the best way to handle external code in global_cycle?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#730]
I am getting this error:

```
CMake Error at sorc/global_cycle.fd/CMakeLists.txt:27 (add_library):
536
  Cannot find source file:
537

538
    ../../ccpp-physics/physics/sfcsub.F
```

When I look in the CMakeList.txt file for global_cycle I see:

```
set(lib_src
    machine.f90
    num_parthds.f90
    ../../ccpp-physics/physics/sfcsub.F
    read_write_data.f90
    utils.F90
    land_increments.f90)

```

So this will only work if build as part of a larger nceplibs build? That doesn't seem good.

Seems like just taking a copy of the file would be better. Otherwise how are other packages, like spack, to build UFS_UTILS?

Or am I missing something?

**Comment by GeorgeGayno-NOAA** [comment]
We don't want to keep a separate copy of sfcsub.F in UFS_UTILS. So, we use submodules to link to the version in the CCPP repository. I am open to a better solution.

**Comment by edwardhartnett** [comment]
I think keeping a copy would be a better solution.

We cannot use git submodules to distribute our software. For one thing, NCO demands a tarball, not a git clone. For another, it breaks all other forms of release. The only way to install the software is through git. That's not really going to work.

**Comment by edwardhartnett** [comment]
Another question @GeorgeGayno-NOAA: it seems like this is pointing at a moving target. That is, the owners of sfcsub.F can change the code at any time.

When we get an old release of UFS_UTILS, we will not get the version of sfcsub.F which we used in testing that release. We will get the current version of sfcsub.F, and it could break that old release of UFS_UTILS. So this makes the releases unstable.

We must take a copy of the code file and make it part of UFS_UTILS. Then, periodically (like before every release) you can see if there is a new version of the file, and, if so, update the one in UFS_UTILS before release, ensuring full testing with the new version, and a stable release.

So whatever version of sfcsub.F we have in UFS_UTILS for a release, it's that version in that release forever. If a new version of sfcsub.F comes out, and we need to accommodate it, then we do a new release of UFS_UTILS. But old releases will still keep the old copies of sfcsub.F they were built and tested with.

Does that make sense @GeorgeGayno-NOAA ?

**Comment by edwardhartnett** [comment]
Also, how do you get this file on your local machine when building UFS_UTILS?

I've tried this, but it doesn't seem to work:
` git submodule update --recursive`

**Comment by edwardhartnett** [comment]
OK, I was forgetting the --init:

`git submodule update --init --recursive`

**Comment by arunchawla-NOAA** [comment]
If this is answered can we close this? I am wondering if questions are better put under the GitHub discussions forum. That was created for this purpose

**Comment by arunchawla-NOAA** [comment]
@GeorgeGayno-NOAA and @edwardhartnett can we close this issue? This seems better handled in Github discussions
