### ISSUE TITLE
delete master branch and master branch protection rules?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#733]
Like other projects we have been using the develop branch for quite a while.

On other NCEPLIBS projects we have deleted the master branch. It has no meaning and would be confusing to anyone who tried to use it.

@GeorgeGayno-NOAA any objections?

**Comment by GeorgeGayno-NOAA** [comment]
No objections.

**Comment by edwardhartnett** [comment]
Done.
