### ISSUE TITLE
Updated presentation available?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#738]
In our README.md we have:

`Gayno G., Beck J., Carson L., [Pre-Processing: chgres_cube](https://github.com/ufs-community/UFS_UTILS/blob/develop/docs/20201105-0945a-pre-processing-chgres-cube-gayno-final.pdf), UFS MRW App Training, 5 November 2020.`

@GeorgeGayno-NOAA have you make any presentation since then that we should add?

Do you make a presentation every year at the UFS workshop?

**Comment by edwardhartnett** [comment]
@GeorgeGayno-NOAA is there a more recent presentation? If not, I will close this issue...

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA is there a more recent presentation? If not, I will close this issue...

I don't have a more recent presentation, but @JeffBeck-NOAA or @LarissaReames-NOAA may have one.

**Comment by JeffBeck-NOAA** [comment]
Hi @GeorgeGayno-NOAA, @edwardhartnett, we have [this version](https://docs.google.com/presentation/d/1GlCb2AYBQKJZ4T84WoR3O0ANgcy6LkQg0GvaEPvBODg/edit#slide=id.p), which is an updated overview of pre-processing for the SRW App.

**Comment by arunchawla-NOAA** [comment]
Hi is this still an issue? We should close this if it is resolved

**Comment by GeorgeGayno-NOAA** [comment]
Unfortunately, we don't have a current preprint/paper for chgres. Will close for now.
