### ISSUE TITLE
any way to build ESMF for UFS_UTILS with less options?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#740]
NetCDF gives us options like --disable-utilities, which allow for a faster compile of the lbrary in CI.

Does ESMF have anything similar? Anything we can turn off in the build to save time, but still provide everything UFS_UTILS needs?

@GeorgeGayno-NOAA do you know?

**Comment by GeorgeGayno-NOAA** [comment]
@edwardhartnett I do not know. Perhaps @theurich can advise.

**Comment by theurich** [comment]
You can set `ESMF_MOAB=OFF` to turn off building MOAB. This portion of the code is not yet used internally by default, and I doubt that UFS_UTILS is making the required run-time call to use it.
The only other part that might have some significant savings is to set `ESMF_ARRAY_LITE=TRUE`. This reduces the the overloading of Array and Field classes to only up to 4D, which might be sufficient for UFS_UTILS, also.
Obviously, using an external PIO via `ESMF_PIO=external` will safe you the time of internally building it, but I assume you are already doing that.
Those are the lowest hanging fruit I can think at the moment.
