### ISSUE TITLE
MacOS CI build breaking

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/UFS_UTILS#756]
Well the MacOS CI builds all broke a little while ago.

The main problem seems to be the brew update command. This command updates all the software (apparently) on the MacOS. It's slow and unnecessary, as we use very little - just compilers and a few tools. Somehow the brew update command is broken on macos-latest in GitHub. Something fails to do with PHP. However, removing the brew update command works.

Meanwhile, another of the workflows was building mpich/openmpi. Actually we don't need to build these, we can just install them with package management tools apt-get on Linux and brew on MacOS. Something about the build of mpich broke on the MacOS. Something to do with the new compilers I think. Rather than fix that, I just switch to using package management installs.

Currently there is a compile problem for the code, which I'm asking George about, and an ESMF build problem, which I am asking ESMF about.

**Comment by edwardhartnett** [comment]
I am still working on this but stuck on ESMF build.

**Comment by GeorgeGayno-NOAA** [comment]
Is this still needed in light of #668? Will close for now.

**Comment by aerorahul** [comment]
@GeorgeGayno-NOAA 
If necessary, I could attempt to add a similar `mac_clang.yaml` workflow that tests the ufs-utils on macOS.
Let me know if that is desired.
