### ISSUE TITLE
Remove `checksum` from `sfcanl_data.tileX.nc` files following `global_cycle`.

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/UFS_UTILS#781]
When the `sfcanl_data.tileX.nc` files are created with the program `global_cycle`, the `checksum` global attribute is retained.
This `checksum` is bound to be incorrect (unless recalculated), when fields are updated.

This is seen when using `GFSv16` CCPP SDF.  The model fails after `global_cycle` updates the `sfc_data.tileX.nc` files to produce `sfcanl_data.tileX.nc`.

@CoryMartin-NOAA ran into this issue when he tested the cycled global-workflow with the GFSv16 configuration.  

A requested solution is to delete the `checksum` global attribute from the `sfcanl_data.tileX.nc` files in the utility `global_cycle`.

The proposal is being tested via: https://github.com/aerorahul/UFS_UTILS/pull/new/feature/checksum

**Comment by GeorgeGayno-NOAA** [comment]
Will work this issue under this branch:
https://github.com/GeorgeGayno-NOAA/UFS_UTILS/tree/feature/checksum

**Comment by GeorgeGayno-NOAA** [comment]
@aerorahul I have logic working that will remove the 'checksum' attribute. Before I go further, should I remove 'checksum' from **all** records in the file, or only those records that get updated? For NoahMP, I will only update a small subset of the records in the file.

**Comment by GeorgeGayno-NOAA** [comment]
@aerorahul Please try my branch at 2c5ff01, which will remove 'checksum' for all updated records.

**Comment by aerorahul** [comment]
Thanks @GeorgeGayno-NOAA.  Will give it a try.

**Comment by CoryMartin-NOAA** [comment]
Looks like this does the trick, an older version of UFS_UTILS causes the forecast to fail due to incorrect checksums, but this commit allows the model to initialize.

**Comment by GeorgeGayno-NOAA** [comment]
> Looks like this does the trick, an older version of UFS_UTILS causes the forecast to fail due to incorrect checksums, but this commit allows the model to initialize.

Great. I will initiate a PR.
