### ISSUE TITLE
Change orog_mask_tools inputs from binary to netcdf

### ISSUE THREAD

**Issue by barlage** [NOAA-EMC/UFS_UTILS#786]
mtnlm7_oclsm.F reads binary files (landcover30.fixed, gmted2010.30sec.int, thirty.second.antarctic.new.bin) to create orography inputs on tiles. For future efforts to make these files consistent with land source data mask (e.g., from new VIIRS vegetation), using higher resolution inputs, and for greater transparency, convert the reads to netcdf.

**Comment by GeorgeGayno-NOAA** [comment]
@barlage - this issue has been open for a while.  I can start converting the existing inputs to the orog code to netcdf.
