### ISSUE TITLE
chgres_cube - problem with call to routine "search_many"

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#797]
When running is Debug mode, the chgres_cube regression tests are crashing at the calls to routine "search_many". That routine is called from each MPI task, but some of the arguments have only been allocated on task 0. For example, the tests crash with an error about 'land_target_one_tile' not being allocated. 

```
   if (localpet == 0) then
     allocate(land_target_one_tile(i_target,j_target))
     land_target_one_tile = 0
     where(mask_target_one_tile == 1) land_target_one_tile = 1
   endif

   call search_many(num_fields,bundle_allland_target,data_one_tile, land_target_one_tile,&
                    tile,search_nums,localpet)

   if (localpet == 0) deallocate(land_target_one_tile)
```

After a code handoff, NCO will now compile/run all tags in Debug mode. For the Intel compiler, that mode must include at least `-check all -ftrapuv`.

As a future item, at least one of the regression tests should run in Debug mode.

**Comment by GeorgeGayno-NOAA** [comment]
@LarissaReames-NOAA I recall you had a fix ready? If so, I can test it.

**Comment by LarissaReames** [comment]
> @LarissaReames-NOAA I recall you had a fix ready? If so, I can test it.

I'm running the GitHub actions in my fork right now. Once those pass I'll submit a PR. If you'd like to test before then, here's the branch: https://github.com/LarissaReames-NOAA/UFS_UTILS/tree/feature/fix_chres_unallocated_bug

**Comment by GeorgeGayno-NOAA** [comment]
@BinLiu-NOAA and @ZhanZhang-NOAA - chgres_cube now runs on WCOSS2 in "Debug' mode.
