### ISSUE TITLE
Remove spurious ice points from VIIRS vegetation data

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#803]
The VIIRS data has some spurious ice points in Louisiana and the Bahamas. The number of points is very small. But when running high-resolution regional grids, the fraction of 'ice' at grid point can be non-zero. @barlage has an updated VIIRS dataset as well as a consistent BNU soil type dataset.

We will need to ask @KateFriedman-NOAA to host these updated files (including 0.03/0.05/0.1-degree resolution versions) in the official 'fix' directories.

**Comment by KateFriedman-NOAA** [comment]
Point me to the updates files when ready and I'll pull them into the primary fix sets. Thanks!
