### ISSUE TITLE
Update GDAS_INIT utility for new coldstart directory structure

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#817]
The global workflow group is reorganizing the COM directory (https://github.com/NOAA-EMC/global-workflow/pull/1421)

Currently, the GDAS_INIT utility places the ENKF coldstart files in: `./enkfgdas.YYYYMMDD/HH/mem???/atmos/INPUT`

Update the utility to place the ENKF coldstart files here: `./enkfgdas.YYYYMMDD/HH/atmos/mem???/INPUT`

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA only the ENKF directories will change, correct?

**Comment by KateFriedman-NOAA** [comment]
@GeorgeGayno-NOAA You have the directory structure backwards in the issue comment...it's currently:
`./enkfgdas.YYYYMMDD/HH/mem???/atmos/INPUT`

I think you just need to add the `/atmos` under `mem###` to capture the prior reorg for the enkf folders. To answer you question, it was just the enkf member folders that were affected previously. The major COM reorg PR is going in today...I will see what other changes may be needed for `gdas_init` (likely also in the non-enkf folders too). I'll try to look at things tomorrow after the g-w COM reorg PR has gone in and provide a summary of needed changes in this issue. Stay tuned...

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA You have the directory structure backwards in the issue comment...it's currently: `./enkfgdas.YYYYMMDD/HH/mem???/atmos/INPUT`
> 
> I think you just need to add the `/atmos` under `mem###` to capture the prior reorg for the enkf folders. To answer you question, it was just the enkf member folders that were affected previously. The major COM reorg PR is going in today...I will see what other changes may be needed for `gdas_init` (likely also in the non-enkf folders too). I'll try to look at things tomorrow after the g-w COM reorg PR has gone in and provide a summary of needed changes in this issue. Stay tuned...

All right. We can adjust the scope of this issue as needed.
