### ISSUE TITLE
Create oro from scratch for coupled model

### ISSUE THREAD

**Issue by sanatcumar** [NOAA-EMC/UFS_UTILS#825]
Aim is to create a single step procedure for atmosphere-land coupled grid generation that is well documented, easily reproducible. The procedure has the capability to generate combinations of ocean and atmospheric resolutions.

The multi step procedure to generate coupled grids are as follows. Steps 1- 5 are run as a single script and steps 6 - 9 are then run individually using custom scripts.* 

1. fv3gfs_make_grid.sh (make 'grid' files)
2. fv3gfs_make_orog.sh (make 'oro' files)
3. fv3gfs_make_lake.sh (optionally add lakes to oro file)
4. fv3gfs_filter_topo.sh (filter topography) 
5. sfc_climo_gen.sh (create surface climo fields)
6. Shan's fortran merge code.exe reads pre-generated ocean mask using cpld_gridgen procedure given below**
8. fv3gfs_make_orog.sh is run again as landpoints can change 
9. fv3gfs_filter_topo.sh (filter topography)
10. sfc_climo_gen.sh (re-create surface climo fields)

*The new single step procedure calls the following in order using a single script

1. fv3gfs_make_grid.sh (make 'grid' files)
2. fv3gfs_make_lake.sh (adds lakes and resolves the coastal lake issue)
3. fv3gfs_make_orog.sh (make land mask and exits for uniform grid type only, generates oro for other grid types)
4. fv3gfs_ocean_merge.sh (Reads pre-generated ocean grid and merges them for uniform grid type only)
5. fv3gfs_make_orog.sh (reads merged masks and makes 'oro' files for uniform grid type only. Resolves orography issues for fractional land near coasts)
6. fv3gfs_make_orog_gsl.sh (make gsl drag 'oro' files for uniform grid type only)
8. fv3gfs_filter_topo.sh (filter topography)
9. sfc_climo_gen.sh (create surface climo fields)
10. Include a readme file in the output folder with all relevant information needed to regenerate the outputs

**Generate ocean mask using cpld_gridgen procedure in HERA

Check-out ufs-utils (and be sure to check out the ccpp submodule)
cd fix 
./link_fixdirs.sh emc hera
cd ../reg_tests/cpld_gridgen
Edit the rt.conf and add the non-standard case(s) you want to generate
Note you need to keep/run the C384_025 case because the lower resolution cases 
depend on it to generate the remapping weights used to create the CICE ICs and/
or do the Post jobs.
Edit rt.sh for proper accounts/partitions
Build and run the test using ./rt.sh -b >output 2>&1 &
Your results should be in /scratch1/NCEPDEV/stmp4/First.Last/CPLD_GRIDGEN/rt_#

**Comment by GeorgeGayno-NOAA** [comment]
Instead of running the orog program twice (steps 2 and 8), could Shan's algorithm be incorporated as part of the orog code?

**Comment by sanatcumar** [comment]
Step 7  needs the step2 oro  files as it takes the lake info from it first. Step 7 can change the land points. So it needs to be run twice.  I believe @shansun6 can help address this ?

**Comment by GeorgeGayno-NOAA** [comment]
I also see that `sfc_climo gen` is run twice (steps 5 and 9). Why is that?

**Comment by sanatcumar** [comment]
The sfc_climo is run just once in this single step procedure. I have edited the start of this conversation to reflect this
