### ISSUE TITLE
variable grid_files in model_grid.F90: filenames can be larger than 25 characters

### ISSUE THREAD

**Issue by mefrediani** [NOAA-EMC/UFS_UTILS#828]
https://github.com/ufs-community/UFS_UTILS/blob/ca9bed8967edb272272894e23727eb522e35d690/sorc/chgres_cube.fd/model_grid.F90#L1198

With the name auto-generated for my grid, the size of the grid_files string became 26 characters. The task make_grid completes without issues but the tasks make_ics and make_lbcs crash, with a message saying the grid file isn't avalable.   
See the screenshot below showing the "c" is cut off from the end of the file path. 
<img width="1527" alt="image" src="https://github.com/ufs-community/UFS_UTILS/assets/43454744/597447de-5871-4217-88e2-62ffc340eba6">

**Comment by GeorgeGayno-NOAA** [comment]
@mefrediani - This was fixed at d0040d5. Can you use the latest version of 'develop'?

**Comment by mefrediani** [comment]
Great! Thanks for letting me know, @GeorgeGayno-NOAA.
