### ISSUE TITLE
Is there any plan to support sfc_ctrl.nc file output

### ISSUE THREAD

**Issue by jokervTv** [NOAA-EMC/UFS_UTILS#844]
My environment is as follows

Version 1.10.0
Operating system: CentOS 7
Compiler: oneapi

and works fine, but when `chgres_cube` finishes, `sfc_ctrl.nc` is not found while `gfs_ctel.nc` is generated normally.

So, is there any plan to support sfc_ctrl.nc file output ?

Thanks for reading.

**Comment by GeorgeGayno-NOAA** [comment]
`chgres_cube` has never output a file called `sfc_ctrl.nc`. What is that file and why is it needed?

**Comment by jokervTv** [comment]
Hi,

I thought `sfc_ctrl.nc` needed by `ufs_model` was generated by `chgres_cube`.

I may have misunderstood the purpose of the program and the process of using ufs, so I will read the documentation carefully.

Thanks for reading and replying.
