### ISSUE TITLE
fix files versions

### ISSUE THREAD

**Issue by MarcusGDaniels** [NOAA-EMC/UFS_UTILS#845]
Hi, 

link_fixdirs.sh refers to versions like am/20220805 and raw/orog and sfc_climo/20221017.  

These files are not in https://ufs-data.s3.amazonaws.com/public_release/ufs-srweather-app-v1.0.0/fix/fix_files.tar.gz

Marcus

**Comment by GeorgeGayno-NOAA** [comment]
I don't work with the short-range weather app. I am guessing they only keep one set of fixed files to save space. Sylvia Chin is the one who populates the fixed data on aws. She pointed me to this location:

https://noaa-ufs-srw-pds.s3.amazonaws.com/index.html

You can contact her at sylvia.chin@noaa.gov

**Comment by GeorgeGayno-NOAA** [comment]
@MarcusGDaniels did Sylvia resolve this?

**Comment by GeorgeGayno-NOAA** [comment]
Will reopen if necessary.
