### ISSUE TITLE
Unable to install via stack: 'By not providing "Findwgrib2.cmake"'

### ISSUE THREAD

**Issue by jokervTv** [NOAA-EMC/UFS_UTILS#849]
when I try to install UFS_UTILS via spack

```console
$ spack install ufs-utils
```

I get error like:

<details><summary>Error message</summary>

<pre>
==> No binary for ufs-utils-1_6_0-ib6tinreexeufyacvh7s2hduk277cx6h found: installing from source
==> Using cached archive: /var/lib/spack/cache/source/_source-cache/archive/82/829ba4b50162e4202f96ec92a65b9fa824f71db65d2b63b70822db07d061cd92.tar.gz
==> No patches needed for ufs-utils
==> ufs-utils: Executing phase: 'cmake'
==> Error: ProcessError: Command exited with status 1
1 error found in build log:
     37    -- Found sigio: /var/lib/spack/packages/linux-manjaro23-icelake/gcc-13.2.1/sigio-2.3.2-l7hpls42ko
           jwv4ihn2tdlp7cab2aaigx/lib/libsigio.a (found version "2.3.0")
     38    -- Found sp: /var/lib/spack/packages/linux-manjaro23-icelake/gcc-13.2.1/sp-2.3.3-ybalppqs2xi6kem5
           n4hpx6q5gbauc4nb/lib/libsp_4.a (found version "2.3.3")
     39    -- Found ip: /var/lib/spack/packages/linux-manjaro23-icelake/gcc-13.2.1/ip-3.3.3-iijkvqbxotkd5dyn
           tgwb5y6fmk2dxsqx/lib/libip_4.a (found version "3.3.3")
     40    -- Found ZLIB: /var/lib/spack/packages/linux-manjaro23-icelake/gcc-13.2.1/zlib-1.2.13-rthwqptkpqa
           zmde5w63wkngahndkc5vh/lib/libz.so (found version "1.2.13")
     41    -- Found PNG: /var/lib/spack/packages/linux-manjaro23-icelake/gcc-13.2.1/libpng-1.6.39-mnut4me6mo
           5bcgzej4b2iqnrbz3wcdzi/lib/libpng.so (found version "1.6.39")
     42    -- Found g2: /var/lib/spack/packages/linux-manjaro23-icelake/gcc-13.2.1/g2-3.4.5-fr56h4leqvhpmtlx
           pwxqk7eq45haibnt/lib/libg2_4.a (found version "3.4.5")
  >> 43    CMake Error at CMakeLists.txt:64 (find_package):
     44      By not providing "Findwgrib2.cmake" in CMAKE_MODULE_PATH this project has
     45      asked CMake to find a package configuration file provided by "wgrib2", but
     46      CMake did not find one.
     47    
     48      Could not find a package configuration file provided by "wgrib2" (requested
     49      version 2.0.8) with any of the following names:
</pre></details>

But wgrib2 is installed.

```shell
❯ spack find wgrib2
-- linux-manjaro23-icelake / gcc@13.2.1 -------------------------
wgrib2@3.1.1
==> 1 installed package
```

There seems to be something wrong with "CMAKE_MODULE_PATH". Is it my system problem or some misconfiguration ？

Thanks for your reading.

**Comment by GeorgeGayno-NOAA** [comment]
Are you using the v1.6.0 tag?

https://github.com/ufs-community/UFS_UTILS/releases/tag/ufs_utils_1_6_0

**Comment by jokervTv** [comment]
Yes, there is only v1.6.0 in `spack`.

<details> <summary>spack info ufs-utils</summary>

```log
❯ spack info ufs-utils

CMakePackage:   ufs-utils

Description:
    The UFS Utilities package contains programs set up the model grid and
    create coldstart initial conditions. This is related to NOAA's NCEPLIBS
    project.

Homepage: https://noaa-emcufs-utils.readthedocs.io/en/latest/

Preferred version:  
    1_6_0    https://github.com/NOAA-EMC/UFS_UTILS/archive/refs/tags/ufs_utils_1_6_0.tar.gz

Safe versions:  
    1_6_0    https://github.com/NOAA-EMC/UFS_UTILS/archive/refs/tags/ufs_utils_1_6_0.tar.gz

Deprecated versions:  
    None
```
</details>

And I found that `spack` installs wgrib2 via makefile instead of cmake, so there is no `Findwgrib2.cmake` here.

<details> <summary>spack info wgrib2</summary>

```log
❯ spack info wgrib2

MakefilePackage:   wgrib2
...
Preferred version:  
    3.1.1    https://www.ftp.cpc.ncep.noaa.gov/wd51we/wgrib2/wgrib2.tgz.v3.1.1
...
Name [Default]             When    Allowed values    Description
    =======================    ====    ==============    ============================================================
    build_system [makefile]    --      makefile          Build systems supported by the package
...
```
</details>

**Comment by GeorgeGayno-NOAA** [comment]
v1.6.0 is two years old. I recommend you move to a newer version. I see support for newer tags in spack:

https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/ufs-utils/package.py

@Hang-Lei-NOAA, @edwardhartnett, @AlexanderRichert-NOAA can one of you assist?

**Comment by AlexanderRichert-NOAA** [comment]
I took out some of the older versions of ufs-utils from the spack recipe precisely to get rid of the wgrib2 dependency which has always been a headache. If possible, please use the updated spack recipe and install one of the more recent ufs-utils versions.

**Comment by jokervTv** [comment]
Wow, thanks a lot for the help.

In addition, in my test (using `spack` under the develop branch), the dependent library `g2@3.4.6` cannot be installed temporarily, and an error ```By not providing "Findw3emc.cmake"``` is encountered. After manually downgrading to `3.4.5`, the installation was successful.

Thanks again.

**Comment by GeorgeGayno-NOAA** [comment]
Glad to help.
