### ISSUE TITLE
Update lake code for new datasets and to fix coastal lake problem

### ISSUE THREAD

**Issue by NingWang325** [NOAA-EMC/UFS_UTILS#854]
An option is added to choose the observational datasets to generate lake mask and lake depth. GLDBv2 & GLDBv3 were used in the Prototype 6 and 7 applications. Lake fraction from MODIS+ (with Landset) and lake depth from GLDBv3 will be
used in the Prototype 8 application.

Since GLDBv3 is a debug version of GLDBv2, we keep GLDBv2 option for backward compatible reason and suggest using GLDBv3 for new applications.

Options for
-- lake fraction: GLDBv3, MODIS+ and VIIRS;
-- lake depth: GLDBv3 and GloBathy

A namelist is added to choose the dataset without recompiling the code.

New logic will also be added to remove coastal lakes.

**Comment by barlage** [comment]
@GeorgeGayno-NOAA add "inland lake code will be updated to fix coastal lakes"
