### ISSUE TITLE
Update WCOSS2 Modulefiles

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/UFS_UTILS#877]
The UFS now uses HPC-stack-built libraries, including updated netCDF (4.9.2) and ESMF (8.4.2) versions.  UFS_Utils should be updated to point to the same library versions.

**Comment by GeorgeGayno-NOAA** [comment]
@DavidHuber-NOAA what is the status of this issue? I see UFS has the use of this stack commented out:
https://github.com/ufs-community/ufs-weather-model/blob/develop/modulefiles/ufs_wcoss2.intel.lua#L17

**Comment by DavidHuber-NOAA** [comment]
@GeorgeGayno-NOAA I was waiting on a new versions of the ncdiag and ncio libraries to be installed (needed for the GSI) to start this work.  That was completed at the beginning of this month.  I'm hoping to tackle this next month.

I have updated the description to reflect the new library versions that this update will include.

**Comment by GeorgeGayno-NOAA** [comment]
@DavidHuber-NOAA - just want to verify the location of the stack. Is this it? 

`/apps/test/hpc-stack/i-19.1.3.304__m-8.1.12__h-1.14.0__n-4.9.2__p-2.5.10__e-8.6.0_pnetcdf/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.12`

**Comment by DavidHuber-NOAA** [comment]
@GeorgeGayno-NOAA The modules have been installed into production directories, so there is no need to manually append to the `MODULE_PATH` anymore.  See the current UFS module file for WCOSS2: https://github.com/ufs-community/ufs-weather-model/blob/develop/modulefiles/ufs_wcoss2.intel.lua for an example.

**Comment by GeorgeGayno-NOAA** [comment]
@DavidHuber-NOAA - I was able to compile. See 15438a9.

There are different versions of some libraries. Ex: esmf-A, esmf-B, esmf-C. What do the letters mean?

**Comment by DavidHuber-NOAA** [comment]
@GeorgeGayno-NOAA These letters represent how the dependent and downstream libraries were compiled and correspond to the netCDF, HDF5, and/or pnetcdf versions used in the compilation.  I am not sure if this convention will continue to be followed if netCDF and/or HDF5 are upgraded.

-A: netCDF v4.9.2, HDF5 v1.14.0, ESMF v8.4.2
-B: netCDF v4.9.2, HDF5 v1.14.0, ESMF v8.4.2
-C: netCDF v4.9.2, HDF5 v1.14.0, ESMF v8.6.0, pnetCDF v1.12.2

**Comment by GeorgeGayno-NOAA** [comment]
Originally, I thought to use IPLIB v4.1.0, since it was the latest version that is part of the stack. However, this caused the snow2mdl regression test to fail with large differences. So, I switched to v4.0.0 (6f42420) and now the tests pass as expected. 

Will alert the libraries team about a possible problem in v4.1.0.
