### ISSUE TITLE
Enable support on Hercules

### ISSUE THREAD

**Issue by BinLiu-NOAA** [NOAA-EMC/UFS_UTILS#878]
Since the spack-stack library is now available on MSU Hercules, it would be nice to enable UFS_UTILS's support on Hercules.

Note: @BijuThomas-NOAA was able to build and run UFS_UTILS on Hercules from HAFS application side.

**Comment by DavidHuber-NOAA** [comment]
I was just about to open this issue and start working on it.  If there is an existing fork, I'm happy to work with @BijuThomas-NOAA bring it in.

**Comment by BinLiu-NOAA** [comment]
Thanks, @DavidHuber-NOAA! From HAFS side, I believe @BijuThomas-NOAA had the following commit/changes:
https://github.com/hafs-community/UFS_UTILS/commit/146611c11eab65050a9489ad81a0746478ad7bdc
Just added a modulefile and the platform detection for Hercules. 

However, there are more other things need to be done for UFS_UTILS's fully support on Hercules (for example, enabling and setting up the regression test capabilities there). So, please feel free to coordinate with code/repo admin in terms of enabling the full support for Hercules. Thanks and much appreciated!
