### ISSUE TITLE
Upgrade to spack-stack 1.6.0

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/UFS_UTILS#884]
UFS_Utils should be upgraded to use the newest suite of spack-stack libraries (version 1.6.0). This includes an upgrade of CRTM to 2.4.0.1, netcdf-fortran to 4.6.1, and prod_util to 2.1.1.  This has already been tested successfully on Hercules on a test build of spack-stack, though official installations have not yet been rolled out.

**Comment by DavidHuber-NOAA** [comment]
@GeorgeGayno-NOAA The `c96_viirs.bnu` `grid_gen` test is failing on Jet with the error 
```
forrtl: severe (28): CLOSE error, unit 15, file "Unknown"
```
when the program is stopped at line [165 of mtnlm7_oclsm.F](https://github.com/ufs-community/UFS_UTILS/blob/bef91f05168e129ea94f4d2b6286dc96c848e45f/sorc/orog_mask_tools.fd/orog.fd/mtnlm7_oclsm.F#L165).  Looking through the code, I do not see any point where unit 15 is opened, though it is read at [line 598](https://github.com/ufs-community/UFS_UTILS/blob/bef91f05168e129ea94f4d2b6286dc96c848e45f/sorc/orog_mask_tools.fd/orog.fd/mtnlm7_oclsm.F#L568).  This seems like a bug, though Hera and Orion ran the test successfully.  Is this a known issue?

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA The `c96_viirs.bnu` `grid_gen` test is failing on Jet with the error
> 
> ```
> forrtl: severe (28): CLOSE error, unit 15, file "Unknown"
> ```
> 
> when the program is stopped at line [165 of mtnlm7_oclsm.F](https://github.com/ufs-community/UFS_UTILS/blob/bef91f05168e129ea94f4d2b6286dc96c848e45f/sorc/orog_mask_tools.fd/orog.fd/mtnlm7_oclsm.F#L165). Looking through the code, I do not see any point where unit 15 is opened, though it is read at [line 598](https://github.com/ufs-community/UFS_UTILS/blob/bef91f05168e129ea94f4d2b6286dc96c848e45f/sorc/orog_mask_tools.fd/orog.fd/mtnlm7_oclsm.F#L568). This seems like a bug, though Hera and Orion ran the test successfully. Is this a known issue?

I have not heard of the problem before.  Just curious if you are you able to run the head of 'develop' on Jet successfully.

**Comment by DavidHuber-NOAA** [comment]
Running the develop branch does not produce the error.  I'm going to run the spack-stack branch once more to see if this is intermittent or easily reproducible with the newest library versions.

**Comment by DavidHuber-NOAA** [comment]
Indeed, the job passed the second go around, so it seems to be intermittent.  I will open an issue.
