### ISSUE TITLE
Intermittent crash of c96.viirs.bnu test; unable to close file on stop

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/UFS_UTILS#888]
The `c96.viirs.bnu` test failed once, but could not be reproduced after two additional runs.  The failure was at the end of the program at line [165 of mtnlm7_oclsm.F](https://github.com/ufs-community/UFS_UTILS/blob/bef91f05168e129ea94f4d2b6286dc96c848e45f/sorc/orog_mask_tools.fd/orog.fd/mtnlm7_oclsm.F#L165).:
```
forrtl: severe (28): CLOSE error, unit 15, file "Unknown"
```
This error occurred while regression testing spack-stack/1.6.0 (#844) on Jet.  Additional tests on Orion, Hera, and Jet and with the develop branch on Jet did not reproduce the error.  Opening this issue for awareness and may close if I cannot recreate the error.

**Comment by GeorgeGayno-NOAA** [comment]
@DavidHuber-NOAA - this has been open for a while. Can I close it?

**Comment by DavidHuber-NOAA** [comment]
Yes, I have not seen the error again.  Closing.
