### ISSUE TITLE
Update "nst_tf_chg" program for GFS v15 and v16 data

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#90]
The nst_tf_chg program does not work with GFS v15 nemsio files.  When I try running it with the 'fv3gfs_chgres.sh' script, I get errors:

```
ERROR: the size of recname is not equal to the total number of the fields in the file!
readrecv for gfilei for zm  Status =          -42
writerecv for gfileo for zm  Status =          -73
readrecv for gfilei for ifd  Status =          -42
writerecv for gfileo for ifd  Status =          -73
```

The program will also need to work with GFS v16 gaussian netcdf files.

**Comment by GeorgeGayno-NOAA** [comment]
@XuLi-NOAA  What is the status of this?

**Comment by XuLi-NOAA** [comment]
@GeorgeGayno-NOAA : I am going to look at this. Basically, a new version is needed

**Comment by GeorgeGayno-NOAA** [comment]
@XuLi-NOAA  We have been going through old issues today.  Are you working on a new version?  Should we remove the current version, which you say does not work.

**Comment by XuLi-NOAA** [comment]
@GeorgeGayno-NOAA : I will look at this issue these days.

**Comment by edwardhartnett** [comment]
@XuLi-NOAA is this still necessary?

**Comment by XuLi-NOAA** [comment]
Not any more, it can be closed.
