### ISSUE TITLE
Broken links to example input data in `chgres_cube` documentation

### ISSUE THREAD

**Issue by spencerkclark** [NOAA-EMC/UFS_UTILS#905]
In [section 3.1.3.1 of the documentation](https://noaa-emcufs-utils.readthedocs.io/en/latest/ufs_utils.html#program-inputs-and-outputs-for-global-applications), which describes the input files needed for running `chgres_cube` there are some links which used to point to a directory of example input files:

```
https://ftp.emc.ncep.noaa.gov/EIB/UFS/global/fix/fix_fv3_gmted2010.v20191213/
```

This directory also contained logs of the scripts used to generate those input files, which were helpful for reference as well.  These links appear to be broken now.  Is there another source of these example files that could be linked to?

In general I've found the documentation quite helpful over the years, so I appreciate your work maintaining it!

**Comment by GeorgeGayno-NOAA** [comment]
Thanks for letting me know about the broken links.

Are you with GFDL? Do you have access to our RDHPCS systems? You can find the files there.

**Comment by spencerkclark** [comment]
Indeed I know where to find them on NOAA systems, but since I work with external collaborators I sometimes find it useful to be able to refer to these publicly hosted examples.  It's OK though if these links / files are a nuisance to maintain.

**Comment by GeorgeGayno-NOAA** [comment]
Looks like those directories were moved here:
https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/GFS/fix/fix_fv3_gmted2010/
https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/GFS/fix/fix_fv3_gmted2010/C48/fix_sfc/

I can update the documentation.

**Comment by spencerkclark** [comment]
Excellent, thanks!
