### ISSUE TITLE
gdas_init routine fails when processing GDAS v15 data

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#908]
When coldstarting a global cycle with v15 GDAS or v16 retro GDAS data, the chgres step fails because the orography data for the input grid does not exist.  The orography data is required when using the 'warm' restart files as input to chgres because the orography record is not included in the restart files.

I think the problem started when the orography files were updated at #881.

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA - FYI.

**Comment by KateFriedman-NOAA** [comment]
Noted, thanks for letting me know @GeorgeGayno-NOAA !
