### ISSUE TITLE
Update RDHPCS Hera to Rocky-8 compliance 

### ISSUE THREAD

**Issue by HenryRWinterbottom** [NOAA-EMC/UFS_UTILS#913]
**Description**

RDHPCS Hera is being upgraded to Linux [Rocky version 8](https://rockylinux.org/). As a result all build applications, namely module files must be updated accordingly.

**Required Functionality**

A UFS based applications used by the UFS global-workflow must be updated to Rocky-8.

**Proposed Solution**

Update all UFS global-workflow applications to Rocky-8 compatability.

**Definition of Completion**

The global-workflow and the associated UFS applications reproduce RHEL 8 instances. Further, all unit-tests pass with success.

**Related Issues**

Global workflow issue [#2329](https://github.com/NOAA-EMC/global-workflow/issues/2329)

**Comment by GeorgeGayno-NOAA** [comment]
I have been looking at your branch. The regression tests are passing. However, I had to make some minor changes to two driver scripts to get them working. See my changes here:
 - `/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.henry/reg_tests/ice_blend/driver.hera.sh.rocky8`
 - `/scratch1/NCEPDEV/da/George.Gayno/ufs_utils.git/UFS_UTILS.henry/reg_tests/snow2mdl/driver.hera.sh.rocky8`

**Comment by HenryRWinterbottom** [comment]
@GeorgeGayno-NOAA I assume that you would like me to add these changes to my branch?

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA I assume that you would like me to add these changes to my branch?

Yes.

**Comment by HenryRWinterbottom** [comment]
Done.
