### ISSUE TITLE
Resolve problem related to wind field errors at initialization for JPgrid 

### ISSUE THREAD

**Issue by JeffBeck-NOAA** [NOAA-EMC/UFS_UTILS#93]
@JeffBeck-NOAA @gsketefian @LarissaReames-NOAA

**Comment by GeorgeGayno-NOAA** [comment]
What is the nature of the error?

**Comment by JeffBeck-NOAA** [comment]
Our hypothesis is that there may be missing metadata that is required by
FV3 to correctly rotate the earth-relative winds that are output by
chgres_cube for the JPgrid (when using the regional_grid utility).  We
discovered this potential bug when verifying initialization wind speed RMSE
and bias with the JPgrid (using either FV3GFS or HRRRX ICs, they both have
significant RMSE/bias) when compared to the HRRRX initialization.  We're
working on verifying the chgres_cube output directly, and testing a
GFDLgrid to see if that produces the same errors.  If you have any input on
how the winds are rotated to the final Gnomonic grid in FV3, and whether
any metadata from make_hgrid is used (for the GFDLgrid), that would be
appreciated.

**Comment by GeorgeGayno-NOAA** [comment]
Sorry, I don't know the details on how the winds are rotated by the model.  I do know that chgres_cube always outputs the winds as "earth relative", not turned to the grid.

**Comment by JeffBeck-NOAA** [comment]
We've identified that the wind rotation problem was occurring in the verification, and not in the model data.  Since the regional models we've dealt with in the past have output grib2 files with grid-relative winds, MATS was rotating the RAOB data to the LCC grid prior to verification, resulting in large RMSE/bias.  We will be modifying the code to read the grib2 metadata flag that defines either grid or earth-relative winds (fixed for SAR output by Jili Dong in January) to tell the verification code whether rotation of the RAOB data is required or not.

Fortunately, this means that the FV3 wind initialization code does not need to be modified for the JP/ESG grid, and it's possible for use to switch back over to this much more uniform option.
