### ISSUE TITLE
Create unit tests for ocean_merge code

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#944]
Follow the procedures used in other programs:

- Place the 'guts' of the program into Fortran modules that are accessed by a simple driver.
- Modify build to create a library that is linked by the driver.
- Create unit tests that link to the library.

Unit tests should be created for all major functions of the code:

- The read of the orography file.
- The read of the namelist file.
- The loop that merges the land and ocean masks along coastlines.
- The write of the updated orography file.

**Comment by HenryRWinterbottom** [comment]
@GeorgeGayno-NOAA My branch for this issue is [#944](https://github.com/HenryWinterbottom-NOAA/UFS_UTILS/tree/feature/ufs_utils_issue_944).

Is there a plan to add the respective test files to the FTP site for the `ocean_merge` application unit-tests?

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA My branch for this issue is [#944](https://github.com/HenryWinterbottom-NOAA/UFS_UTILS/tree/feature/ufs_utils_issue_944).
> 
> Is there a plan to add the respective test files to the FTP site for the `ocean_merge` application unit-tests?

If your tests require large binary input data, we can host it here:
https://ftp.emc.ncep.noaa.gov/static_files/public/UFS/ufs_utils/unit_tests/

Small ASCII data files can be stored in Github. For example:
https://github.com/ufs-community/UFS_UTILS/tree/develop/tests/chgres_cube/data

**Comment by HenryRWinterbottom** [comment]
@GeorgeGayno-NOAA I have finished a first cut of the `ocean_merge` refactor. Please see [here](https://github.com/HenryWinterbottom-NOAA/UFS_UTILS/tree/feature/ufs_utils_issue_944).

I implemented the `ncio` package. This is a NCEP-libs supported package but will require a spack-stack update. Further, some additions to the CMake application are also required. If/when you are OK with the refactoring, I can update the CMake accordingly and finish up the unit-tests.

Please let me know how you'd like to proceed.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA I have finished a first cut of the `ocean_merge` refactor. Please see [here](https://github.com/HenryWinterbottom-NOAA/UFS_UTILS/tree/feature/ufs_utils_issue_944).
> 
> I implemented the `ncio` package. This is a NCEP-libs supported package but will require a spack-stack update. Further, some additions to the CMake application are also required. If/when you are OK with the refactoring, I can update the CMake accordingly and finish up the unit-tests.
> 
> Please let me know how you'd like to proceed.

This looks fine. 

What spack-stack update is required?

**Comment by HenryRWinterbottom** [comment]
@GeorgeGayno-NOAA We will need to make sure `ncio` is included in the stack. I can make that PR, I just wanted to make sure we were on the same page before diving in.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA We will need to make sure `ncio` is included in the stack. I can make that PR, I just wanted to make sure we were on the same page before diving in.

I checked Hercules and Hera. `ncio` was part of the stack. But I did not find `ncio` on WCOSS2. Getting libraries installed on WCOSS2 is not a quick or simple process. So, I would move forward with the assumption that `ncio` is not available.

**Comment by HenryRWinterbottom** [comment]
@GeorgeGayno-NOAA OK, thank you for checking into that.

I will need to rewrite some code, but it shouldn't be too terrible. I will follow-up here once I do.

Thanks again.

**Comment by HenryRWinterbottom** [comment]
@GeorgeGayno-NOAA I made appropriate updates, including to the relevant `CMakeList.txt`.

This simplifies things a bit, and as discussed, removes the `ncio` dependency thus saving a PR into spack-stack and provides WCOSS compatibility. 

Please review. Once you are satisfied, I can finish up the respective unit-tests.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA I made appropriate updates, including to the relevant `CMakeList.txt`.
> 
> This simplifies things a bit, and as discussed, removes the `ncio` dependency thus saving a PR into spack-stack and provides WCOSS compatibility.
> 
> Please review. Once you are satisfied, I can finish up the respective unit-tests.

This looks fine.

**Comment by GeorgeGayno-NOAA** [comment]
@HenryWinterbottom-NOAA - please cease work on this issue for now.
