### ISSUE TITLE
build UFS_UTIL error on Hera

### ISSUE THREAD

**Issue by bingfu-NOAA** [NOAA-EMC/UFS_UTILS#946]
Build error found on Hera when executing build_all.sh. 
"-- Found OpenMP_Fortran: -qopenmp (found version "5.0") 
-- Found OpenMP: TRUE (found version "5.0") found components: Fortran 
CMake Error at /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8/install/intel/2021.5.0/cmake-3.23.1-qjplcak/share/cmake-3.23/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "Findbacio.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "bacio", but
  CMake did not find one.

  Could not find a package configuration file provided by "bacio" with any of
  the following names:

    bacioConfig.cmake
    bacio-config.cmake

  Add the installation prefix of "bacio" to CMAKE_PREFIX_PATH or set
  "bacio_DIR" to a directory containing one of the above files.  If "bacio"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8/install/intel/2021.5.0/w3emc-2.10.0-xer6twa/lib64/cmake/w3emc/w3emc-config.cmake:43 (find_dependency)
  CMakeLists.txt:105 (find_package)

-- Configuring incomplete, errors occurred!

"

**Comment by GeorgeGayno-NOAA** [comment]
I just checked out the head of 'develop' (7034628) on Hera. It built with no problems. What hash are you using?

**Comment by bingfu-NOAA** [comment]
I was using head of 'develop' hash 7034628. Thanks for checking, it must something wrong with my environmental settings. 
Do you know if there is any update needed after Rocky8 migration from user side?

**Comment by GeorgeGayno-NOAA** [comment]
> I was using head of 'develop' hash [7034628](https://github.com/ufs-community/UFS_UTILS/commit/7034628893ab392105df8e81c451eced960d8959). Thanks for checking, it must something wrong with my environmental settings. Do you know if there is any update needed after Rocky8 migration from user side?

Can you pipe the entire standard output to a log file? I.e., ./build_all.sh >& log

**Comment by bingfu-NOAA** [comment]
Here is the log file:
/scratch2/NCEPDEV/ensemble/Bing.Fu/UFS_UTILS/log

**Comment by bingfu-NOAA** [comment]
Hi George, I think it is due to the hpc-stack setting in my environment.
I can build the utility after I commented out the following
#module use -a /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/stack
#module load hpc/1.1.0
#module load hpc-intel/2022.1.2
#module load nco/4.9.1
#module load netcdf/4.7.0
#module load wgrib2
#module load cdo/2.3.0

Thanks, you might close this issue.

**Comment by GeorgeGayno-NOAA** [comment]
> Hi George, I think it is due to the hpc-stack setting in my environment. I can build the utility after I commented out the following #module use -a /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/stack #module load hpc/1.1.0 #module load hpc-intel/2022.1.2 #module load nco/4.9.1 #module load netcdf/4.7.0 #module load wgrib2 #module load cdo/2.3.0
> 
> Thanks, you might close this issue.

The build script does a 'module purge', so I would think that would override your environment settings. Maybe it does not like the 'module use -a'.

One thing I noticed is that you were not loading all the modules:

```
Currently Loaded Modules:
  1) hpss/hpss                         8) cmake/3.23.1  15) sigio/2.3.2        22) hdf5/1.14.0             29) netcdf/4.9.0
  2) intel/2022.1.2                    9) g2/3.4.5      16) zlib/1.2.13        23) netcdf-c/4.9.2          30) nco/5.0.6
  3) stack-intel/2021.5.0             10) ip/4.3.0      17) libpng/1.6.37      24) netcdf-fortran/4.6.1    31) build.hera.intel
  4) impi/2022.1.2                    11) bacio/2.4.1   18) snappy/1.1.10      25) nccmp/1.9.0.1
  5) stack-intel-oneapi-mpi/2021.5.1  12) nemsio/2.5.4  19) zstd/1.5.2         26) parallel-netcdf/1.12.2
  6) nghttp2/1.57.0                   13) sp/2.5.0      20) c-blosc/1.21.5     27) parallelio/2.5.10
  7) curl/8.4.0                       14) w3emc/2.10.0  21) pkg-config/0.27.1  28) esmf/8.6.0

```

This is what you should get:

```
Currently Loaded Modules:
  1) hpss/hpss                         6) nghttp2/1.57.0  11) jasper/2.0.32  16) w3emc/2.10.0   21) zstd/1.5.2         26) netcdf-fortran/4.6.1    31) antlr/2.7.7
  2) intel/2022.1.2                    7) curl/8.4.0      12) g2/3.4.5       17) sigio/2.3.2    22) c-blosc/1.21.5     27) nccmp/1.9.0.1           32) gsl/2.7.1
  3) stack-intel/2021.5.0              8) cmake/3.23.1    13) ip/4.3.0       18) zlib/1.2.13    23) pkg-config/0.27.1  28) parallel-netcdf/1.12.2  33) udunits/2.2.28
  4) impi/2022.1.2                     9) bacio/2.4.1     14) nemsio/2.5.4   19) libpng/1.6.37  24) hdf5/1.14.0        29) parallelio/2.5.10       34) nco/5.0.6
  5) stack-intel-oneapi-mpi/2021.5.1  10) libjpeg/2.1.0   15) sp/2.5.0       20) snappy/1.1.10  25) netcdf-c/4.9.2     30) esmf/8.6.0              35) build.hera.intel

```

**Comment by GeorgeGayno-NOAA** [comment]
> Hi George, I think it is due to the hpc-stack setting in my environment. I can build the utility after I commented out the following #module use -a /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/stack #module load hpc/1.1.0 #module load hpc-intel/2022.1.2 #module load nco/4.9.1 #module load netcdf/4.7.0 #module load wgrib2 #module load cdo/2.3.0
> 
> Thanks, you might close this issue.

Ok. Closing.
