### ISSUE TITLE
Optimize orog.fd code

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#947]
The orog.fd code is threaded, but not very scalable. Look for additional opportunities to optimize it.

**Comment by GeorgeGayno-NOAA** [comment]
I set up a regional grid test case (1311 x 610) on Hercules. 

The scripts and data to run this test is located here: `/work2/noaa/da/ggayno/save/orog.omp`

**Comment by GeorgeGayno-NOAA** [comment]
Running the regional grid test using ca3fccc using one thread showed these timings (in seconds):

`Total runtime time=    206.983000000000`

Most of the time (199.3 seconds) was spent in three subroutines:

```
MAKEMT2 time=    33.8209999999963
MAKEPC2 time=    16.6759999999995
MAKEOA2 time=    148.803000000000
```

The remaining time (about 6 seconds) is spent in i/o (reading the hi-resolution input terrain and mask data).

**Comment by GeorgeGayno-NOAA** [comment]
The routines MAKEMT2, MAKEPC2 and MAKEOA2 already contain threads. The scaling was checked by rerunning the regional test case using 18 threads.

Total time was reduced.

`Total runtime time=    18.1710000000021`

And the threaded routines showed about a 16.5x speed up.

```
  MAKEMT2 time=    2.04699999999866
  MAKEPC2 time=    1.01200000000244
  MAKEOA2 time=    8.77399999999761
```

This is very scalable.

**Comment by GeorgeGayno-NOAA** [comment]
Given that the i/o part of the code can't be threaded, and is only a small percentage of the total execution time, I don't see many opportunities for further optimizing.

Perhaps this single test case in not representative.

@BinLiu-NOAA - comments? Should I try your test case?

**Comment by BinLiu-NOAA** [comment]
@GeorgeGayno-NOAA, Appreciate it if you can try my HAFS test case from your end as well. Please see the following dir on Cactus for my test case:
/lfs/h2/emc/ptmp/bin.liu/hafsv2_20240509_hfsa_test/2021082712/09L/atm_prep_mvnest1res/orog
For the related job log, you can see /lfs/h2/emc/ptmp/bin.liu/hafsv2_20240509_hfsa_test/2021082712/09L/hafs_atm_prep_mvnest.log
For example, the related time info:
```
  ===== Deallocate Arrays and ENDING MTN VAR OROG program
  Total runtime time=    265.706000000000
Application e12a636a-fe6c-4845-adf5-6ed10a3f73dd resources: utime=3543s stime=5s maxrss=13481844KB inblock=2267768 oublock=2712040 minflt=29420 majflt=2 nvcsw=642 nivcsw=1640

```
Please feel free to let me know if you need any other information. Thanks!

**Comment by GeorgeGayno-NOAA** [comment]
Set up Bin's case on Hercules. It is a regional case with grid dimensions of 4350x3990. I used this script: /work2/noaa/da/ggayno/save/orog.omp/run.C5133.sh.

Running with one thread took a little over 3300 seconds 

` Total runtime time=    3316.50300000000`

And most of the time (3300.14 seconds) was spent in three routines:

```
  MAKEMT2 time=    425.853000000003
  MAKEPC2 time=    211.006000000001
  MAKEOA2 time=    2663.24000000000
```

MAKEOA2, which computes orographic asymmetry and length scale, is by far the most expensive part of the code.

**Comment by GeorgeGayno-NOAA** [comment]
Re-running with 18 threads showed:

```
  Total runtime time=    257.890000000007
  MAKEMT2 time=    32.8779999999970
  MAKEPC2 time=    16.2450000000026
  MAKEOA2 time=    192.803000000000
```

The speed up is:

- MAKEMT2 - ~13x
- MAKEPC2 - ~13x
- MAKEOA2 - ~14x
- Total time - ~13x

Not as scalable as the smaller regional grid test: https://github.com/ufs-community/UFS_UTILS/issues/947#issuecomment-2118157422

**Comment by GeorgeGayno-NOAA** [comment]
The `orog_gsl` code outputs the same fields (it appears) as MAKEOA2. When the GSL GWD option is chosen, are the fields created by MAKEOA2 even used? If not, an option could be added to bypass the call of that routine?

**Comment by BinLiu-NOAA** [comment]
Hi @GeorgeGayno-NOAA, sorry for the late follow-up, I did another test by increasing the NUM_OMP_THREAD from 20 to 40, for the make_orog step for the same/above HAFS test. And the wallclock time reduced from:  
Total runtime time=    265.706000000000
down to
Total runtime time=    136.516000000003
With that, looks to me the threading speeding up is still good with 40 threads.  Also the time of ~ 136s is also good enough for currently HAFS application. 

Thanks a lot for these additional exploration/testing, @GeorgeGayno-NOAA! Please feel free to close this issue as you see fit.

**Comment by GeorgeGayno-NOAA** [comment]
@BinLiu-NOAA - I will close. It can always be reopened if necessary.
