### ISSUE TITLE
HREFv3 support

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#95]
Matt Pyle requested a release branch to support HREFv3.

HREF uses chgres_cube.

**Comment by GeorgeGayno-NOAA** [comment]
Guidance from Matt: "The code handoff is months away, but the code freeze is scheduled for April 8th".

**Comment by GeorgeGayno-NOAA** [comment]
Latest from Matt: the code handoff is scheduled for the latter half of August.

**Comment by GeorgeGayno-NOAA** [comment]
@MatthewPyle-NOAA requested another branch that includes a version of chgres_cube that can ingest GFS v16 NetCDF data.

**Comment by GeorgeGayno-NOAA** [comment]
> @MatthewPyle-NOAA requested another branch that includes a version of chgres_cube that can ingest GFS v16 NetCDF data.
> 
> New branch created at [6d3b5eb](https://github.com/NOAA-EMC/UFS_UTILS/commit/6d3b5eb4e71ab582cf2342cc77a9aeac968f805b).

@MatthewPyle-NOAA on what machine are you implementing this latest release?  Dell or Cray?

**Comment by MatthewPyle-NOAA** [comment]
It is on the Cray

**Comment by MatthewPyle-NOAA** [comment]
I submitted a CDF including this branch already today - is it still okay?

**Comment by GeorgeGayno-NOAA** [comment]
> I submitted a CDF including this branch already today - is it still okay?

The branch at fa6522d?

**Comment by MatthewPyle-NOAA** [comment]
Yes - the branch you updated 10 days ago.

**Comment by GeorgeGayno-NOAA** [comment]
> Yes - the branch you updated 10 days ago.

That is pointing to the official wgrib2, but in a test directory.  And the esmf library not official.  I am working to remove non-OPS libraries from everyone's release branch.  Can you hold off on the CDF for another day?

**Comment by MatthewPyle-NOAA** [comment]
I'm guessing NCO won't grab it immediately, but once you have finalized things I can send Steven Earle a note about it to be safe.  As long as the branch name doesn't change it should be fine.

**Comment by GeorgeGayno-NOAA** [comment]
@MatthewPyle-NOAA I updated `release/ops-hrefv3.1` to point to the official wgrib2 v2.0.8.  This release branch should be in final form.  Release branches are supposed to be temporary (until a tag is created). Did you submit a CDF for your implementation yet?   If so, are they to pull the release branch?

**Comment by edwardhartnett** [comment]
What's the status of this issue?

**Comment by MatthewPyle-NOAA** [comment]
I just submitted a fresh CDF today to NCO - it still checks out release/ops-hrefv3.1.

**Comment by GeorgeGayno-NOAA** [comment]
@MatthewPyle-NOAA I will keep `release/ops-hrefv3.1` and also create a tag from it. If there is another CDF, please point NCO to the tag and not the release branch.
