### ISSUE TITLE
Replace script variables ${FIXorog} with $(FIXgfs}/orog

### ISSUE THREAD

**Issue by GeorgeGayno-NOAA** [NOAA-EMC/UFS_UTILS#955]
Per the request of the global workflow group:
https://github.com/NOAA-EMC/global-workflow/pull/2632#issuecomment-2138889821

**Comment by guoqing-noaa** [comment]
@GeorgeGayno-NOAA Thanks for creating the issue. 

We would like to make two replacements:
`${FIXgfs}/orog`  to `${FIXorog}`
`${FIXgfs}/ugwd` to `${FIXugwd}`

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA Thanks for creating the issue.
> 
> We would like to make two replacements: `${FIXgfs}/orog` to `${FIXorog}` `${FIXgfs}/ugwd` to `${FIXugwd}`

Is `$FIXgfs` being removed or should I retain it?
