### ISSUE TITLE
UFS_UTILS on C6

### ISSUE THREAD

**Issue by BijuThomas-NOAA** [NOAA-EMC/UFS_UTILS#960]
The spack-stack is available on the Gaea C6 and wondering if  UFS_UTILS is tested or if there is a plan to test it on the Gaea C6 platform.
/autofs/ncrc-svm1_proj/epic/spack-stack/spack-stack-1.6.0/envs/unified-env-c6/install/modulefiles/Core

**Comment by GeorgeGayno-NOAA** [comment]
Gaea is not a Tier 1 platform. So, UFS_UTILS is not officially supported there.  And I don't have access to Gaea.

Are you volunteering to do the testing?

**Comment by BijuThomas-NOAA** [comment]
@GeorgeGayno-NOAA Sure, I can work on it next week. In fact, the build is successful on C6.

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA Sure, I can work on it next week. In fact, the build is successful on C6.

Great.

**Comment by BijuThomas-NOAA** [comment]
@GeorgeGayno-NOAA I am able to successfully complete HAFS end-to-end system (which includes UFS_UTILS) on C6

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA I am able to successfully complete HAFS end-to-end system (which includes UFS_UTILS) on C6

Great. When you are ready, issue a pull request.

**Comment by GeorgeGayno-NOAA** [comment]
@BijuThomas-NOAA - what is the status of this issue?

**Comment by BijuThomas-NOAA** [comment]
@GeorgeGayno-NOAA - A pull request(https://github.com/ufs-community/UFS_UTILS/pull/988) has been issued.
