### ISSUE TITLE
UFS-Utils Installation on NCAR HPC Derecho

### ISSUE THREAD

**Issue by muradme** [NOAA-EMC/UFS_UTILS#964]
Hi,

I am a new user of the Unified Forecast System (UFS), focusing on the Hurricane Analysis and Forecast System (HAFS). I am working on the NCAR HPC system, Derecho, where UFS installation is supported.

However, I have encountered difficulties installing UFS-Utils on Derecho, as it is not supported till now. Additionally, I could not find any links or resources for the necessary fix files to generate input files using UFS-Utils on this system.

Could you add support for UFS-Utils on NCAR HPC Derecho? Alternatively, if there is already a way to generate input files for UFS on Derecho, could you provide guidance or documentation on how to achieve this?

Thank you for your assistance.

Thanks,
Murad.

**Comment by GeorgeGayno-NOAA** [comment]
I don't have access to Derecho, so unfortunately, I am unable to assist. 

You want to generate input files to coldstart the UFS?

**Comment by muradme** [comment]
yes, thats correct. Especially, I want to create input files to coldstart UFS for HAFS configuration in derecho.

**Comment by GeorgeGayno-NOAA** [comment]
@BinLiu-NOAA - do you know of any HAFS developers who work on Derecho?

**Comment by muradme** [comment]
@GeorgeGayno-NOAA  on a relevant issue, UFS weather model (https://github.com/ufs-community/ufs-weather-model?tab=readme-ov-file) is supported for derecho. I could install it in derecho, and run the regression tests for HAFS configuration. So, for that code, can I use UFS-utils to generate the input files? Do you support this for derecho? Or is there any other way to generate inputs for that code?

**Comment by GeorgeGayno-NOAA** [comment]
> @GeorgeGayno-NOAA on a relevant issue, UFS weather model (https://github.com/ufs-community/ufs-weather-model?tab=readme-ov-file) is supported for derecho. I could install it in derecho, and run the regression tests for HAFS configuration. So, for that code, can I use UFS-utils to generate the input files? Do you support this for derecho? Or is there any other way to generate inputs for that code?

Do you have access to any of the NOAA RDHPCS machines (e.g., Hera)? Are you working with the HAFS group at NCEP/EMC?

**Comment by muradme** [comment]
No, I dont have access to any of the NOAA RDHPCS machines, and I am not working with the HAFS group at NCEP/EMC. I am a PhD student from University of Houston, and I am going to work on HAFS as a part of my PhD research.

**Comment by GeorgeGayno-NOAA** [comment]
> No, I dont have access to any of the NOAA RDHPCS machines, and I am not working with the HAFS group at NCEP/EMC. I am a PhD student from University of Houston, and I am going to work on HAFS as a part of my PhD research.

Unfortunately, I don't have access to derecho. Maybe you can try the Q/A forum: https://github.com/orgs/ufs-community/discussions/categories/q-a

What exactly is the problem with the install on derecho?

**Comment by muradme** [comment]
The installation of UFS-utils stops as there is no links for fix files in derecho (I understand, as it is not supported in derecho). Can you provide me with the fix files, in github or ftp server or in any other way possible?

**Comment by GeorgeGayno-NOAA** [comment]
> The installation of UFS-utils stops as there is no links for fix files in derecho (I understand, as it is not supported in derecho). Can you provide me with the fix files, in github or ftp server or in any other way possible?

Check here: https://noaa-ufs-srw-pds.s3.amazonaws.com/index.html#fix/

**Comment by muradme** [comment]
Thank you for sharing the fix files. While going through this, I have found that some fix files are not there (eg., fix_fv3_gmted2010, fix_vi, fix_hycom, fix_mom6, fix_ww3, fix_cdeps). I was going through the HAFS code and found the directory where all the fix files are stored. I would really appreciate if you could provide me with all this files. I am here attaching screenshot of fix file location. Again, thank you for your help on this matter.

![Screenshot from 2024-06-28 08-34-42](https://github.com/ufs-community/UFS_UTILS/assets/92276205/31a4aa3e-506c-4f2d-a39d-064e9bd24dee)

**Comment by GeorgeGayno-NOAA** [comment]
> Thank you for sharing the fix files. While going through this, I have found that some fix files are not there (eg., fix_fv3_gmted2010, fix_vi, fix_hycom, fix_mom6, fix_ww3, fix_cdeps). I was going through the HAFS code and found the directory where all the fix files are stored. I would really appreciate if you could provide me with all this files. I am here attaching screenshot of fix file location. Again, thank you for your help on this matter.
> 
> ![Screenshot from 2024-06-28 08-34-42](https://private-user-images.githubusercontent.com/92276205/344180624-31a4aa3e-506c-4f2d-a39d-064e9bd24dee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1ODc4MzQsIm5iZiI6MTcxOTU4NzUzNCwicGF0aCI6Ii85MjI3NjIwNS8zNDQxODA2MjQtMzFhNGFhM2UtNTA2Yy00ZjJkLWEzOWQtMDY0ZTliZDI0ZGVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDE1MTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZWRhYmJlYzYzZjcwOTIxZjQ0OGU4ZDhmNDk2OWFkOTgzMzUxZjkwYWIzNjhmODQwN2JmYmFjYTI5ODkzNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8ABqUzsETJe37yOeM7jDAekflTWW7bkW179VnAK9B00)

UFS_UTILS does not use most of those data directories. And I don't know where those data are.

I recommend you contact EPIC, who is charged with supporting community users: https://epic.noaa.gov/get-support/
