### ISSUE TITLE
no access to fix directories on gaea-c5

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/UFS_UTILS#971]
On GaeaC5, at develop 3ef2e6bd I can link the directories (./link_fixdirs.sh emc gaea) but I cannot ``ls`` or ``cp`` any of them.  I need to copy the fix files used by the UWM coupled configs into a sandbox run directory on gaea. I am not an epic project member, afaik.

```
ls /gpfs/f5/epic/proj-shared/global/glopara/data/fix/am/20220805
ls: cannot access '/gpfs/f5/epic/proj-shared/global/glopara/data/fix/am/20220805': Permission denied
```

**Comment by GeorgeGayno-NOAA** [comment]
@DeniseWorthen is this a UFS_UTILS issue or a permissions issue? Is this an EPIC owned directory?

**Comment by DeniseWorthen** [comment]
I think it is because it is an EPIC owned directory. We have the same issue in UWM, where the baselines and input reside in a world-shared directory (``/gpfs/f5/epic/world-shared/UFS-WM_RT/NEMSfv3gfs``).

**Comment by GeorgeGayno-NOAA** [comment]
> I think it is because it is an EPIC owned directory. We have the same issue in UWM, where the baselines and input reside in a world-shared directory (`/gpfs/f5/epic/world-shared/UFS-WM_RT/NEMSfv3gfs`).

Do you know who in EPIC can help? I will assign the issue to them.

**Comment by GeorgeGayno-NOAA** [comment]
@KateFriedman-NOAA do you work with EPIC to host the fixed data on some machines?

**Comment by DeniseWorthen** [comment]
The fix directories on Gaea were added in this https://github.com/ufs-community/UFS_UTILS/pull/935 by @DavidBurrows-NCO

**Comment by DavidBurrows-NCO** [comment]
Hi @DeniseWorthen @GeorgeGayno-NOAA. Yes..this is a project code permission issue with proj-shared directories.  I also have the fix files at /gpfs/f5/ufs-ard/**world-shared**/global/glopara/data/fix.  These world-shared directories are available to everyone. I see some broken links at the world-shared location. Let me double check those, and I will respond back to this issue.

**Comment by DavidBurrows-NCO** [comment]
@DeniseWorthen @GeorgeGayno-NOAA The broken links have been corrected. I have also created a PR #972 to address the correct link in fix/link_fixdirs.sh.

**Comment by DeniseWorthen** [comment]
@DavidBurrows-NCO Thanks for your help.
